import{id,el,button}from'./state.js';

const STORE='pacefold.stream.v1';
const YT_API='https://www.youtube.com/iframe_api';

function readSaved(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')||{}}catch{return{}}}
function saveSaved(value){try{localStorage.setItem(STORE,JSON.stringify(value))}catch{}}
function mediaFrom(value){
  const raw=String(value||'').trim();if(!raw)return null;
  if(/^[A-Za-z0-9_-]{11}$/.test(raw))return{videoId:raw,listId:'',url:`https://www.youtube.com/watch?v=${raw}`};
  let url;try{url=new URL(raw)}catch{return null}
  if(url.protocol!=='https:'||url.username||url.password)return null;
  const host=url.hostname.replace(/^www\./,'').toLowerCase();if(!['youtube.com','music.youtube.com','youtu.be'].includes(host))return null;
  let videoId='',listId=url.searchParams.get('list')||'';
  if(host==='youtu.be')videoId=url.pathname.split('/').filter(Boolean)[0]||'';
  else{videoId=url.searchParams.get('v')||'';const parts=url.pathname.split('/').filter(Boolean);if(!videoId&&['shorts','embed','live'].includes(parts[0]))videoId=parts[1]||''}
  if(videoId&&!/^[A-Za-z0-9_-]{11}$/.test(videoId))videoId='';if(listId&&!/^[A-Za-z0-9_-]{6,}$/.test(listId))listId='';if(!videoId&&!listId)return null;
  const canonical=videoId?`https://www.youtube.com/watch?v=${videoId}${listId?`&list=${encodeURIComponent(listId)}`:''}`:`https://www.youtube.com/playlist?list=${encodeURIComponent(listId)}`;
  return{videoId,listId,url:canonical};
}
function timeText(seconds){const total=Math.max(0,Math.floor(Number(seconds)||0)),minutes=Math.floor(total/60),rest=String(total%60).padStart(2,'0');return`${minutes}:${rest}`}
function cleanLibrary(value){return(Array.isArray(value)?value:[]).filter(item=>item&&mediaFrom(item.url)).slice(0,24).map(item=>{const media=mediaFrom(item.url);return{url:media.url,title:String(item.title||'Saved music').slice(0,120),author:String(item.author||'YouTube').slice(0,100),type:media.listId?'playlist':'track',addedAt:Number(item.addedAt)||Date.now()}})}

let ytPromise;
function loadYouTube(){
  if(window.YT?.Player)return Promise.resolve(window.YT);if(ytPromise)return ytPromise;
  ytPromise=new Promise((resolve,reject)=>{
    const previous=window.onYouTubeIframeAPIReady;let settled=false;
    const done=()=>{if(settled)return;settled=true;if(window.YT?.Player)resolve(window.YT);else reject(new Error('YouTube player API unavailable'))};
    window.onYouTubeIframeAPIReady=()=>{try{previous?.()}finally{done()}};
    let script=document.querySelector('script[data-pacefold-youtube]');if(!script){script=document.createElement('script');script.src=YT_API;script.async=true;script.referrerPolicy='strict-origin-when-cross-origin';script.dataset.pacefoldYoutube='true';document.head.append(script)}
    script.addEventListener('error',()=>{if(!settled){settled=true;reject(new Error('Could not load YouTube player'))}},{once:true});setTimeout(()=>{if(!settled){settled=true;reject(new Error('YouTube player timed out'))}},12000);
  });return ytPromise;
}

export function installStreamPlayer(ctx){
  const sound=id('sound-bar');if(!sound||id('stream-player'))return;
  sound.dataset.streaming='player';sound.setAttribute('aria-label','Streaming music player');for(const child of[...sound.children])child.hidden=true;
  const shell=el('section','stream-player');shell.id='stream-player';shell.dataset.state='empty';shell.dataset.artwork='empty';
  const video=el('div','stream-video');video.id='stream-video';video.hidden=true;let mount=el('div','stream-video-mount');mount.id='stream-youtube';const videoClose=button('stream-video-close','Pause and collapse video','×');video.append(mount,videoClose);
  const dock=el('div','stream-dock');
  const source=button('stream-source','Choose music');source.id='stream-source';source.append(el('i'),el('span','','Music'));
  const meta=el('div','stream-meta');meta.append(el('strong','stream-title','Pick something to play'),el('small','stream-author','YouTube · YouTube Music'));
  const previous=button('stream-control','Previous','‹');previous.id='stream-previous';const play=button('stream-control stream-play','Play','▶');play.id='stream-play';const next=button('stream-control','Next','›');next.id='stream-next';const controls=el('div','stream-controls');controls.append(previous,play,next);
  const timeline=el('div','stream-timeline'),current=el('small','stream-current','0:00'),seek=el('input','stream-seek'),duration=el('small','stream-duration','0:00');seek.id='stream-seek';seek.type='range';seek.min='0';seek.max='1000';seek.value='0';seek.step='1';seek.setAttribute('aria-label','Track position');timeline.append(current,seek,duration);
  const volumeWrap=el('label','stream-volume');volumeWrap.title='Volume';volumeWrap.append(el('span','','⌁'));const volume=el('input');volume.id='stream-volume';volume.type='range';volume.min='0';volume.max='100';volume.step='1';volume.setAttribute('aria-label','Volume');volumeWrap.append(volume);
  const save=button('stream-save','Save current music','☆');save.id='stream-save';const queueToggle=button('stream-queue-toggle','Open playlist picker','≡');queueToggle.id='stream-queue-toggle';const videoToggle=button('stream-video-toggle','Show video','▣');videoToggle.id='stream-video-toggle';dock.append(source,meta,controls,timeline,volumeWrap,save,queueToggle,videoToggle);

  const chooser=el('section','stream-chooser');chooser.id='stream-chooser';chooser.hidden=true;const form=el('form','stream-add-form'),input=el('input');input.id='stream-url';input.type='text';input.inputMode='url';input.autocomplete='off';input.placeholder='Paste a YouTube or YouTube Music song / playlist link';input.setAttribute('aria-label','YouTube or YouTube Music link');const cancel=button('','Close music picker','Cancel'),load=button('primary','Load music','Load');load.type='submit';form.append(input,cancel,load);const library=el('div','stream-library');chooser.append(form,library);
  const queue=el('section','stream-queue');queue.id='stream-queue';queue.hidden=true;const queueHead=el('header');queueHead.append(el('span','','Playlist'));const shuffle=button('stream-mode','Shuffle playlist','Shuffle');shuffle.id='stream-shuffle';const loop=button('stream-mode','Loop playlist','Loop');loop.id='stream-loop';queueHead.append(shuffle,loop);const queueGrid=el('div','stream-queue-grid');queue.append(queueHead,queueGrid);
  shell.append(video,dock,chooser,queue);sound.append(shell);

  let player=null,ready=false,currentMedia=null,progressTimer=0,lastPersist=0;const saved=readSaved();saved.library=cleanLibrary(saved.library);const savedVolume=Number(saved.volume);volume.value=String(Math.round((Number.isFinite(savedVolume)?Math.max(0,Math.min(1,savedVolume)):.35)*100));const title=shell.querySelector('.stream-title'),author=shell.querySelector('.stream-author');
  const setArtwork=(videoId,label='')=>{const art=id('music-room-cover');if(!art)return;if(/^[A-Za-z0-9_-]{11}$/.test(String(videoId||''))){art.src=`https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;art.alt=label?`${label} artwork`:'';shell.dataset.artwork='track'}else{art.removeAttribute('src');art.alt='';shell.dataset.artwork='empty'}};
  const persist=()=>{const position=ready&&player?.getCurrentTime?Number(player.getCurrentTime())||0:Number(saved.time)||0,index=ready&&player?.getPlaylistIndex?Number(player.getPlaylistIndex())||0:Number(saved.index)||0;const data={...saved,url:currentMedia?.url||saved.url||'',volume:Number(volume.value)/100,time:position,index,title:title.textContent||'',author:author.textContent||'',shuffle:Boolean(saved.shuffle),loop:Boolean(saved.loop),library:cleanLibrary(saved.library)};saveSaved(data);Object.assign(saved,data)};
  const setVideo=open=>{video.hidden=!open;shell.dataset.video=open?'open':'closed';videoToggle.setAttribute('aria-pressed',String(open))};const setPlaying=playing=>{shell.dataset.playing=String(playing);play.textContent=playing?'Ⅱ':'▶';play.setAttribute('aria-label',playing?'Pause':'Play')};
  const ensureMount=()=>{let node=id('stream-youtube');if(!node){node=el('div','stream-video-mount');node.id='stream-youtube';video.prepend(node)}mount=node;return node};
  const libraryHas=url=>saved.library.some(item=>item.url===url);const refreshSave=()=>{save.textContent=currentMedia&&libraryHas(currentMedia.url)?'★':'☆';save.setAttribute('aria-pressed',String(Boolean(currentMedia&&libraryHas(currentMedia.url))))};
  const renderLibrary=()=>{library.replaceChildren();const head=el('header');head.append(el('strong','','My music'),el('small','',saved.library.length?'Saved on this device':'Save a song or playlist once and it stays here'));library.append(head);if(!saved.library.length)return;const list=el('div','stream-library-list');for(const item of saved.library){const row=el('div','stream-library-row'),pick=button('stream-library-pick',`Play ${item.title}`),copy=el('span');copy.append(el('strong','',item.title),el('small','',item.type==='playlist'?`Playlist · ${item.author}`:item.author));pick.append(copy);pick.addEventListener('click',()=>{chooser.hidden=true;void createPlayer(mediaFrom(item.url),{autoplay:true})});const remove=button('stream-library-remove',`Remove ${item.title}`,'×');remove.addEventListener('click',event=>{event.stopPropagation();saved.library=saved.library.filter(entry=>entry.url!==item.url);persist();renderLibrary();refreshSave()});row.append(pick,remove);list.append(row)}library.append(list)};
  const renderQueue=()=>{queueGrid.replaceChildren();if(!ready||!player?.getPlaylist){queueGrid.append(el('p','','Load a playlist to pick tracks here.'));return}const items=player.getPlaylist?.()||[],active=Math.max(0,Number(player.getPlaylistIndex?.())||0);if(items.length<2){queueGrid.append(el('p','','This is a single track.'));return}items.slice(0,60).forEach((videoId,index)=>{const item=button(`stream-track${index===active?' active':''}`,`Play playlist track ${index+1}`);item.dataset.index=String(index);item.append(el('b','',String(index+1)),el('span','',index===active?(title.textContent||`Track ${index+1}`):`Track ${index+1}`));item.addEventListener('click',()=>{player.playVideoAt?.(index);setVideo(true)});queueGrid.append(item)})};
  const updateMeta=()=>{if(!ready||!player)return;const data=player.getVideoData?.()||{};if(data.title)title.textContent=data.title;if(data.author)author.textContent=data.author;if(data.video_id)setArtwork(data.video_id,data.title||'');shell.dataset.state=data.video_id?'ready':shell.dataset.state;refreshSave();renderQueue();persist()};
  const updateProgress=()=>{if(!ready||!player)return;const now=Number(player.getCurrentTime?.())||0,total=Number(player.getDuration?.())||0;current.textContent=timeText(now);duration.textContent=timeText(total);seek.value=String(total?Math.round(now/total*1000):0);if(Date.now()-lastPersist>4000){lastPersist=Date.now();persist()}};const startProgress=()=>{clearInterval(progressTimer);progressTimer=setInterval(updateProgress,500);updateProgress()};const destroyPlayer=()=>{clearInterval(progressTimer);progressTimer=0;try{player?.destroy?.()}catch{}player=null;ready=false;ensureMount()};

  const createPlayer=async(media,{resume=false,autoplay=false}={})=>{if(!media)return;currentMedia=media;saved.url=media.url;shell.dataset.state='loading';title.textContent='Loading…';author.textContent=media.listId?'YouTube playlist':'YouTube';setArtwork(media.videoId,'');setVideo(true);destroyPlayer();persist();
    try{const YT=await loadYouTube(),playerVars={playsinline:1,controls:1,rel:0,enablejsapi:1,origin:location.origin};if(media.listId){playerVars.listType='playlist';playerVars.list=media.listId}const target=ensureMount().id;player=new YT.Player(target,{width:356,height:200,videoId:media.videoId||undefined,playerVars,events:{onReady:event=>{ready=true;event.target.setVolume?.(Number(volume.value));event.target.setLoop?.(Boolean(saved.loop));event.target.setShuffle?.(Boolean(saved.shuffle));const index=resume?Number(saved.index)||0:0,at=resume?Number(saved.time)||0:0;if(index>0&&media.listId)event.target.playVideoAt?.(index);if(at>1)event.target.seekTo?.(at,true);shell.dataset.state='ready';updateMeta();startProgress();if(autoplay)event.target.playVideo?.()},onStateChange:event=>{const state=Number(event.data);setPlaying(state===1);if(state===1)setVideo(true);updateMeta();updateProgress();if(state===0){saved.time=0;persist()}},onAutoplayBlocked:()=>ctx.toast?.('Press play to start audio'),onError:()=>{shell.dataset.state='error';title.textContent='This item cannot play here';author.textContent='Try another YouTube link';setPlaying(false)}}});}catch(error){shell.dataset.state='error';title.textContent='Player unavailable';author.textContent='Check the connection and try again';ctx.toast?.(error.message)}};

  source.addEventListener('click',()=>{chooser.hidden=!chooser.hidden;queue.hidden=true;renderLibrary();if(!chooser.hidden){input.value=currentMedia?.url||saved.url||'';requestAnimationFrame(()=>input.focus())}});cancel.addEventListener('click',()=>{chooser.hidden=true;source.focus()});form.addEventListener('submit',event=>{event.preventDefault();const media=mediaFrom(input.value);if(!media){ctx.toast?.('Paste a valid HTTPS YouTube or YouTube Music link');return}input.value=media.url;chooser.hidden=true;saved.time=0;saved.index=0;void createPlayer(media,{autoplay:true})});
  play.addEventListener('click',async()=>{if(!player){const media=mediaFrom(saved.url);if(!media){chooser.hidden=false;renderLibrary();requestAnimationFrame(()=>input.focus());return}await createPlayer(media,{resume:true,autoplay:true});return}if(!ready)return;const state=Number(player.getPlayerState?.());if(state===1)player.pauseVideo?.();else{setVideo(true);player.playVideo?.()}});previous.addEventListener('click',()=>{if(ready){setVideo(true);player.previousVideo?.()}});next.addEventListener('click',()=>{if(ready){setVideo(true);player.nextVideo?.()}});seek.addEventListener('change',()=>{if(!ready)return;const total=Number(player.getDuration?.())||0;if(total)player.seekTo?.(total*Number(seek.value)/1000,true)});volume.addEventListener('input',()=>{if(ready)player.setVolume?.(Number(volume.value));persist()});
  save.addEventListener('click',()=>{if(!currentMedia){chooser.hidden=false;renderLibrary();return}if(libraryHas(currentMedia.url))saved.library=saved.library.filter(item=>item.url!==currentMedia.url);else saved.library=[{url:currentMedia.url,title:title.textContent||'Saved music',author:author.textContent||'YouTube',type:currentMedia.listId?'playlist':'track',addedAt:Date.now()},...saved.library].slice(0,24);persist();refreshSave();renderLibrary();ctx.toast?.(libraryHas(currentMedia.url)?'Saved to My music':'Removed from My music')});
  queueToggle.addEventListener('click',()=>{queue.hidden=!queue.hidden;chooser.hidden=true;renderQueue()});shuffle.addEventListener('click',()=>{saved.shuffle=!saved.shuffle;shuffle.setAttribute('aria-pressed',String(saved.shuffle));if(ready)player.setShuffle?.(Boolean(saved.shuffle));persist();renderQueue()});loop.addEventListener('click',()=>{saved.loop=!saved.loop;loop.setAttribute('aria-pressed',String(saved.loop));if(ready)player.setLoop?.(Boolean(saved.loop));persist()});shuffle.setAttribute('aria-pressed',String(Boolean(saved.shuffle)));loop.setAttribute('aria-pressed',String(Boolean(saved.loop)));
  videoToggle.addEventListener('click',()=>{if(!video.hidden){if(Number(player?.getPlayerState?.())===1)player.pauseVideo?.();setVideo(false)}else if(player)setVideo(true)});videoClose.addEventListener('click',()=>{if(Number(player?.getPlayerState?.())===1)player.pauseVideo?.();setVideo(false)});window.addEventListener('beforeunload',persist);
  if(saved.url&&mediaFrom(saved.url)){currentMedia=mediaFrom(saved.url);shell.dataset.state='saved';title.textContent=saved.title||'Ready to resume';author.textContent=saved.author||'YouTube · YouTube Music';setArtwork(currentMedia.videoId,saved.title||'')}renderLibrary();refreshSave();ctx.streamPlayer={parse:mediaFrom,load:createPlayer,library:()=>cleanLibrary(saved.library)};
}
