'use strict';
const fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const{chromium}=require('playwright');
const site=path.resolve(process.argv[2]||'_site'),out=process.argv[3]?path.resolve(process.argv[3]):null,assert=(value,message)=>{if(!value)throw new Error(message)};
if(out)fs.mkdirSync(out,{recursive:true});

function serve(){return new Promise(resolve=>{const server=http.createServer((request,response)=>{let pathname='/';try{pathname=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname)}catch{}let file=path.join(site,pathname.replace(/^\/+/,''));if(pathname.endsWith('/'))file=path.join(file,'index.html');if(!file.startsWith(site)){response.writeHead(403);response.end();return}fs.readFile(file,(error,data)=>{if(error){response.writeHead(404);response.end('Not found');return}const type={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2','.webmanifest':'application/manifest+json'}[path.extname(file)]||'application/octet-stream';response.writeHead(200,{'content-type':type,'cache-control':'no-store'});response.end(data)})});server.listen(0,'127.0.0.1',()=>resolve({server,origin:`http://127.0.0.1:${server.address().port}`}))})}

const seed=()=>{
  const now=Date.now();
  localStorage.setItem('pacefoldPrefsV15',JSON.stringify({profile:'original',rhythmDiscretion:'neutral',timeZone:'America/Toronto',method:'15',asr:'hanafi',showSeconds:true,timeFormat:'12',workHours:'08:30-16:30',workDays:[1,2,3,4,5],notifications:false,quietMode:false,weatherEnabled:false,waterTarget:24,waterStep:2,waterOz:0,waterLastAt:now,waterCadence:45,gazeLastCompleted:now,eyeCadence:20,bodyLastCompleted:now,bodyCadence:45,noteCategories:['Note','Follow-up'],oneNoteTenant:'https://evil.example/'}));
  localStorage.setItem('pacefold.notebook.entries.v2','[]');
  window.__ytCalls=[];
  window.YT={Player:class{constructor(node,options){this.options=options;this.state=5;this.time=0;this.duration=240;this.index=0;this.playlist=options.playerVars?.list?['dQw4w9WgXcQ','M7lc1UVf-VE']:[options.videoId||'dQw4w9WgXcQ'];this.data={video_id:this.playlist[0],title:'Secure mock track',author:'Mock artist'};setTimeout(()=>options.events.onReady?.({target:this}),0)}setVolume(){}getVideoData(){return this.data}getCurrentTime(){return this.time}getDuration(){return this.duration}getPlayerState(){return this.state}getPlaylist(){return this.playlist}getPlaylistIndex(){return this.index}playVideo(){this.state=1;this.options.events.onStateChange?.({data:1})}pauseVideo(){this.state=2;this.options.events.onStateChange?.({data:2})}seekTo(v){this.time=v}previousVideo(){}nextVideo(){}playVideoAt(i){this.index=i;this.data={video_id:this.playlist[i],title:`Secure track ${i+1}`,author:'Mock artist'};this.options.events.onStateChange?.({data:1})}setShuffle(){}setLoop(){}destroy(){}}};
};

async function main(){
  const app=fs.readFileSync(path.join(site,'app','index.html'),'utf8'),auth=fs.readFileSync(path.join(site,'app','auth.html'),'utf8'),worker=fs.readFileSync(path.join(site,'service-worker.js'),'utf8'),experience=fs.readFileSync(path.join(site,'pacefold-experience.txt'),'utf8').trim();
  assert(experience==='27.1.0 wow-security-r4-notification-r5','WOW/security build identity missing');
  assert(app.includes("default-src 'none'")&&app.includes("media-src 'self' blob:")&&!app.includes("media-src 'self' data: blob: https:"),'App CSP is not default-deny / media restricted');
  assert(app.includes("img-src 'self' data: blob: https://i.ytimg.com")&&app.includes('<meta name="referrer" content="strict-origin-when-cross-origin">'),'Artwork or referrer policy missing');
  assert(auth.includes("default-src 'none'; script-src 'self'")&&auth.includes("form-action 'none'")&&!auth.includes('Pacefold'),'Auth bridge is not hardened and neutral');
  assert(worker.includes('wow-security-r4')&&worker.includes('SHELL_SET')&&worker.includes('AUTH_PATHS')&&worker.includes("frame-ancestors 'none'")&&worker.includes("const DB_NAME='pacefold-v26'"),'Worker cache/security contract is incomplete');

  const{server,origin}=await serve();let browser;try{
    browser=await chromium.launch({headless:true});
    const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'America/Toronto'}),page=await context.newPage(),errors=[];
    page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'&&!/Failed to load resource/i.test(message.text()))errors.push(message.text())});
    await page.route('https://i.ytimg.com/**',route=>route.fulfill({status:200,contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="120" height="90"><rect width="120" height="90" fill="#ccd8d2"/></svg>'}));
    await page.addInitScript(seed);await page.goto(`${origin}/app/`,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__PACEFOLD__?.version==='27.1.0');
    const initial=await page.evaluate(()=>({security:window.__PACEFOLD__.security,setup:document.getElementById('setup-dialog').open,dayline:document.getElementById('cover-dayline')?.getAttribute('aria-label')||'',ambient:Boolean(document.getElementById('cover-ambient')),brand:document.querySelector('.brand strong')?.textContent||'',visibleName:document.body.innerText.includes('Pacefold')}));
    assert(!initial.setup,'Setup blocked hardened launch');assert(initial.security?.backupLimit===5242880,'Backup ceiling is not exposed');assert(initial.security?.referrer==='strict-origin-when-cross-origin','Runtime referrer policy is wrong');assert(initial.security?.csp.includes("default-src 'none'"),'Runtime CSP is not default deny');assert(initial.security?.tenant==='organizations','Unsafe OneNote tenant did not normalize');assert(initial.dayline.length>0&&initial.ambient,'Ambient live day horizon did not boot');assert(initial.brand==='Clock'&&!initial.visibleName,'Discreet Clock identity regressed');

    const external=await page.evaluate(()=>{const a=document.createElement('a');a.href='https://example.com/';a.target='_blank';a.addEventListener('click',event=>event.preventDefault());document.body.append(a);a.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}));const result={rel:a.rel,referrer:a.referrerPolicy};a.remove();return result});
    assert(external.rel.includes('noopener')&&external.rel.includes('noreferrer')&&external.referrer==='no-referrer','External-link isolation did not apply');

    await page.click('#cover-enter');await page.waitForFunction(()=>document.documentElement.dataset.cover==='peeled');
    await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.waitForTimeout(140);assert(await page.evaluate(()=>document.documentElement.dataset.privacyScreen)==='on','Privacy curtain did not engage on blur');assert(await page.locator('.privacy-curtain').evaluate(node=>getComputedStyle(node).display)==='grid','Privacy curtain is not visible');
    await page.evaluate(()=>window.dispatchEvent(new Event('focus')));await page.waitForTimeout(30);assert(await page.evaluate(()=>document.documentElement.dataset.privacyScreen)==='off','Privacy curtain did not release on focus');

    const largeBackup=await page.evaluate(()=>{const input=document.getElementById('restore-file-input'),file=new File([new Uint8Array(5*1024*1024+1)],'oversize.json',{type:'application/json'}),dt=new DataTransfer();dt.items.add(file);input.files=dt.files;input.dispatchEvent(new Event('change',{bubbles:true}));return file.size});assert(largeBackup>5*1024*1024,'Oversize backup fixture is invalid');await page.waitForTimeout(50);assert((await page.locator('#toast').textContent()).includes('too large'),'Oversize backup was not blocked before parsing');

    await page.click('#cover-return');await page.waitForFunction(()=>document.documentElement.dataset.cover==='on');await page.click('#cover-music-open');await page.waitForFunction(()=>document.getElementById('sound-bar').dataset.musicOpen==='true');await page.fill('#stream-url','https://music.youtube.com/watch?v=dQw4w9WgXcQ&utm_source=secret&si=tracking');await page.click('#stream-chooser button.primary');await page.waitForFunction(()=>document.getElementById('stream-player').dataset.state==='ready');
    const media=await page.evaluate(()=>{const video=document.getElementById('stream-video').getBoundingClientRect(),stage=document.getElementById('music-room-stage'),stageBox=stage.getBoundingClientRect();return{stored:JSON.parse(localStorage.getItem('pacefold.stream.v1')||'{}').url,artwork:document.getElementById('music-room-cover')?.src||'',artState:document.getElementById('stream-player')?.dataset.artwork||'',video:{w:video.width,h:video.height,x:video.x,y:video.y},stage:{display:getComputedStyle(stage).display,w:stageBox.width,h:stageBox.height}}});
    assert(media.stored==='https://www.youtube.com/watch?v=dQw4w9WgXcQ','Media URL retained tracking or noncanonical parameters');assert(media.artwork.includes('https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg')&&media.artState==='track','Live track artwork did not bind');assert(media.stage.display==='grid'&&media.stage.w>600&&media.stage.h>300,'Artwork stage disappeared when playback loaded');assert(media.video.w>=350&&media.video.w<=360&&media.video.h>=199&&media.video.h<=202,'YouTube source preview is not compact 356×200');
    if(out){await page.evaluate(()=>document.getElementById('toast').classList.remove('on'));await page.waitForTimeout(120);await page.screenshot({path:path.join(out,'clock-r4-music.png'),fullPage:false});await page.click('#music-room-close');await page.waitForFunction(()=>document.getElementById('sound-bar').dataset.musicOpen==='false');await page.screenshot({path:path.join(out,'clock-r4-surface.png'),fullPage:false});await page.click('#cover-enter');await page.waitForFunction(()=>document.documentElement.dataset.cover==='peeled');await page.waitForTimeout(760);await page.screenshot({path:path.join(out,'clock-r4-home.png'),fullPage:false})}
    assert(!errors.length,errors.join('\n'));await context.close();
    console.log('Clock WOW/security contract passed: default-deny shell, privacy curtain, backup guard, tenant normalization, isolated links, canonical media, live artwork and compact YouTube preview.');
  }finally{if(browser)await browser.close();server.close()}
}
main().catch(error=>{console.error(error.stack||error);process.exitCode=1});
