'use strict';
const fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const{chromium}=require('playwright');
const site=path.resolve(process.argv[2]||'_site'),assert=(value,message)=>{if(!value)throw new Error(message)};
function serve(){return new Promise(resolve=>{const server=http.createServer((request,response)=>{let pathname='/';try{pathname=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname)}catch{}let file=path.join(site,pathname.replace(/^\/+/,''));if(pathname.endsWith('/'))file=path.join(file,'index.html');if(!file.startsWith(site)){response.writeHead(403);response.end();return}fs.readFile(file,(error,data)=>{if(error){response.writeHead(404);response.end('Not found');return}const type={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2'}[path.extname(file)]||'application/octet-stream';response.writeHead(200,{'content-type':type,'cache-control':'no-store'});response.end(data)})});server.listen(0,'127.0.0.1',()=>resolve({server,origin:`http://127.0.0.1:${server.address().port}`}))})}
async function main(){
  const worker=fs.readFileSync(path.join(site,'service-worker.js'),'utf8'),daily=JSON.parse(fs.readFileSync(path.join(site,'app','daily-image.json'),'utf8'));assert(worker.includes('polish-r3-daily-surface'),'Daily-surface service-worker revision missing');assert(worker.includes("indexedDB.open('pacefold-v26'"),'Durable cue database changed');
  const{server,origin}=await serve();let browser;try{
    browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'America/Toronto'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
    await context.route('https://www.google.com/search?**',route=>route.fulfill({status:200,contentType:'text/html',body:'<title>Google search test</title>'}));
    await page.addInitScript(()=>{const now=Date.now();localStorage.setItem('pacefoldOnboardedV15','1');localStorage.setItem('pacefoldPrefsV15',JSON.stringify({profile:'original',rhythmDiscretion:'neutral',timeZone:'America/Toronto',method:'15',asr:'hanafi',showSeconds:true,timeFormat:'12',workHours:'00:00-23:59',workDays:[0,1,2,3,4,5,6],notifications:false,quietMode:false,weatherEnabled:false,waterTarget:24,waterStep:2,waterOz:0,waterLastAt:now-20*60000,waterCadence:1,gazeLastCompleted:now,eyeCadence:30,bodyLastCompleted:now,bodyCadence:45,noteCategories:['Note','Follow-up']}));localStorage.setItem('pacefold.notebook.entries.v2','[]');localStorage.setItem('pacefold.cues.v1',JSON.stringify({ack:{},notified:{},snoozeUntil:0}))});
    await page.goto(`${origin}/app/`,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__PACEFOLD__?.version==='27.0.0');
    const surface=await page.evaluate(()=>({cover:document.documentElement.dataset.cover,main:document.getElementById('cover-time-main')?.textContent,seconds:document.getElementById('cover-time-second')?.textContent,placeholder:document.getElementById('cover-search')?.placeholder,tabs:document.querySelectorAll('.cover-modes').length,note:document.getElementById('cover-note-toggle')?.textContent,music:document.getElementById('music-launch')?.href,photo:document.getElementById('pace-cover')?.dataset.photo||'',stageInert:document.getElementById('stage')?.inert===true}));
    assert(surface.cover==='on'&&surface.main&&/^\d{2}$/.test(surface.seconds),'Polished cover clock did not boot');assert(surface.placeholder==='Search Google or type a web address','Google omnibox copy is wrong');assert(surface.tabs===0&&/Note/.test(surface.note),'Segmented Search/Note tabs were not removed');assert(surface.music==='https://music.youtube.com/'&&surface.stageInert,'Music handoff or cover interaction guard regressed');if(daily.url)assert(surface.photo==='loaded','Packed daily image metadata did not reach the cover');
    await page.fill('#cover-search','pacefold test');const popupPromise=context.waitForEvent('page');await page.press('#cover-search','Enter');const popup=await popupPromise;await popup.waitForLoadState('domcontentloaded');assert(popup.url().startsWith('https://www.google.com/search?q=pacefold%20test'),'Default search is not Google');await popup.close();
    await page.click('#cover-note-toggle');await page.fill('#cover-note','Quick note from polished surface');await page.press('#cover-note','Enter');await page.waitForTimeout(60);assert(await page.evaluate(()=>window.__PACEFOLD__.notes.some(note=>note.body==='Quick note from polished surface')),'Quick note did not reach Daybook');
    await page.click('#cover-peel');await page.waitForFunction(()=>document.documentElement.dataset.cover==='peeled');assert(await page.evaluate(()=>document.getElementById('stage').inert===false),'Peeling did not restore Pacefold');
    const privateTerms=/\b(Fajr|Dhuhr|Asr|Maghrib|Isha|Hanafi|prayer)\b|Etobicoke|Toronto|America\/Toronto|15°/i;const home=await page.evaluate(()=>({text:document.querySelector('[data-view="home"]').innerText,title:document.title,brand:document.querySelector('.brand strong')?.textContent,bubbles:document.querySelectorAll('.window-cue-bubble').length}));assert(!privateTerms.test(home.text),'Neutral Clock leaked private rhythm vocabulary');assert(home.title==='Clock'&&home.brand==='Clock','Discreet Clock chrome regressed');assert(home.bubbles>0,'Window-native cue beads are missing');assert(!errors.length,errors.join('\n'));await context.close();console.log('Pacefold 27 polished daily-surface release contract passed.');
  }finally{if(browser)await browser.close();server.close()}}
main().catch(error=>{console.error(error.stack||error);process.exitCode=1});
