'use strict';
const fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const{chromium}=require('playwright');
const site=path.resolve(process.argv[2]||'_site'),assert=(value,message)=>{if(!value)throw new Error(message)};
function serve(){return new Promise(resolve=>{const server=http.createServer((request,response)=>{let pathname='/';try{pathname=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname)}catch{}let file=path.join(site,pathname.replace(/^\/+/,''));if(pathname.endsWith('/'))file=path.join(file,'index.html');if(!file.startsWith(site)){response.writeHead(403);response.end();return}fs.readFile(file,(error,data)=>{if(error){response.writeHead(404);response.end('Not found');return}const type={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2'}[path.extname(file)]||'application/octet-stream';response.writeHead(200,{'content-type':type,'cache-control':'no-store'});response.end(data)})});server.listen(0,'127.0.0.1',()=>resolve({server,origin:`http://127.0.0.1:${server.address().port}`}))})}
async function main(){
  const worker=fs.readFileSync(path.join(site,'service-worker.js'),'utf8');assert(worker.includes("VERSION='27.1.0'")&&worker.includes('final-form-r1'),'Final-form service-worker revision missing');assert(worker.includes("indexedDB.open('pacefold-v26'"),'Durable cue database changed');
  const{server,origin}=await serve();let browser;try{
    browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'America/Toronto'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
    await context.route('https://www.google.com/search?**',route=>route.fulfill({status:200,contentType:'text/html',body:'<title>Google search test</title>'}));
    await page.addInitScript(()=>{
      const now=Date.now();localStorage.setItem('pacefoldOnboardedV15','1');localStorage.setItem('pacefoldPrefsV15',JSON.stringify({profile:'original',rhythmDiscretion:'neutral',timeZone:'America/Toronto',method:'15',asr:'hanafi',showSeconds:true,timeFormat:'12',workHours:'00:00-23:59',workDays:[0,1,2,3,4,5,6],notifications:false,quietMode:false,weatherEnabled:false,waterTarget:24,waterStep:2,waterOz:0,waterLastAt:now-20*60000,waterCadence:15,gazeLastCompleted:now,eyeCadence:30,bodyLastCompleted:now,bodyCadence:45,noteCategories:['Note','Follow-up']}));localStorage.setItem('pacefold.notebook.entries.v2','[]');localStorage.setItem('pacefold.cues.v1',JSON.stringify({ack:{},notified:{},snoozeUntil:0}));
      window.__ytCalls=[];window.YT={Player:class{constructor(node,options){this.options=options;this.state=5;this.time=0;this.duration=240;this.index=0;this.playlist=options.playerVars?.list?['dQw4w9WgXcQ','M7lc1UVf-VE','aqz-KE-bpKQ']:[options.videoId||'dQw4w9WgXcQ'];this.data={video_id:this.playlist[0],title:'Mock track',author:'Mock artist'};setTimeout(()=>options.events.onReady?.({target:this}),0)}setVolume(v){window.__ytCalls.push(`volume:${v}`)}getVideoData(){return this.data}getCurrentTime(){return this.time}getDuration(){return this.duration}getPlayerState(){return this.state}getPlaylist(){return this.playlist}getPlaylistIndex(){return this.index}playVideo(){this.state=1;window.__ytCalls.push('play');this.options.events.onStateChange?.({data:1})}pauseVideo(){this.state=2;window.__ytCalls.push('pause');this.options.events.onStateChange?.({data:2})}seekTo(v){this.time=v;window.__ytCalls.push(`seek:${Math.round(v)}`)}previousVideo(){this.index=Math.max(0,this.index-1);window.__ytCalls.push('previous');this.options.events.onStateChange?.({data:1})}nextVideo(){this.index=Math.min(this.playlist.length-1,this.index+1);window.__ytCalls.push('next');this.options.events.onStateChange?.({data:1})}playVideoAt(i){this.index=i;this.data={video_id:this.playlist[i],title:`Mock track ${i+1}`,author:'Mock artist'};window.__ytCalls.push(`playAt:${i}`);this.options.events.onStateChange?.({data:1})}setShuffle(v){window.__ytCalls.push(`shuffle:${v}`)}setLoop(v){window.__ytCalls.push(`loop:${v}`)}destroy(){window.__ytCalls.push('destroy')}}};
    });
    await page.goto(`${origin}/app/`,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__PACEFOLD__?.version==='27.1.0');
    const surface=await page.evaluate(()=>({cover:document.documentElement.dataset.cover,seconds:document.getElementById('cover-time-second')?.textContent,clockPx:parseFloat(getComputedStyle(document.getElementById('cover-time-main')).fontSize),stageInert:document.getElementById('stage')?.inert===true,htmlOverflow:getComputedStyle(document.documentElement).overflow,bodyOverflow:getComputedStyle(document.body).overflow,playerWidth:document.getElementById('stream-player')?.getBoundingClientRect().width||0,controlsDisplay:getComputedStyle(document.querySelector('.stream-controls')).display,focusChoices:document.querySelectorAll('.stream-focus-choice').length,customRows:document.querySelectorAll('#custom-moment-rows [data-custom-row]').length,enter:document.getElementById('cover-enter')?.innerText||'',musicEntry:Boolean(document.getElementById('cover-music-open'))}));
    assert(surface.cover==='on'&&/^\d{2}$/.test(surface.seconds),'Final cover clock did not boot');assert(surface.clockPx>=180,`Hero clock is not giant enough (${surface.clockPx}px)`);assert(surface.stageInert&&surface.htmlOverflow==='hidden'&&surface.bodyOverflow==='hidden','Simple surface is not fully scroll-locked');assert(surface.playerWidth<=310&&surface.controlsDisplay==='none','Closed player is still visually heavy');assert(/Open Pacefold/i.test(surface.enter),'Start surface lost the explicit Pacefold entrance');assert(surface.musicEntry,'Start surface lost the full Music entry');assert(surface.focusChoices===4,'Local focus sounds are not integrated into Music');assert(surface.customRows===8,'Eight custom-moment slots were not preserved');
    await page.fill('#cover-search','pacefold test');const popupPromise=context.waitForEvent('page');await page.press('#cover-search','Enter');const popup=await popupPromise;await popup.waitForLoadState('domcontentloaded');assert(popup.url().startsWith('https://www.google.com/search?q=pacefold%20test'),'Default search is not Google');await popup.close();
    await page.click('#cover-music-open');await page.waitForFunction(()=>document.getElementById('sound-bar')?.dataset.musicOpen==='true');assert(await page.locator('#stream-chooser').isVisible(),'Full Music room did not open its library/picker');await page.fill('#stream-url','https://music.youtube.com/playlist?list=PLmock123456');await page.click('#stream-chooser button.primary');await page.waitForFunction(()=>document.getElementById('stream-player')?.dataset.state==='ready');await page.click('#stream-queue-toggle');assert(await page.locator('.stream-track').count()===3,'Playlist did not expose track picker');await page.locator('.stream-track').nth(1).click();await page.click('#stream-shuffle');await page.click('#stream-loop');await page.click('#stream-save');
    const backup=await page.evaluate(()=>window.__PACEFOLD__.backup());assert(backup.release==='27.1.0'&&backup.revision==='final-form-r1','Backup release identity is stale');assert(backup.player?.stream?.library?.length===1,'My Music was not included in backup');
    const transport=await page.evaluate(()=>{const p=document.getElementById('stream-play').getBoundingClientRect(),dock=document.querySelector('.stream-dock').getBoundingClientRect(),shell=document.getElementById('stream-player').getBoundingClientRect();return{play:{x:p.x,y:p.y,w:p.width,h:p.height,right:p.right,bottom:p.bottom},dock:{x:dock.x,y:dock.y,w:dock.width,h:dock.height,right:dock.right,bottom:dock.bottom},shell:{x:shell.x,y:shell.y,w:shell.width,h:shell.height,right:shell.right,bottom:shell.bottom},vw:innerWidth,vh:innerHeight}});assert(transport.play.x>=0&&transport.play.y>=0&&transport.play.right<=transport.vw+1&&transport.play.bottom<=transport.vh+1,`Music transport escaped viewport: ${JSON.stringify(transport)}`);
    await page.click('#stream-play');await page.evaluate(()=>{const seek=document.getElementById('stream-seek');seek.value='500';seek.dispatchEvent(new Event('change',{bubbles:true}));const volume=document.getElementById('stream-volume');volume.value='50';volume.dispatchEvent(new Event('input',{bubbles:true}))});await page.click('#stream-next');await page.click('#stream-previous');const calls=await page.evaluate(()=>window.__ytCalls);for(const expected of['playAt:1','shuffle:true','loop:true','seek:120','volume:50','next','previous'])assert(calls.includes(expected),`Player missed ${expected}`);
    await page.click('#music-room-close');await page.waitForFunction(()=>document.getElementById('sound-bar')?.dataset.musicOpen==='false');await page.click('#cover-enter');await page.waitForFunction(()=>document.documentElement.dataset.cover==='peeled');const privateTerms=/\b(Fajr|Dhuhr|Asr|Maghrib|Isha|Hanafi|prayer)\b|Etobicoke|Toronto|America\/Toronto|15°/i;const home=await page.evaluate(()=>({text:document.querySelector('[data-view="home"]').innerText,title:document.title,brand:document.querySelector('.brand strong')?.textContent,prep:document.querySelector('[data-action="prep"] strong')?.textContent}));assert(!privateTerms.test(home.text),'Neutral Clock leaked private rhythm vocabulary');assert(home.title==='Clock'&&home.brand==='Clock','Discreet Clock chrome regressed');assert(home.prep==='Noodles','Original profile lost the noodle timer identity');
    await page.evaluate(()=>window.__PACEFOLD__.selfCheck());await page.waitForTimeout(40);assert((await page.locator('#diagnostic-output').textContent()).includes('My Music backup'),'Expanded final self-check did not run');assert(!errors.length,errors.join('\n'));await context.close();console.log('Pacefold 27.1 full-player release contract passed.');
  }finally{if(browser)await browser.close();server.close()}}
main().catch(error=>{console.error(error.stack||error);process.exitCode=1});
