'use strict';
const fs=require('node:fs'),http=require('node:http'),path=require('node:path');
const{chromium}=require('playwright');
const site=path.resolve(process.argv[2]||'_site'),assert=(value,message)=>{if(!value)throw new Error(message)};
function serve(){return new Promise(resolve=>{const server=http.createServer((request,response)=>{let pathname='/';try{pathname=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname)}catch{}let file=path.join(site,pathname.replace(/^\/+/,''));if(pathname.endsWith('/'))file=path.join(file,'index.html');if(!file.startsWith(site)){response.writeHead(403);response.end();return}fs.readFile(file,(error,data)=>{if(error){response.writeHead(404);response.end('Not found');return}const type={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.mjs':'text/javascript; charset=utf-8','.json':'application/json','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.woff2':'font/woff2'}[path.extname(file)]||'application/octet-stream';response.writeHead(200,{'content-type':type,'cache-control':'no-store'});response.end(data)})});server.listen(0,'127.0.0.1',()=>resolve({server,origin:`http://127.0.0.1:${server.address().port}`}))})}
async function main(){
  const worker=fs.readFileSync(path.join(site,'service-worker.js'),'utf8'),daily=JSON.parse(fs.readFileSync(path.join(site,'app','daily-image.json'),'utf8'));assert(worker.includes('polish-r5-wow-player'),'Wow-player service-worker revision missing');assert(worker.includes("indexedDB.open('pacefold-v26'"),'Durable cue database changed');
  const{server,origin}=await serve();let browser;try{
    browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'America/Toronto'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
    await context.route('https://www.google.com/search?**',route=>route.fulfill({status:200,contentType:'text/html',body:'<title>Google search test</title>'}));
    await page.addInitScript(()=>{
      const now=Date.now();localStorage.setItem('pacefoldOnboardedV15','1');localStorage.setItem('pacefoldPrefsV15',JSON.stringify({profile:'original',rhythmDiscretion:'neutral',timeZone:'America/Toronto',method:'15',asr:'hanafi',showSeconds:true,timeFormat:'12',workHours:'00:00-23:59',workDays:[0,1,2,3,4,5,6],notifications:false,quietMode:false,weatherEnabled:false,waterTarget:24,waterStep:2,waterOz:0,waterLastAt:now-20*60000,waterCadence:1,gazeLastCompleted:now,eyeCadence:30,bodyLastCompleted:now,bodyCadence:45,noteCategories:['Note','Follow-up']}));localStorage.setItem('pacefold.notebook.entries.v2','[]');localStorage.setItem('pacefold.cues.v1',JSON.stringify({ack:{},notified:{},snoozeUntil:0}));
      window.__ytCalls=[];window.YT={Player:class{constructor(node,options){this.options=options;this.state=5;this.time=0;this.duration=240;this.index=0;this.playlist=options.playerVars?.list?['dQw4w9WgXcQ','M7lc1UVf-VE','aqz-KE-bpKQ']:[options.videoId||'dQw4w9WgXcQ'];this.data={video_id:this.playlist[0],title:'Mock track',author:'Mock artist'};setTimeout(()=>options.events.onReady?.({target:this}),0)}setVolume(v){window.__ytCalls.push(`volume:${v}`)}getVideoData(){return this.data}getCurrentTime(){return this.time}getDuration(){return this.duration}getPlayerState(){return this.state}getPlaylist(){return this.playlist}getPlaylistIndex(){return this.index}playVideo(){this.state=1;window.__ytCalls.push('play');this.options.events.onStateChange?.({data:1})}pauseVideo(){this.state=2;window.__ytCalls.push('pause');this.options.events.onStateChange?.({data:2})}seekTo(v){this.time=v;window.__ytCalls.push(`seek:${Math.round(v)}`)}previousVideo(){this.index=Math.max(0,this.index-1);window.__ytCalls.push('previous');this.options.events.onStateChange?.({data:1})}nextVideo(){this.index=Math.min(this.playlist.length-1,this.index+1);window.__ytCalls.push('next');this.options.events.onStateChange?.({data:1})}playVideoAt(i){this.index=i;this.data={video_id:this.playlist[i],title:`Mock track ${i+1}`,author:'Mock artist'};window.__ytCalls.push(`playAt:${i}`);this.options.events.onStateChange?.({data:1})}setShuffle(v){window.__ytCalls.push(`shuffle:${v}`)}setLoop(v){window.__ytCalls.push(`loop:${v}`)}destroy(){window.__ytCalls.push('destroy')}}};
    });
    await page.goto(`${origin}/app/`,{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__PACEFOLD__?.version==='27.0.0');
    const surface=await page.evaluate(()=>({cover:document.documentElement.dataset.cover,main:document.getElementById('cover-time-main')?.textContent,seconds:document.getElementById('cover-time-second')?.textContent,clockPx:parseFloat(getComputedStyle(document.getElementById('cover-time-main')).fontSize),placeholder:document.getElementById('cover-search')?.placeholder,player:Boolean(document.getElementById('stream-player')),peelText:document.getElementById('cover-peel')?.innerText||'',barBlur:getComputedStyle(document.querySelector('.app-bar')).backdropFilter||getComputedStyle(document.querySelector('.app-bar')).webkitBackdropFilter,photoFilter:getComputedStyle(document.getElementById('pace-cover'),'::before').filter,favicon:document.getElementById('app-favicon')?.href||'',photo:document.getElementById('pace-cover')?.dataset.photo||'',stageInert:document.getElementById('stage')?.inert===true}));
    assert(surface.cover==='on'&&surface.main&&/^\d{2}$/.test(surface.seconds),'Polished cover clock did not boot');assert(surface.clockPx>=180,`Hero clock is not giant enough (${surface.clockPx}px)`);assert(surface.placeholder==='Search Google or type a web address','Google omnibox copy is wrong');assert(surface.player&&surface.stageInert,'Integrated mini player or cover guard is missing');assert(!/Open Pacefold/i.test(surface.peelText),'Reveal handle is still too literal');assert(surface.barBlur==='none'&&surface.photoFilter==='none','Top image/chrome blur returned');assert(surface.favicon.startsWith('data:image/svg+xml'),'Functional live tab clock did not render');if(daily.url)assert(surface.photo==='loaded','Packed daily image metadata did not reach the cover');
    await page.fill('#cover-search','pacefold test');const popupPromise=context.waitForEvent('page');await page.press('#cover-search','Enter');const popup=await popupPromise;await popup.waitForLoadState('domcontentloaded');assert(popup.url().startsWith('https://www.google.com/search?q=pacefold%20test'),'Default search is not Google');await popup.close();
    await page.click('#stream-source');await page.fill('#stream-url','https://music.youtube.com/playlist?list=PLmock123456');await page.click('#stream-chooser button.primary');await page.waitForFunction(()=>document.getElementById('stream-player')?.dataset.state==='ready');
    await page.click('#stream-queue-toggle');assert(await page.locator('.stream-track').count()===3,'Loaded playlist did not expose a track picker');await page.locator('.stream-track').nth(1).click();await page.click('#stream-shuffle');await page.click('#stream-loop');
    await page.click('#stream-save');await page.click('#stream-source');assert(await page.locator('.stream-library-row').count()===1,'Saved playlist did not appear in My music');const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('pacefold.stream.v1')||'{}'));assert(stored.library?.length===1&&stored.library[0].type==='playlist','My music library persistence is incomplete');await page.click('#stream-source');
    await page.click('#stream-play');await page.evaluate(()=>{const seek=document.getElementById('stream-seek');seek.value='500';seek.dispatchEvent(new Event('change',{bubbles:true}));const volume=document.getElementById('stream-volume');volume.value='50';volume.dispatchEvent(new Event('input',{bubbles:true}))});await page.click('#stream-next');await page.click('#stream-previous');
    const calls=await page.evaluate(()=>window.__ytCalls);for(const expected of['playAt:1','shuffle:true','loop:true','seek:120','volume:50','next','previous'])assert(calls.includes(expected),`Mini-player missed ${expected}`);await page.click('.stream-video-close');assert(await page.locator('#stream-video').isHidden(),'Collapsing the visible player did not work');
    await page.click('#cover-peel');await page.waitForFunction(()=>document.documentElement.dataset.cover==='peeled');assert(await page.evaluate(()=>document.getElementById('stage').inert===false),'Peeling did not restore Pacefold');
    const privateTerms=/\b(Fajr|Dhuhr|Asr|Maghrib|Isha|Hanafi|prayer)\b|Etobicoke|Toronto|America\/Toronto|15°/i;const home=await page.evaluate(()=>({text:document.querySelector('[data-view="home"]').innerText,title:document.title,brand:document.querySelector('.brand strong')?.textContent,bubbles:document.querySelectorAll('.window-cue-bubble').length}));assert(!privateTerms.test(home.text),'Neutral Clock leaked private rhythm vocabulary');assert(home.title==='Clock'&&home.brand==='Clock','Discreet Clock chrome regressed');assert(home.bubbles>0,'Window-native cue beads are missing');assert(!errors.length,errors.join('\n'));await context.close();console.log('Pacefold 27 wow-player release contract passed.');
  }finally{if(browser)await browser.close();server.close()}}
main().catch(error=>{console.error(error.stack||error);process.exitCode=1});
