import fs from'node:fs';
import path from'node:path';
import{spawnSync}from'node:child_process';
import{DEFAULT_PREFS,migratePrefs,scheduleState,normalizeNotes,normalizeLog,metricsForDay,dateKey}from'../src/app/core.mjs';

const root=path.resolve(process.argv[2]||'_site'),read=file=>fs.readFileSync(path.join(root,file),'utf8'),exists=file=>fs.existsSync(path.join(root,file)),assert=(value,message)=>{if(!value)throw new Error(message)};
for(const file of['index.html','site.css','privacy.html','manifest.webmanifest','service-worker.js','pacefold-experience.txt','app/index.html','app/pacefold.css','app/pacefold.mjs','app/daily-image.json','app/auth.html','app/auth.js','app/icons/fold-mark.svg','app/icons/icon-192.png','app/icons/icon-512.png','app/fonts/pacefold-ma.woff2'])assert(exists(file),`Missing ${file}`);
assert(!exists('modules')&&!exists('styles')&&!exists('app/core.mjs'),'Readable source modules/styles/core must not ship');
assert(read('pacefold-experience.txt').trim()==='27.0.0 polish-r3-daily-surface','Build identity is wrong');
for(const file of['app/pacefold.mjs','app/auth.js','service-worker.js']){const result=spawnSync(process.execPath,['--check',path.join(root,file)],{encoding:'utf8'});assert(result.status===0,`${file} syntax failed: ${result.stderr}`)}

const app=read('app/index.html'),runtime=read('app/pacefold.mjs'),styles=read('app/pacefold.css'),worker=read('service-worker.js'),manifest=JSON.parse(read('manifest.webmanifest')),daily=JSON.parse(read('app/daily-image.json'));
const source=file=>fs.readFileSync(path.resolve(file),'utf8'),start=source('src/modules/start-cover.js'),windowCues=source('src/modules/window-cues.js'),cueStore=source('src/modules/cue-store.js'),scheduleSource=source('src/modules/schedule.js'),clock=source('src/modules/clock.js'),notes=source('src/modules/notes.js'),daylog=source('src/modules/daylog.js'),now=source('src/modules/now.js'),main=source('src/modules/main.mjs'),state=source('src/modules/state.js');
assert((app.match(/<link[^>]+stylesheet/g)||[]).length===1,'App must load exactly one stylesheet');assert((app.match(/<script/g)||[]).length===2,'App must load only MSAL and one Pacefold runtime');assert(!runtime.includes('./core.mjs')&&!runtime.includes('../modules/'),'Built runtime references source modules');
assert(main.includes('installStartCover(ctx)')&&main.includes('installWindowCues(ctx)')&&main.includes('installRelease(ctx)'),'Runtime modules are not fully wired');
assert(start.includes("const GOOGLE_SEARCH='https://www.google.com/search?q='")&&start.includes("const YOUTUBE_MUSIC='https://music.youtube.com/'"),'Google search or YouTube Music handoff is missing');
assert(start.includes("data.url!=='./daily-image.jpg'")&&start.includes('cover-time-main')&&start.includes("ctx.captureNote?.(noteInput.value,'Note')"),'Daily image, polished clock or quick-note contract is incomplete');
assert(!start.includes('cover-modes')&&!styles.includes('.cover-modes'),'Segmented Search/Note tabs must be removed');
assert(styles.includes('--cover-image:none')&&styles.includes('.cover-time-main')&&styles.includes('.cover-note-toggle')&&styles.includes('.cover-photo-credit'),'Daily-image surface styling is incomplete');
assert(!styles.includes('.brand{align-self:flex-end;height:48px'),'Fake browser-tab brand styling returned');
assert(worker.includes('polish-r3-daily-surface')&&worker.includes('/app/daily-image.json')&&worker.includes("cache:'no-store'"),'Daily image cache policy is incomplete');
assert(worker.includes("indexedDB.open('pacefold-v26'"),'Durable cue database continuity regressed');
assert(windowCues.includes("document.title='Clock'")&&windowCues.includes('windowCueBloomUntil'),'Window cue lifecycle regressed');
assert(cueStore.includes("label:named?item.label:'Scheduled moment'"),'Background cue privacy regressed');assert(scheduleSource.includes("const discreet=ctx.rhythmMode()!=='names'"),'Rhythm discretion regressed');
assert(clock.includes('day-now-line')&&clock.includes('% of workday'),'Clock day marker regressed');assert(notes.includes("placeholder='Log a thought.'")&&notes.includes('note-inline-input'),'Daybook capture/editing regressed');assert(daylog.includes("['At work',metrics.desk")&&daylog.includes('renderYesterdayComparison'),'Day Log regression');assert(now.includes('weather-rain-window'),'Weather context regressed');
assert(manifest.name==='Clock'&&manifest.short_name==='Clock'&&manifest.start_url==='./app/','Manifest is wrong');assert(state.includes("RELEASE='27.0.0'")&&state.includes("cueState:'pacefold.cues.v1'"),'Release/storage identity regressed');
assert(typeof daily.url==='string'&&typeof daily.credit==='string'&&daily.source==='Bing image of the day','Daily image metadata shape is invalid');if(daily.url){assert(daily.url==='./daily-image.jpg'&&exists('app/daily-image.jpg'),'Daily image metadata points to a missing local image');assert(daily.credit.length>0,'Daily image credit is missing')}

const toronto=migratePrefs({...DEFAULT_PREFS,timeZone:'America/Toronto',lat:43.6205,lng:-79.5132,profile:'original',asr:'hanafi',method:'15'}),summer=new Date('2026-08-10T16:00:00Z'),schedule=scheduleState(summer,toronto);assert(schedule.today.length===6&&schedule.today.every((item,index,rows)=>index===0||item.date>rows[index-1].date),'Prayer rhythm invalid');assert(schedule.today.find(item=>item.id==='asr').date>schedule.today.find(item=>item.id==='dhuhr').date,'Hanafi Asr invalid');
const migrated=migratePrefs({profile:'original',waterSips:8,noodleMinutes:45,showSeconds:true});assert(migrated.waterOz===8&&migrated.prepMinutes===45,'Legacy preference migration failed');assert(normalizeNotes([{id:'old',text:'Old note',createdAt:'2026-08-10T12:00:00Z'}])[0].body==='Old note','Legacy note migration failed');const key=dateKey(summer,'America/Toronto'),log=normalizeLog({days:{[key]:{events:[{id:'f',type:'focus',source:'focus',label:'Focus',start:summer.getTime()-3600000,end:summer.getTime()}]}}});assert(metricsForDay(log,key,toronto,summer.getTime()).focus===3600000,'Day-log metrics failed');
console.log(JSON.stringify({release:'27.0.0',surface:'polish-r3-daily-surface',googleSearch:'checked',dailyImage:daily.url?'packed':'fallback',fakeTab:'removed',windowCues:'checked',storageContinuity:'checked',prayerSchedule:'passed'},null,2));
