import fs from'node:fs';
import path from'node:path';
import{spawnSync}from'node:child_process';
import{DEFAULT_PREFS,migratePrefs,scheduleState,normalizeNotes,normalizeLog,metricsForDay,dateKey}from'../src/app/core.mjs';

const root=path.resolve(process.argv[2]||'_site'),read=file=>fs.readFileSync(path.join(root,file),'utf8'),exists=file=>fs.existsSync(path.join(root,file)),assert=(value,message)=>{if(!value)throw new Error(message)},source=file=>fs.readFileSync(path.resolve(file),'utf8');
for(const file of['index.html','site.css','privacy.html','manifest.webmanifest','service-worker.js','pacefold-experience.txt','app/index.html','app/pacefold.css','app/pacefold.mjs','app/daily-image.json','app/auth.html','app/auth.js','app/icons/fold-mark.svg','app/icons/icon-192.png','app/icons/icon-512.png','app/fonts/pacefold-ma.woff2'])assert(exists(file),`Missing ${file}`);
assert(!exists('modules')&&!exists('styles')&&!exists('app/core.mjs'),'Readable source modules/styles/core must not ship');
assert(read('pacefold-experience.txt').trim()==='27.1.0 final-form-r1','Build identity is wrong');
for(const file of['app/pacefold.mjs','app/auth.js','service-worker.js']){const result=spawnSync(process.execPath,['--check',path.join(root,file)],{encoding:'utf8'});assert(result.status===0,`${file} syntax failed: ${result.stderr}`)}

const app=read('app/index.html'),runtime=read('app/pacefold.mjs'),styles=read('app/pacefold.css'),worker=read('service-worker.js'),manifest=JSON.parse(read('manifest.webmanifest')),daily=JSON.parse(read('app/daily-image.json'));
const main=source('src/modules/main.mjs'),finalForm=source('src/modules/final-form.js'),start=source('src/modules/start-cover.js'),stream=source('src/modules/stream-player.js'),windowCues=source('src/modules/window-cues.js'),cueStore=source('src/modules/cue-store.js'),scheduleSource=source('src/modules/schedule.js'),clock=source('src/modules/clock.js'),notes=source('src/modules/notes.js'),daylog=source('src/modules/daylog.js'),now=source('src/modules/now.js');
assert((app.match(/<link[^>]+stylesheet/g)||[]).length===1,'App must load exactly one stylesheet');assert((app.match(/<script/g)||[]).length===2,'App must load only MSAL and one bundled runtime before YouTube is requested');assert(!runtime.includes('./core.mjs')&&!runtime.includes('../modules/'),'Built runtime references source modules');
assert(main.includes('prepareFinalForm(ctx)')&&main.includes('installFinalForm(ctx)')&&main.includes('installStartCover(ctx)')&&main.includes('installStreamPlayer(ctx)')&&main.includes('installWindowCues(ctx)'),'Final runtime modules are not fully wired');
assert(finalForm.includes("FINAL_RELEASE='27.1.0'")&&finalForm.includes("FINAL_REVISION='final-form-r1'")&&finalForm.includes("STREAM_STORE='pacefold.stream.v1'"),'Final-form identity/storage contract is incomplete');
assert(finalForm.includes("ctx.prefs.profile==='original'?'Noodles':'Prep'")&&finalForm.includes('stream-focus-sounds'),'Original noodle identity or integrated focus sounds regressed');
assert(finalForm.includes('player:{...(payload.player||{}),soundChoice:ctx.prefs.soundChoice,soundVolume:ctx.prefs.soundVolume,stream}')&&finalForm.includes("localStorage.setItem(STREAM_STORE"),'My Music backup/restore is incomplete');
assert(finalForm.includes('custom.children.length<8'),'Eight custom moment slots are not preserved');assert(finalForm.includes('Clock and Now follow this privacy setting'),'Privacy settings copy is inconsistent');
assert(finalForm.includes('positions=[[51,12],[53,25],[53,39],[51,52]]'),'Multi-dot live favicon contract is missing');
assert(start.includes("const GOOGLE_SEARCH='https://www.google.com/search?q='")&&start.includes('cover-time-main')&&start.includes("ctx.captureNote?.(noteInput.value,'Note')"),'Daily surface/search/note contract is incomplete');
assert(stream.includes("const YT_API='https://www.youtube.com/iframe_api'")&&stream.includes('playVideoAt?.(')&&stream.includes('setShuffle?.(')&&stream.includes('setLoop?.(')&&stream.includes('getPlaylist?.()'),'Playlist-first YouTube player regressed');
assert(stream.includes('stream-library')&&stream.includes('My music')&&stream.includes("'music.youtube.com'"),'My Music / YouTube Music parsing regressed');
assert(app.includes("script-src 'self' https://www.youtube.com;")&&app.includes('frame-src https://login.microsoftonline.com https://www.youtube.com;'),'YouTube CSP allowance is missing');
assert(styles.includes('font-size:clamp(112px,14.8vw,238px)!important')&&styles.includes('.cover-clock:before'),'Giant hero clock styling is missing');
assert(styles.includes('html[data-cover="on"],html[data-cover="on"] body{overflow:hidden!important')&&styles.includes('.stream-player[data-state="empty"]')&&styles.includes('.stream-focus-grid'),'Final surface/player integration styling is incomplete');
assert(worker.includes("VERSION='27.1.0'")&&worker.includes('final-form-r1')&&worker.includes("indexedDB.open('pacefold-v26'"),'Service-worker release or durable cue DB continuity regressed');
assert(cueStore.includes("const DB_NAME='pacefold-v26'")&&cueStore.includes("label:named?item.label:'Scheduled moment'"),'Cue durability/privacy regressed');assert(scheduleSource.includes("const discreet=ctx.rhythmMode()!=='names'"),'Rhythm discretion regressed');assert(clock.includes('day-now-line')&&clock.includes('% of workday'),'Day Unfold regressed');assert(notes.includes("placeholder='Log a thought.'")&&notes.includes('note-inline-input'),'Daybook capture/editing regressed');assert(daylog.includes("['At work',metrics.desk")&&daylog.includes('renderYesterdayComparison'),'Day Log regressed');assert(now.includes("forecast_days:'2'")&&now.includes('weather-rain-window'),'Across-midnight weather context regressed');
assert(manifest.name==='Clock'&&manifest.short_name==='Clock'&&manifest.start_url==='./app/','Manifest is wrong');assert(windowCues.includes("document.title='Clock'")&&windowCues.includes('windowCueBloomUntil'),'Discreet window cue lifecycle regressed');
assert(typeof daily.url==='string'&&typeof daily.credit==='string'&&daily.source==='Bing image of the day','Daily image metadata shape is invalid');if(daily.url){assert(daily.url==='./daily-image.jpg'&&exists('app/daily-image.jpg'),'Daily image points to a missing local image');assert(daily.credit.length>0,'Daily image credit is missing')}

const toronto=migratePrefs({...DEFAULT_PREFS,timeZone:'America/Toronto',lat:43.6205,lng:-79.5132,profile:'original',asr:'hanafi',method:'15'}),summer=new Date('2026-08-10T16:00:00Z'),schedule=scheduleState(summer,toronto);assert(schedule.today.length===6&&schedule.today.every((item,index,rows)=>index===0||item.date>rows[index-1].date),'Prayer rhythm invalid');assert(schedule.today.find(item=>item.id==='asr').date>schedule.today.find(item=>item.id==='dhuhr').date,'Hanafi Asr invalid');
const migrated=migratePrefs({profile:'original',waterSips:8,noodleMinutes:45,customMoments:Array.from({length:8},(_,i)=>[`m${i}`,`Moment ${i}`,`${String(9+i).padStart(2,'0')}:00`])});assert(migrated.waterOz===8&&migrated.prepMinutes===45&&migrated.customMoments.length===8,'Legacy/custom preference migration failed');assert(normalizeNotes([{id:'old',text:'Old note',createdAt:'2026-08-10T12:00:00Z'}])[0].body==='Old note','Legacy note migration failed');const key=dateKey(summer,'America/Toronto'),log=normalizeLog({days:{[key]:{events:[{id:'f',type:'focus',source:'focus',label:'Focus',start:summer.getTime()-3600000,end:summer.getTime()}]}}});assert(metricsForDay(log,key,toronto,summer.getTime()).focus===3600000,'Day-log metrics failed');
console.log(JSON.stringify({release:'27.1.0',surface:'final-form-r1',giantClock:'checked',surfaceLock:'checked',dailyImage:daily.url?'packed':'fallback',streamPlayer:'YouTube + My Music + local focus sounds',backup:'stream state included',taskbar:'live clock + multi cue dots',storageContinuity:'checked',prayerSchedule:'passed'},null,2));
