import fs from'node:fs';
import path from'node:path';
import{spawnSync}from'node:child_process';
import{DEFAULT_PREFS,migratePrefs,scheduleState,normalizeNotes,normalizeLog,metricsForDay,dateKey}from'../src/app/core.mjs';

const root=path.resolve(process.argv[2]||'_site'),read=file=>fs.readFileSync(path.join(root,file),'utf8'),exists=file=>fs.existsSync(path.join(root,file)),assert=(value,message)=>{if(!value)throw new Error(message)},source=file=>fs.readFileSync(path.resolve(file),'utf8');
for(const file of['index.html','site.css','privacy.html','manifest.webmanifest','service-worker.js','pacefold-experience.txt','app/index.html','app/pacefold.css','app/pacefold.mjs','app/daily-image.json','app/auth.html','app/auth.js','app/icons/fold-mark.svg','app/icons/icon-192.png','app/icons/icon-512.png','app/fonts/pacefold-ma.woff2'])assert(exists(file),`Missing ${file}`);
assert(!exists('modules')&&!exists('styles')&&!exists('app/core.mjs'),'Readable source modules/styles/core must not ship');
assert(read('pacefold-experience.txt').trim()==='27.1.0 homepage-r7','Build identity is wrong');
for(const file of['app/pacefold.mjs','app/auth.js','service-worker.js']){const result=spawnSync(process.execPath,['--check',path.join(root,file)],{encoding:'utf8'});assert(result.status===0,`${file} syntax failed: ${result.stderr}`)}

const app=read('app/index.html'),auth=read('app/auth.html'),runtime=read('app/pacefold.mjs'),styles=read('app/pacefold.css'),worker=read('service-worker.js'),manifest=JSON.parse(read('manifest.webmanifest')),daily=JSON.parse(read('app/daily-image.json'));
const main=source('src/modules/main.mjs'),finalForm=source('src/modules/final-form.js'),homepage=source('src/modules/homepage-r7.js'),start=source('src/modules/start-cover.js'),stream=source('src/modules/stream-player.js'),security=source('src/modules/security.js'),notificationHardening=source('src/modules/notification-hardening.js'),ambient=source('src/modules/ambient.js'),windowCues=source('src/modules/window-cues.js'),cueStore=source('src/modules/cue-store.js'),scheduleSource=source('src/modules/schedule.js'),clock=source('src/modules/clock.js'),notes=source('src/modules/notes.js'),daylog=source('src/modules/daylog.js'),now=source('src/modules/now.js'),homepageStyle=source('src/styles/27-zzzzzzzzzzzzzzzzzz-homepage-r7.css');
assert((app.match(/<link[^>]+stylesheet/g)||[]).length===1,'App must load exactly one stylesheet');assert((app.match(/<script/g)||[]).length===2,'App must load only MSAL and one bundled runtime before YouTube is requested');assert(!runtime.includes('./core.mjs')&&!runtime.includes('../modules/'),'Built runtime references source modules');
assert(main.includes('prepareFinalForm(ctx)')&&main.includes('installFinalForm(ctx)')&&main.includes('installStartCover(ctx)')&&main.includes('installAmbient(ctx)')&&main.includes('installStreamPlayer(ctx)')&&main.includes('installWindowCues(ctx)')&&main.includes('installSecurity(ctx)')&&main.includes('installNotificationHardening(ctx)')&&main.includes('installHomepageR7(ctx)'),'Final runtime modules are not fully wired');
assert(finalForm.includes("FINAL_RELEASE='27.1.0'")&&finalForm.includes("FINAL_REVISION='final-form-r1'")&&finalForm.includes("STREAM_STORE='pacefold.stream.v1'"),'Final-form identity/storage contract is incomplete');
assert(finalForm.includes("ctx.prefs.profile==='original'?'Noodles':'Prep'")&&finalForm.includes('stream-focus-sounds'),'Original noodle identity or integrated focus sounds regressed');
assert(finalForm.includes('player:{...(payload.player||{}),soundChoice:ctx.prefs.soundChoice,soundVolume:ctx.prefs.soundVolume,stream}')&&finalForm.includes("localStorage.setItem(STREAM_STORE"),'My Music backup/restore is incomplete');
assert(finalForm.includes('custom.children.length<8'),'Eight custom moment slots are not preserved');assert(finalForm.includes('Clock and Now follow this privacy setting'),'Privacy settings copy is inconsistent');
assert(homepage.includes("HOMEPAGE_REVISION='homepage-r7'")&&homepage.includes('positions=[[17,51],[28,51],[39,51],[50,51]]')&&homepage.includes('ctx.renderCueFavicon?.()')&&homepage.includes('const baseRefreshCues=ctx.refreshCues'),'Homepage favicon visibility/immediate-refresh contract is missing');
assert(notificationHardening.includes('HEARTBEAT_MS=30000')&&notificationHardening.includes('ctx.refreshCues(true)')&&notificationHardening.includes('ctx.cueFavicon?.(ctx.currentCues||[])'),'Hidden/minimized cue heartbeat or multi-dot favicon refresh is missing');
assert(notificationHardening.includes("type:'CLOCK_BADGE'")&&notificationHardening.includes("typeof navigator.setAppBadge==='function'")&&notificationHardening.includes('await navigator.setAppBadge(count)'),'Promise-aware app badge delivery is missing');
assert(notificationHardening.includes('READY_TIMEOUT_MS=1800')&&notificationHardening.includes('new Notification(copy.label,fallback)')&&notificationHardening.includes("Notification.permission!=='granted'"),'Notification delivery fallback/permission reconciliation is missing');
assert(start.includes("const GOOGLE_SEARCH='https://www.google.com/search?q='")&&start.includes('cover-time-main')&&start.includes("ctx.captureNote?.(noteInput.value,'Note')")&&!start.includes('music-launch'),'Daily surface/search/note contract or legacy Music cleanup regressed');
assert(ambient.includes('cover-dayline')&&ambient.includes('--ambient-left')&&ambient.includes("ctx.workRange(ctx.prefs,now)"),'Ambient day horizon is missing');
assert(stream.includes("const YT_API='https://www.youtube.com/iframe_api'")&&stream.includes('playVideoAt?.(')&&stream.includes('setShuffle?.(')&&stream.includes('setLoop?.(')&&stream.includes('getPlaylist?.()'),'Playlist-first YouTube player regressed');
assert(stream.includes("url.protocol!=='https:'")&&stream.includes('url.username||url.password')&&stream.includes('https://www.youtube.com/watch?v=')&&stream.includes('https://i.ytimg.com/vi/'),'Media canonicalization or artwork hardening is missing');
assert(stream.includes('stream-library')&&stream.includes('My music')&&stream.includes("'music.youtube.com'"),'My Music / YouTube Music parsing regressed');
assert(security.includes('MAX_BACKUP_BYTES=5*1024*1024')&&security.includes('SAFE_TENANT')&&security.includes('Blocked non-OneNote Microsoft request')&&security.includes('privacy-curtain'),'Security runtime guardrails are incomplete');
assert(app.includes("default-src 'none'")&&app.includes("media-src 'self' blob:")&&!app.includes("media-src 'self' data: blob: https:")&&app.includes('img-src \'self\' data: blob: https://i.ytimg.com')&&app.includes('<meta name="referrer" content="strict-origin-when-cross-origin">'),'Production CSP/referrer policy is not hardened');
assert(auth.includes("default-src 'none'; script-src 'self'")&&auth.includes('form-action \'none\'')&&auth.includes('<title>Clock sign-in</title>')&&!auth.includes('Pacefold'),'Auth bridge shell is not hardened/neutral');
assert(styles.includes('Clock 27.1 — wow + security r4')&&styles.includes('.privacy-curtain')&&styles.includes('.cover-dayline')&&styles.includes('.music-room-cover'),'WOW/security visual/security layer is incomplete');
assert(styles.includes('html[data-cover="on"],html[data-cover="on"] body{overflow:hidden!important')&&styles.includes('.stream-player[data-state="empty"]')&&styles.includes('.stream-focus-grid'),'Final surface/player integration styling is incomplete');
assert(homepageStyle.includes('Clock 27.1 — homepage r7')&&homepageStyle.includes('Readability-first visual reset')&&homepageStyle.includes('html[data-cover="on"] .cue-cluster:not(:has(.cue-dot))')&&homepageStyle.includes('.now-grid>section.now-primary{background:#f7faf8')&&homepageStyle.includes('.cover-time-main{font-size:clamp(72px,8vw,104px)'),'Homepage-first readable visual layer is incomplete');
assert(styles.includes('Clock 27.1 — homepage r7')&&styles.lastIndexOf('Clock 27.1 — homepage r7')>styles.lastIndexOf('Clock 27.1 — wow + security r4'),'Homepage-r7 is not the final bundled visual layer');
assert(!fs.existsSync(path.resolve('src/styles/27-zzzzzzzzzzzzzzzz-visual-finale-r6.css'))&&!fs.existsSync(path.resolve('src/styles/27-zzzzzzzzzzzzzzzzz-visual-finale-r6-calibration.css')),'Unreadable visual-finale r6 layers are still present');
assert(worker.includes("VERSION='27.1.0'")&&worker.includes('wow-security-r4-notification-r5-homepage-r7')&&worker.includes("const DB_NAME='pacefold-v26'")&&worker.includes('SHELL_SET')&&worker.includes('AUTH_PATHS')&&worker.includes("frame-ancestors 'none'"),'Service-worker security/cache or durable cue DB continuity regressed');
assert(worker.includes("type==='CLOCK_BADGE'")&&worker.includes('setWorkerBadge')&&worker.includes('self.navigator.setAppBadge')&&worker.includes('refreshWorkerBadge'),'Service-worker taskbar badge path is missing');
assert(worker.includes('workWindows')&&worker.includes('!state.ack[cue.key]')&&worker.includes('cues.find(item=>!state.notified[item.key])'),'Worker waiting/notified state separation is missing');
assert(worker.includes('`eyes:${dateKey}:${Math.floor(now/eyeCadence)}`')&&worker.includes('`move:${dateKey}:${Math.floor(now/moveCadence)}`'),'Worker care cue keys do not match foreground cues');
assert(cueStore.includes("const DB_NAME='pacefold-v26'")&&cueStore.includes("label:named?item.label:'Scheduled moment'")&&cueStore.includes('workWindows')&&cueStore.includes('for(const date of[now,tomorrow])'),'Cue durability/privacy or two-day background mirror regressed');assert(scheduleSource.includes("const discreet=ctx.rhythmMode()!=='names'"),'Rhythm discretion regressed');assert(clock.includes('day-now-line')&&clock.includes('% of workday'),'Day Unfold regressed');assert(notes.includes("placeholder='Log a thought.'")&&notes.includes('note-inline-input'),'Daybook capture/editing regressed');assert(daylog.includes("['At work',metrics.desk")&&daylog.includes('renderYesterdayComparison'),'Day Log regressed');assert(now.includes("forecast_days:'2'")&&now.includes('weather-rain-window'),'Across-midnight weather context regressed');
assert(manifest.name==='Clock'&&manifest.short_name==='Clock'&&manifest.start_url==='./app/','Manifest is wrong');assert(windowCues.includes("document.title='Clock'")&&windowCues.includes('windowCueBloomUntil'),'Discreet window cue lifecycle regressed');
assert(!app.includes('Pacefold')&&!runtime.includes('Pacefold'),'Built app/runtime exposes the project name');
assert(typeof daily.url==='string'&&typeof daily.credit==='string'&&daily.source==='Bing image of the day','Daily image metadata shape is invalid');if(daily.url){assert(daily.url==='./daily-image.jpg'&&exists('app/daily-image.jpg'),'Daily image points to a missing local image');assert(daily.credit.length>0,'Daily image credit is missing')}

const toronto=migratePrefs({...DEFAULT_PREFS,timeZone:'America/Toronto',lat:43.6205,lng:-79.5132,profile:'original',asr:'hanafi',method:'15'}),summer=new Date('2026-08-10T16:00:00Z'),schedule=scheduleState(summer,toronto);assert(schedule.today.length===6&&schedule.today.every((item,index,rows)=>index===0||item.date>rows[index-1].date),'Prayer rhythm invalid');assert(schedule.today.find(item=>item.id==='asr').date>schedule.today.find(item=>item.id==='dhuhr').date,'Hanafi Asr invalid');
const migrated=migratePrefs({profile:'original',waterSips:8,noodleMinutes:45,customMoments:Array.from({length:8},(_,i)=>[`m${i}`,`Moment ${i}`,`${String(9+i).padStart(2,'0')}:00`])});assert(migrated.waterOz===8&&migrated.prepMinutes===45&&migrated.customMoments.length===8,'Legacy/custom preference migration failed');assert(normalizeNotes([{id:'old',text:'Old note',createdAt:'2026-08-10T12:00:00Z'}])[0].body==='Old note','Legacy note migration failed');const key=dateKey(summer,'America/Toronto'),log=normalizeLog({days:{[key]:{events:[{id:'f',type:'focus',source:'focus',label:'Focus',start:summer.getTime()-3600000,end:summer.getTime()}]}}});assert(metricsForDay(log,key,toronto,summer.getTime()).focus===3600000,'Day-log metrics failed');
console.log(JSON.stringify({release:'27.1.0',surface:'homepage-r7',homePage:'readability-first Edge surface',ambientHorizon:'checked',privacyCurtain:'checked',contentPolicy:'default-deny',dailyImage:daily.url?'packed':'fallback',streamPlayer:'YouTube + My Music + artwork + local focus sounds',backup:'5MB guard + stream state',notifications:'immediate favicon repaint + 30s heartbeat + worker badge + delivery fallback',taskbar:'large live favicon cue pips + app badge count',storageContinuity:'checked',prayerSchedule:'passed'},null,2));
