'use strict';
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {chromium}=require('playwright');
const site=path.resolve(process.argv[2]||'_release');
const artifacts=path.resolve(process.argv[3]||'/tmp/pacefold-experience-artifacts');
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
const dayKey=()=>{const value=new Date();return new Date(value-value.getTimezoneOffset()*60000).toISOString().slice(0,10)};
function settings(){const week={};for(let day=0;day<7;day++)week[day]={start:'08:30',end:'16:30',type:day>0&&day<6?'desk':'off'};return{profile:'original',schemaVersion:18,theme:'paper',privacy:false,quietMode:false,timeFormat:'12',showSeconds:true,workHours:'08:30-16:30',workWeek:week,workdaysOnly:false,workReminders:true,gazeEnabled:true,bodyEnabled:true,notifications:true,browserNotif:true,notificationMode:'quiet',taskbarBadge:true,taskbarBadgeMode:'due',waterTarget:24,sipCadence:30,waterSips:2,waterDate:dayKey(),waterLastAt:Date.now()-60000,prepPreset:'noodles',noodleMinutes:30,deskLunchMinutes:20,awayLunchMinutes:45,lunchMode:'desk',lat:43.62,lng:-79.51,locationLabel:'Toronto',method:'15',asr:'hanafi',offsets:{fajr:0,dhuhr:0,asr:0,maghrib:0,isha:0},waferPromptDismissed:true,activityDate:dayKey()}}
function serve(){return new Promise(resolve=>{const server=http.createServer((request,response)=>{let pathname='/';try{pathname=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname)}catch{}let file=path.join(site,pathname.replace(/^\/+/,''));if(pathname.endsWith('/'))file=path.join(file,'index.html');if(!file.startsWith(site)){response.writeHead(403);response.end();return}fs.readFile(file,(error,buffer)=>{if(error){response.writeHead(404);response.end();return}const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.woff2':'font/woff2','.png':'image/png','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream';response.writeHead(200,{'content-type':type,'cache-control':'no-store'});response.end(buffer)})});server.listen(0,'127.0.0.1',()=>resolve(server))})}
async function wait(page,label,predicate,arg=null,timeout=15000){try{await page.waitForFunction(predicate,arg,{timeout})}catch{throw new Error(`${label} did not settle`)}}
(async()=>{
  fs.mkdirSync(artifacts,{recursive:true});const server=await serve(),base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true}),errors=[];
  try{
    const context=await browser.newContext({viewport:{width:1280,height:860}});await context.addInitScript(value=>{localStorage.setItem('pacefoldPrefsV15',JSON.stringify(value));localStorage.setItem('pacefoldOnboardedV15','1');localStorage.setItem('pacefoldSetupDismissedV15','1')},settings());
    const page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'&&!/ERR_(?:INTERNET_DISCONNECTED|FAILED)/.test(message.text()))errors.push(message.text())});
    await page.goto(`${base}/app/`,{waitUntil:'domcontentloaded',timeout:30000});await wait(page,'Experience startup',()=>window.__PACEFOLD_EXPERIENCE__?.revision==='experience-r1'&&document.documentElement.dataset.pacefoldSpatial==='ready');await page.waitForTimeout(500);
    const startup=await page.evaluate(()=>({mode:document.getElementById('pf22-spatial-root')?.dataset.mode,legacy:document.documentElement.dataset.pacefoldSpatial,bootstrap:window.__PACEFOLD_BOOTSTRAP__?.revision,schedule:[...document.querySelectorAll('#pf23-schedule-strip [data-prayer]')].map(node=>node.dataset.prayer),contextCount:document.querySelectorAll('#pf23-context-schedule [data-prayer]').length,width:document.documentElement.scrollWidth,viewport:innerWidth}));
    assert(startup.mode==='home'&&startup.legacy==='ready'&&startup.bootstrap==='experience-r1',`Modern startup ownership failed: ${JSON.stringify(startup)}`);assert(startup.schedule.join(',')==='fajr,dhuhr,asr,maghrib,isha',`Home prayer schedule is incomplete: ${JSON.stringify(startup.schedule)}`);assert(startup.contextCount===6,`Context prayer schedule is incomplete: ${startup.contextCount}`);assert(startup.width<=startup.viewport,`Desktop overflow: ${JSON.stringify(startup)}`);
    const times=await page.evaluate(()=>window.__PACEFOLD_EXPERIENCE__.schedule().today.map(item=>item.date.getTime()));assert(times.length===6&&times.every(Number.isFinite)&&times.every((value,index)=>index===0||value>times[index-1]),`Prayer times are not finite and ordered: ${JSON.stringify(times)}`);
    await page.evaluate(()=>window.__PACEFOLD_SPATIAL__.go('notes'));await wait(page,'Notes mode',()=>document.getElementById('pf22-spatial-root')?.dataset.mode==='notes');await page.keyboard.press('ArrowDown');await wait(page,'Clock-centred navigation',()=>document.getElementById('pf22-spatial-root')?.dataset.mode==='home');
    await page.locator('#pf23-action-water').click();await wait(page,'Correct water logging',()=>{const value=JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}');return Number(value.waterSips)===3&&Number(value.waterLastAt)>0&&!('lastWaterAt'in value)});
    await page.locator('#pf23-action-away').click();await wait(page,'Rest start',()=>Number(JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}').awayStart)>0);await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('pacefoldPrefsV15'));value.awayStart=Date.now()-125000;localStorage.setItem('pacefoldPrefsV15',JSON.stringify(value));window.dispatchEvent(new CustomEvent('pacefold:ma-prefs'))});await page.locator('#pf23-action-away').click();await wait(page,'Rest duration logging',()=>{const value=JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}'),last=(value.awaySessions||[]).at(-1);return !value.awayStart&&Number(last?.minutes)>=2});
    await page.locator('#pf23-action-lunch').click();await wait(page,'Meal start',()=>Number(JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}').lunchStart)>0);await page.evaluate(()=>{const value=JSON.parse(localStorage.getItem('pacefoldPrefsV15'));value.lunchStart=Date.now()-185000;localStorage.setItem('pacefoldPrefsV15',JSON.stringify(value));window.dispatchEvent(new CustomEvent('pacefold:ma-prefs'))});await page.locator('#pf23-action-lunch').click();await wait(page,'Meal duration logging',()=>{const value=JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}'),last=(value.lunchSessions||[]).at(-1);return !value.lunchStart&&Number(last?.minutes)>=3});
    await page.locator('#pf23-action-eyes').click();await wait(page,'Eye reset logging',()=>Number(JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}').gazeLastAt)>0);await page.locator('#pf23-action-body').click();await wait(page,'Movement logging',()=>{const value=JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}');return Number(value.bodyLastAt)>0&&Number((value.bodySessions||[]).at(-1)?.seconds)===60});
    const receipt=await page.locator('#pf23-log-receipt').innerText();assert(/Last logged/i.test(receipt)&&/Movement/i.test(receipt),`Logging receipt is missing: ${receipt}`);await page.screenshot({path:path.join(artifacts,'pacefold-experience-home.png'),fullPage:true});
    await page.evaluate(()=>window.__PACEFOLD_SPATIAL__.go('context'));await wait(page,'Context layout',()=>document.getElementById('pf22-spatial-root')?.dataset.mode==='context');await page.screenshot({path:path.join(artifacts,'pacefold-experience-context.png'),fullPage:true});
    await context.close();
    const legacyContext=await browser.newContext({viewport:{width:1180,height:800}});await legacyContext.addInitScript(()=>{localStorage.setItem('pacefoldPrefsV14',JSON.stringify({profile:'original',workHours:'08:30-16:30',waterTarget:24,sipCadence:30}));localStorage.setItem('pacefoldOnboardedV14','1')});const legacyPage=await legacyContext.newPage();await legacyPage.goto(`${base}/app/`,{waitUntil:'domcontentloaded',timeout:30000});await wait(legacyPage,'Legacy returning-user takeover',()=>document.getElementById('pf22-spatial-root')&&document.documentElement.dataset.pacefoldSpatial==='ready');const legacy=await legacyPage.evaluate(()=>({returning:window.__PACEFOLD_BOOTSTRAP__?.returning,mode:document.getElementById('pf22-spatial-root')?.dataset.mode,onboarding:document.getElementById('onboarding')?.hidden}));assert(legacy.returning===true&&legacy.mode==='home',`Old preferences still expose the legacy surface: ${JSON.stringify(legacy)}`);await legacyContext.close();
    assert(!errors.length,`Browser errors: ${errors.join(' | ')}`);
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve))}
  console.log('Pacefold experience repair audit passed.');
})().catch(error=>{console.error(error);process.exitCode=1});
