(()=>{
'use strict';
const EXPERIENCE='21.3.1';
const RELEASE='21.3.1';
const REVISION='dayflow-r2';
const CORE='15.2.2',PREFS='pacefoldPrefsV15',FLOW='pacefold.dayflow.v1',NOTES='pacefold.notebook.entries.v2',DAY=86400000;
let frame=0,observer,snapshot,date='',tab='day',search='',flowKey='',bookKey='';
const $=s=>document.querySelector(s),id=s=>document.getElementById(s),txt=v=>String(v??'').replace(/\s+/g,' ').trim(),obj=v=>v&&typeof v==='object'&&!Array.isArray(v),json=(v,f)=>{try{return v?JSON.parse(v):f}catch{return f}},el=(t,c,x)=>{const n=document.createElement(t);if(c)n.className=c;if(x!=null)n.textContent=String(x);return n},btn=(c,a,x)=>{const n=el('button',c,x);n.type='button';if(a)n.setAttribute('aria-label',a);return n},local=(v=new Date())=>{const d=v instanceof Date?v:new Date(v);return Number.isNaN(d.getTime())?'':new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10)},clock=v=>new Date(Number(v)||v).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),label=k=>new Date(`${k}T12:00:00`).toLocaleDateString([],{weekday:'long',month:'long',day:'numeric'}),clamp=(v,a,b)=>Math.min(b,Math.max(a,Number(v)||0));
const prefs=()=>window.__PACEFOLD_MA_CORE__?.getPrefs?.()||obj(json(localStorage.getItem(PREFS),{}))||{};
const notes=()=>{const v=json(localStorage.getItem(NOTES),[]);return Array.isArray(v)?v:[]};
const noteDay=n=>{const explicit=String(n?.date||'');if(/^20\d\d-\d\d-\d\d$/.test(explicit))return explicit;for(const v of [n?.createdAt,n?.updatedAt,n?.timestamp]){if(!v)continue;const k=local(v);if(k)return k}return String(n?.id||'').match(/20\d\d-\d\d-\d\d/)?.[0]||''};
const dayNotes=k=>notes().filter(n=>noteDay(n)===k).sort((a,b)=>new Date(b.updatedAt||b.createdAt||0)-new Date(a.updatedAt||a.createdAt||0));
const empty=()=>({version:RELEASE,savedAt:new Date().toISOString(),days:{}});
const read=()=>{const v=json(localStorage.getItem(FLOW),null);return obj(v)&&obj(v.days)?{...v,version:RELEASE,days:{...v.days}}:empty()};
function norm(v,k){v=obj(v)?v:{};return{date:k,createdAt:v.createdAt||new Date().toISOString(),events:Array.isArray(v.events)?v.events.filter(obj).slice(-500):[]}}
function save(s){const cutoff=Date.now()-180*DAY;for(const k of Object.keys(s.days||{})){const t=new Date(`${k}T00:00:00`).getTime();if(!t||t<cutoff)delete s.days[k];else s.days[k]=norm(s.days[k],k)}s.version=RELEASE;s.savedAt=new Date().toISOString();localStorage.setItem(FLOW,JSON.stringify(s));window.dispatchEvent(new CustomEvent('pacefold:dayflow'));return s}
function getDay(s,k=local()){s.days=s.days||{};return s.days[k]=norm(s.days[k],k)}
const events=(k=local())=>norm(read().days?.[k],k).events.slice().sort((a,b)=>a.start-b.start);
const active=(source,k=local())=>[...events(k)].reverse().find(e=>e.source===source&&!e.end);
const eid=(t,s)=>`${t}-${Number(s).toString(36)}-${Math.random().toString(36).slice(2,6)}`;
function open(source,type,name,detail='',start=Date.now()){const s=read(),d=getDay(s,local(start));let e=d.events.find(x=>x.source===source&&!x.end);if(e)return e;e={id:eid(type,start),source,type,label:name,detail,start:Number(start)||Date.now(),end:null,meta:{}};d.events.push(e);save(s);return e}
function close(source,name='',end=Date.now()){const s=read();let found;for(const k of Object.keys(s.days||{}).sort().reverse()){found=[...getDay(s,k).events].reverse().find(e=>e.source===source&&!e.end);if(found){found.end=Math.max(found.start,end);break}}if(!found)return false;if(name)getDay(s,local(end)).events.push({id:eid('return',end),source:`return-${source}`,type:'return',label:name,detail:'',start:end,end,meta:{from:source}});save(s);return true}
function moment(type,name,detail='',start=Date.now(),source=type){const s=read(),d=getDay(s,local(start)),last=[...d.events].reverse().find(e=>e.source===source&&e.label===name);if(last&&Math.abs(last.start-start)<45000)return last;const e={id:eid(type,start),source,type,label:name,detail,start,end:start,meta:{}};d.events.push(e);save(s);return e}
function range(k=local()){const p=prefs(),d=new Date(`${k}T12:00:00`),r=obj(p.workWeek)?.[d.getDay()]||obj(p.workWeek)?.[String(d.getDay())]||{},m=String(p.workHours||'08:30-16:30').match(/^(\d\d:\d\d)-(\d\d:\d\d)$/),a=/^\d\d:\d\d$/.test(r.start)?r.start:m?.[1]||'08:30',b=/^\d\d:\d\d$/.test(r.end)?r.end:m?.[2]||'16:30';return{start:new Date(`${k}T${a}:00`).getTime(),end:new Date(`${k}T${b}:00`).getTime(),a,b}}
const dur=(e,now=Date.now())=>Math.max(0,(e.end||now)-e.start),fmt=(v,short=false)=>{const m=Math.max(0,Math.round(v/60000)),h=Math.floor(m/60),r=m%60;return short?(h?`${h}h ${String(r).padStart(2,'0')}m`:`${r}m`):(h?(r?`${h} hr ${r} min`:`${h} hr`):`${r} min`)};
function metrics(k=local()){const es=events(k),r=range(k),now=k===local()?Date.now():r.end,elapsed=Math.max(0,Math.min(now,r.end)-r.start),sum=t=>es.filter(e=>t.includes(e.type)).reduce((a,e)=>a+Math.max(0,Math.min(e.end||now,r.end)-Math.max(e.start,r.start)),0),field=sum(['field']),away=sum(['away']),meal=sum(['meal']),focus=sum(['focus']),desk=Math.max(0,elapsed-field-away-meal),p=prefs(),water=k===local()?(+p.waterSips||0):es.filter(e=>e.type==='water').reduce((a,e)=>Math.max(a,+e.meta?.total||0),0);return{k,events:es,range:r,elapsed,desk,field,away,meal,focus,water,notes:dayNotes(k).length,breaks:es.filter(e=>['away','meal','eyes','move'].includes(e.type)).length,focusBlocks:es.filter(e=>e.type==='focus').length}}
function insight(m){if(m.elapsed<1800000)return'Your workday log is just getting started.';if(m.field>5400000)return'Field-heavy day. The return points show where desk work resumed.';if(m.focus>=7200000)return'Strong focus depth today. Protect the conditions that created those blocks.';if(m.away+m.meal>Math.max(5400000,m.elapsed*.28))return'Time away is high relative to the logged window. Review transitions, not just the total.';if(!m.breaks&&m.elapsed>14400000)return'Long uninterrupted stretch. A short reset may improve the next block.';if(m.focusBlocks>=3)return'You built several focus blocks. Compare their timing to find your strongest window.';if(m.notes>=4)return'You captured useful context throughout the day. The log is becoming a reliable work record.';return'Your rhythm is balanced so far. Keep logging transitions instead of relying on memory.'}
function state(){const p=prefs(),dayType=document.body.dataset.dayType||p.todayOverride?.type||'desk';return{dayType,water:+p.waterSips||0,noteCount:dayNotes(local()).length,away:+p.awayStart||0,lunch:+p.lunchStart||0,timer:+p.noodleStart||0,eyes:+p.gazeActiveStart||0,body:+p.bodyActiveStart||0}}
function baseline(s){const r=range(),start=clamp(Date.now(),r.start,r.end),d=getDay(s,local());if(!d.events.some(e=>e.type==='day-start'))d.events.push({id:eid('day-start',start),source:'day-start',type:'day-start',label:'Workday opened',detail:'Pacefold began the local day log',start,end:start,meta:{}});save(s)}