'use strict';
(()=>{
  const RELEASE='18.0.0',PREFS_KEY='pacefoldPrefsV15',BACKUP_FORMAT='pacefold.backup.v1',MINUTE=60000,DAY_MS=86400000;
  const DAYS=['sun','mon','tue','wed','thu','fri','sat'];
  const ADDITIVE={schemaVersion:18,minCueGap:4,focusGraceMinutes:25,workWeek:null,quiet:false,maQuietRestore:null,waferSuggestion:'pending',foldReviewDismissed:false,storagePersistAsked:false};
  const state={prefs:null,booted:false,ribbon:null,fallback:null,ribbonMinute:-1,ribbonDate:'',lastInteraction:Date.now(),hiddenAt:0,quietText:new WeakMap(),statusTimer:0,minuteText:'',minuteGuard:false,optionMenu:null,scheduler:null,clipboardDecorate:false};
  const parse=(raw,fallback)=>{try{return JSON.parse(raw)??fallback}catch{return fallback}};
  const array=value=>Array.isArray(value)?value:[];
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
  const safe=(value,max=160)=>String(value??'').replace(/\s+/g,' ').trim().slice(0,max);
  const create=(tag,className,text)=>{const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node};
  const dayKey=(date=new Date())=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
  const minutes=value=>{const match=String(value||'').match(/^(\d{1,2}):(\d{2})$/);return match?Number(match[1])*60+Number(match[2]):0};
  function parseHours(value){const match=String(value||'08:30-16:30').match(/^(\d{1,2}):(\d{2})\s*-\s*(\d{1,2}):(\d{2})$/);return match?{start:`${match[1].padStart(2,'0')}:${match[2]}`,end:`${match[3].padStart(2,'0')}:${match[4]}`}:{start:'08:30',end:'16:30'}}
  function defaultWeek(workHours){const span=parseHours(workHours),week={};for(const name of DAYS)week[name]={...span,type:['sat','sun'].includes(name)?'Off':'Desk'};return week}
  function migrate(input){const next={...(input&&typeof input==='object'&&!Array.isArray(input)?input:{})};for(const [key,value] of Object.entries(ADDITIVE))if(!(key in next))next[key]=value;const fallback=defaultWeek(next.workHours);if(!next.workWeek||typeof next.workWeek!=='object')next.workWeek=fallback;for(const name of DAYS)next.workWeek[name]={...fallback[name],...(next.workWeek[name]||{})};next.schemaVersion=Math.max(18,Number(next.schemaVersion)||0);return next}
  function readPrefs(){state.prefs=migrate(parse(localStorage.getItem(PREFS_KEY),{}));return state.prefs}
  function writePrefs(patch,{dispatch=true}={}){const next=migrate({...readPrefs(),...patch});try{localStorage.setItem(PREFS_KEY,JSON.stringify(next));state.prefs=next}catch{}if(dispatch){try{window.dispatchEvent(new StorageEvent('storage',{key:PREFS_KEY,newValue:JSON.stringify(next)}))}catch{window.dispatchEvent(new Event('storage'))}window.__PACEFOLD_REVAMP__?.reconcile?.()}return next}
  function status(message,timeout=4000){const line=document.getElementById('statusLine');if(!line)return;clearTimeout(state.statusTimer);const previous=line.textContent;line.textContent=message;state.statusTimer=setTimeout(()=>{if(!quiet())line.textContent=previous},timeout)}
  function activeDay(date=new Date()){const prefs=readPrefs(),name=DAYS[date.getDay()],base={...defaultWeek(prefs.workHours)[name],...(prefs.workWeek?.[name]||{})},override=parse(sessionStorage.getItem(`pacefold.ma.dayType.${dayKey(date)}`),null);return override?{...base,type:override}:base}
  function itemMinute(item,keys){for(const key of keys){const raw=item?.[key];if(raw===undefined||raw===null)continue;if(typeof raw==='number'){const date=new Date(raw);if(Number.isFinite(date.getTime()))return date.getHours()*60+date.getMinutes()}if(/^\d{1,2}:\d{2}$/.test(String(raw)))return minutes(raw);const date=new Date(raw);if(Number.isFinite(date.getTime()))return date.getHours()*60+date.getMinutes()}return null}
  function todaySessions(value,date=dayKey()){return array(value).filter(item=>{const raw=item?.date||item?.day||item?.at||item?.startAt||item?.startedAt;if(!raw)return false;const parsed=new Date(raw);return Number.isFinite(parsed.getTime())&&dayKey(parsed)===date})}

  function installDigitFold(){const minute=document.getElementById('minute');if(!minute||minute.dataset.pfMaDigits)return;minute.dataset.pfMaDigits='true';const render=()=>{if(state.minuteGuard)return;const raw=(minute.textContent||'00').replace(/\D/g,'').padStart(2,'0').slice(-2);if(raw===state.minuteText&&minute.children.length===2)return;const old=state.minuteText.padStart(2,'0');state.minuteText=raw;state.minuteGuard=true;const fragment=document.createDocumentFragment();[...raw].forEach((digit,index)=>{const span=create('span','pf-time-digit',digit);if(old[index]!==digit&&old!=='00')span.classList.add('is-folding');fragment.append(span)});minute.replaceChildren(fragment);state.minuteGuard=false};render();new MutationObserver(render).observe(minute,{childList:true,characterData:true,subtree:true})}

  function ribbonMoments(start,end,date){const prefs=readPrefs(),out=[];for(const item of array(prefs.customMoments)){const at=itemMinute(item,['time','at','start']);if(at!==null&&at>=start&&at<=end)out.push({kind:'crease',at,label:safe(item.label||item.name||'Moment')})}for(const item of todaySessions(prefs.prayerSessions,date)){const at=itemMinute(item,['at','startAt','startedAt','time']);if(at!==null&&at>=start&&at<=end)out.push({kind:'prayer',at,label:safe(item.label||item.name||'Prayer')})}for(const item of todaySessions(prefs.lunchSessions,date)){const at=itemMinute(item,['startAt','startedAt','start','at']),to=itemMinute(item,['endAt','endedAt','end'])??(at===null?null:at+Number(item.minutes||prefs.deskLunchMinutes||30));if(at!==null)out.push({kind:'meal',at,to,label:'Meal'})}for(const [key,label] of [['awaySessions','Away'],['bodySessions','Movement']])for(const item of todaySessions(prefs[key],date)){const at=itemMinute(item,['startAt','startedAt','start','at']),to=itemMinute(item,['endAt','endedAt','end'])??(at===null?null:at+Number(item.minutes||5));if(at!==null)out.push({kind:'band',at,to,label})}return out}
  function buildRibbon(){const sequence=document.getElementById('sequence');if(!sequence||sequence.dataset.pfMaRibbon)return;const fallback=[...sequence.childNodes].map(node=>node.cloneNode(true));try{sequence.dataset.pfMaRibbon='true';sequence.classList.add('pf-day-ribbon');const track=create('div','pf-ribbon-track'),spent=create('div','pf-ribbon-spent'),ticks=create('div','pf-ribbon-ticks'),marks=create('div','pf-ribbon-marks'),now=create('div','pf-ribbon-now');spent.dataset.pfRibbonSpent=now.dataset.pfRibbonNow=marks.dataset.pfRibbonMarks='true';track.append(spent,ticks,marks,now);sequence.replaceChildren(track);state.ribbon={sequence,track,spent,ticks,marks,now};state.fallback=fallback;renderRibbon(true);tickRibbon()}catch(error){sequence.replaceChildren(...fallback.map(node=>node.cloneNode(true)));delete sequence.dataset.pfMaRibbon;sequence.classList.remove('pf-day-ribbon');state.ribbon=null;console.warn('Pacefold Ma ribbon fallback',error)}}
  function renderRibbon(force=false){const ribbon=state.ribbon;if(!ribbon)return;const now=new Date(),date=dayKey(now),day=activeDay(now),start=minutes(day.start),end=minutes(day.end),span=Math.max(1,end-start),prefs=readPrefs();const signature=JSON.stringify([date,day,prefs.customMoments,prefs.prayerSessions,prefs.lunchSessions,prefs.awaySessions,prefs.bodySessions,quiet()]);if(!force&&ribbon.marks.dataset.signature===signature)return;ribbon.marks.dataset.signature=signature;ribbon.sequence.dataset.dayType=String(day.type||'Desk').toLowerCase().replace(/\s+/g,'-');ribbon.ticks.replaceChildren();for(let at=Math.ceil(start/60)*60;at<end;at+=60){const tick=create('span','pf-ribbon-tick');tick.style.setProperty('--pf-x',`${((at-start)/span)*100}%`);ribbon.ticks.append(tick)}ribbon.marks.replaceChildren();for(const moment of ribbonMoments(start,end,date)){const mark=create('button',`pf-ribbon-mark is-${moment.kind}`);mark.type='button';const left=clamp((moment.at-start)/span,0,1),width=moment.to?clamp((moment.to-moment.at)/span,.002,1-left):0;mark.style.setProperty('--pf-x',`${left*100}%`);mark.style.setProperty('--pf-w',`${width*100}%`);const label=quiet()?'Day interval':moment.label;mark.dataset.label=label;mark.setAttribute('aria-label',label);mark.addEventListener('click',()=>status(label));mark.addEventListener('mouseenter',()=>status(label));ribbon.marks.append(mark)}}
  function tickRibbon(){const ribbon=state.ribbon;if(!ribbon)return;const now=new Date(),day=activeDay(now),start=minutes(day.start),end=minutes(day.end),span=Math.max(1,end-start),at=now.getHours()*60+now.getMinutes()+now.getSeconds()/60,ratio=clamp((at-start)/span,0,1);ribbon.now.style.transform=`translateX(${ratio*100}%)`;ribbon.spent.style.transform=`scaleX(${ratio})`;ribbon.sequence.dataset.outside=at<start||at>end?'true':'false';document.documentElement.style.setProperty('--pf-second',String(now.getSeconds()));if(state.ribbonMinute!==now.getMinutes()||state.ribbonDate!==dayKey(now)){state.ribbonMinute=now.getMinutes();state.ribbonDate=dayKey(now);renderRibbon()}}

  function solarElevation(date,lat,lon){const rad=Math.PI/180,start=new Date(date.getFullYear(),0,0),day=Math.floor((date-start)/DAY_MS),hour=date.getHours()+date.getMinutes()/60,gamma=2*Math.PI/365*(day-1+(hour-12)/24),decl=.006918-.399912*Math.cos(gamma)+.070257*Math.sin(gamma)-.006758*Math.cos(2*gamma)+.000907*Math.sin(2*gamma)-.002697*Math.cos(3*gamma)+.00148*Math.sin(3*gamma),eq=229.18*(.000075+.001868*Math.cos(gamma)-.032077*Math.sin(gamma)-.014615*Math.cos(2*gamma)-.040849*Math.sin(2*gamma)),trueSolar=(hour*60+eq+4*lon-date.getTimezoneOffset())%1440,angle=(trueSolar/4<0?trueSolar/4+180:trueSolar/4-180)*rad;return Math.asin(Math.sin(lat*rad)*Math.sin(decl)+Math.cos(lat*rad)*Math.cos(decl)*Math.cos(angle))/rad}
  function light(){const prefs=readPrefs(),root=document.documentElement;if(matchMedia('(prefers-contrast: more)').matches||matchMedia('(forced-colors: active)').matches){root.style.setProperty('--pf-warmth','0');return}const lat=Number(prefs.lat),lon=Number(prefs.lng);if(!Number.isFinite(lat)||!Number.isFinite(lon)){root.style.setProperty('--pf-warmth','0');return}const warmth=clamp((25-solarElevation(new Date(),lat,lon))/55,-.12,.18),paper=[242+Math.round(warmth*15),240+Math.round(warmth*7),233-Math.round(warmth*7)],ink=[34+Math.round(warmth*4),47+Math.round(warmth),40-Math.round(warmth*3)];root.style.setProperty('--pf-warmth',warmth.toFixed(3));root.style.setProperty('--pf-paper-live',`rgb(${paper.join(' ')})`);root.style.setProperty('--pf-ink-live',`rgb(${ink.join(' ')})`)}
  function nodeProgress(node){for(const attr of ['aria-valuenow','data-value','data-progress']){const value=Number(node.getAttribute?.(attr));if(Number.isFinite(value))return value}const match=String(node.textContent||'').match(/(\d+(?:\.\d+)?)\s*(?:%|\/\s*(\d+(?:\.\d+)?))?/);return match?(match[2]?Number(match[1])/Math.max(1,Number(match[2]))*100:Number(match[1])):0}
  function meters(){const prefs=readPrefs(),specs=[['waterMeter','bar',clamp(Number(prefs.waterSips||0)/Math.max(1,Number(prefs.waterTarget||8))*100,0,100)],['lunchMeter','fill',null],['noodleRing','arc',null]];for(const [id,shape,fixed] of specs){const node=document.getElementById(id);if(!node)continue;node.classList.add('pf-meter',`pf-meter-${shape}`);node.style.setProperty('--pf-meter',`${fixed??clamp(nodeProgress(node),0,100)}%`)}for(const [selector,shape] of [['#eyesBtn','arc'],['#awayBtn','fill']]){const node=document.querySelector(selector);if(node){node.classList.add('pf-meter-host',`pf-meter-${shape}`);node.style.setProperty('--pf-meter',`${clamp(nodeProgress(node),0,100)}%`)}}}

  const quiet=()=>Boolean(readPrefs().quiet);
  const quietSelectors=()=>['#statusLine','#statusWord','#eventName','#eventTime','#relativeTime','.pf-notebook-tabs>button:not(.pf-tab-add)','.pf-note-block select','.pf-kicker'];
  function applyQuiet(){const on=quiet();document.body?.toggleAttribute('data-pf-quiet',on);document.documentElement.toggleAttribute('data-pf-quiet',on);if(on){document.title='Document';for(const selector of quietSelectors())for(const node of document.querySelectorAll(selector)){if(!state.quietText.has(node))state.quietText.set(node,node.textContent);node.textContent=node.matches('#statusLine,#statusWord')?'Quiet':node.matches('.pf-notebook-tabs>button')?'Tab':node.matches('#eventTime,#relativeTime')?'':'—'}}else{for(const selector of quietSelectors())for(const node of document.querySelectorAll(selector)){const value=state.quietText.get(node);if(value!==undefined){node.textContent=value;state.quietText.delete(node)}}document.title='Pacefold';window.__PACEFOLD_REVAMP__?.reconcile?.()}renderRibbon(true)}
  function toggleQuiet(){const prefs=readPrefs();if(!prefs.quiet){writePrefs({quiet:true,maQuietRestore:{privacy:prefs.privacy,clarity:prefs.clarity,taskbarBadge:prefs.taskbarBadge,notificationDetail:prefs.notificationDetail,notificationMode:prefs.notificationMode},privacy:true,taskbarBadge:false,notificationDetail:'generic',notificationMode:'silent'});status('Quiet on.')}else{writePrefs({quiet:false,maQuietRestore:null,...(prefs.maQuietRestore||{})});status('Quiet off.')}applyQuiet();quietButton()}
  function quietButton(){let button=document.getElementById('pfQuietToggle');if(button){button.setAttribute('aria-pressed',String(quiet()));return}const anchor=document.querySelector('.clock-shell')||document.querySelector('main');if(!anchor)return;button=create('button','pf-quiet-toggle','Quiet');button.id='pfQuietToggle';button.type='button';button.setAttribute('aria-pressed',String(quiet()));button.addEventListener('click',toggleQuiet);anchor.append(button)}

  class CueScheduler{
    constructor(){this.lastDelivered=0;this.pending=new Map();this.nativeNotification=window.Notification;this.install()}
    priority(title,options={}){const text=`${title||''} ${options.body||''} ${document.body?.dataset.source||''}`.toLowerCase();if(/prayer|salah|fajr|dhuhr|asr|maghrib|isha|meal|lunch/.test(text))return 5;if(/prep|noodle|timer/.test(text))return 4;if(/water|hydrat/.test(text))return 3;if(/eye|gaze/.test(text))return 2;if(/body|move|stretch/.test(text))return 1;return 3}
    focusBlocked(priority){return priority<4&&(document.hidden||Date.now()-state.lastInteraction>Number(readPrefs().focusGraceMinutes||25)*MINUTE)}
    enqueue(kind,title,options,deliver,deferred=false){if(quiet())return kind==='notification'?Promise.resolve():undefined;const priority=this.priority(title,options);if(this.focusBlocked(priority))return kind==='notification'?Promise.resolve():undefined;const now=Date.now(),gap=Number(readPrefs().minCueGap||4)*MINUTE,due=this.lastDelivered+gap,run=()=>{if(quiet()||this.focusBlocked(priority))return kind==='notification'?Promise.resolve():undefined;this.lastDelivered=Date.now();document.body?.setAttribute('data-pf-waiting-cue','true');setTimeout(()=>document.body?.removeAttribute('data-pf-waiting-cue'),Math.max(1,Number(readPrefs().dueWindow||10))*MINUTE);return deliver()};if(now>=due)return run();if(deferred)return kind==='notification'?Promise.resolve():undefined;const key=`${kind}:${priority}`,existing=this.pending.get(key);if(existing&&existing.priority>=priority)return kind==='notification'?Promise.resolve():undefined;if(existing)clearTimeout(existing.timer);const timer=setTimeout(()=>{this.pending.delete(key);this.enqueue(kind,title,options,deliver,true)},Math.max(0,due-now));this.pending.set(key,{priority,timer});return kind==='notification'?Promise.resolve():undefined}
    install(){const Native=this.nativeNotification;if(typeof Native==='function'&&!Native.__pacefoldMa){const scheduler=this;function WrappedNotification(title,options={}){const placeholder=new EventTarget();scheduler.enqueue('notification',title,options,()=>{try{const actual=new Native(title,options);for(const type of ['click','close','error','show'])actual.addEventListener(type,event=>placeholder.dispatchEvent(new Event(event.type)));return actual}catch{return null}});return placeholder}Object.defineProperties(WrappedNotification,{permission:{get:()=>Native.permission},maxActions:{get:()=>Native.maxActions||0},__pacefoldMa:{value:true}});WrappedNotification.requestPermission=(...args)=>Native.requestPermission(...args);try{window.Notification=WrappedNotification}catch{}}const proto=globalThis.ServiceWorkerRegistration?.prototype;if(proto?.showNotification&&!proto.showNotification.__pacefoldMa){const native=proto.showNotification,scheduler=this,wrapped=function(title,options={}){return scheduler.enqueue('notification',title,options,()=>native.call(this,title,options))||Promise.resolve()};Object.defineProperty(wrapped,'__pacefoldMa',{value:true});try{proto.showNotification=wrapped}catch{}}if(typeof navigator.setAppBadge==='function'&&!navigator.setAppBadge.__pacefoldMa){const native=navigator.setAppBadge.bind(navigator),scheduler=this,wrapped=value=>scheduler.enqueue('badge','Badge',{body:String(value??'')},()=>native(value));Object.defineProperty(wrapped,'__pacefoldMa',{value:true});try{navigator.setAppBadge=wrapped}catch{}}}
    simulate(cues,minGap=4){let at=-Infinity;const delivered=[];for(const cue of cues.sort((a,b)=>a.at-b.at||b.priority-a.priority)){if(cue.at-at>=minGap){delivered.push(cue);at=cue.at}else if(!cue.deferred){const next={...cue,at:at+minGap,deferred:true};if(next.at<=1440)cues.push(next)}}return delivered}
  }
  function reconcileDrift(now=Date.now(),forcedGap=null){const prefs=readPrefs(),gap=forcedGap??(state.hiddenAt?now-state.hiddenAt:0),stale=Math.max(1,Number(prefs.staleAfterMinutes||15))*MINUTE;if(gap<=stale)return null;const skipped=[],water=Math.floor(gap/(Math.max(5,Number(prefs.sipCadence||30))*MINUTE)),eyes=Math.floor(gap/(Math.max(5,Number(prefs.gazeCadence||20))*MINUTE)),body=Math.floor(gap/(Math.max(5,Number(prefs.bodyCadence||45))*MINUTE));if(water)skipped.push(water===1?'water cue':`${water} water cues`);if(eyes)skipped.push(eyes===1?'eye reset':`${eyes} eye resets`);if(body)skipped.push(body===1?'movement reset':`${body} movement resets`);writePrefs({waterLastAt:now,gazeLastAt:now,bodyLastAt:now},{dispatch:false});const total=Math.round(gap/MINUTE),hours=Math.floor(total/60),mins=total%60,elapsed=hours?`${hours}h${mins?` ${mins}m`:''}`:`${mins}m`,line=`Back after ${elapsed}.${skipped.length?` ${skipped.join(' and ')} skipped.`:''}`;status(line,7000);return line}

  function dayTypeButton(){if(document.getElementById('pfDayTypeToggle'))return;const line=document.getElementById('statusLine');if(!line?.parentElement)return;const button=create('button','pf-day-type-toggle',activeDay().type||'Desk');button.id='pfDayTypeToggle';button.type='button';button.title='Change today only';button.addEventListener('click',()=>{const types=['Desk','Field','Half day','Off'],current=activeDay().type||'Desk',next=types[(types.indexOf(current)+1)%types.length];sessionStorage.setItem(`pacefold.ma.dayType.${dayKey()}`,JSON.stringify(next));button.textContent=next;document.body.dataset.pfDayType=next.toLowerCase().replace(/\s+/g,'-');renderRibbon(true);status(`${next} today.`)});line.parentElement.append(button);document.body.dataset.pfDayType=(activeDay().type||'Desk').toLowerCase().replace(/\s+/g,'-')}
  const countToday=value=>todaySessions(value).length;
  function rhythmSummary(){const prefs=readPrefs();return `--- Pacefold rhythm ---\nDay: ${activeDay().type||'Desk'}\nWater: ${Number(prefs.waterSips||0)}\nMeals: ${countToday(prefs.lunchSessions)}\nIntervals: ${countToday(prefs.bodySessions)+countToday(prefs.awaySessions)+countToday(prefs.prayerSessions)}\nCarry forward: Review unfinished notes.\n--- End rhythm ---\n\n`}
  function clipboard(){const api=navigator.clipboard;if(!api?.writeText||api.writeText.__pacefoldMa)return;const native=api.writeText.bind(api),wrapped=text=>{const value=state.clipboardDecorate?rhythmSummary()+String(text):String(text);state.clipboardDecorate=false;return native(value)};Object.defineProperty(wrapped,'__pacefoldMa',{value:true});try{api.writeText=wrapped}catch{}document.addEventListener('click',event=>{if(event.target.closest?.('[data-pf-copy-day]'))state.clipboardDecorate=true},true)}
  function foldReview(){const prefs=readPrefs();if(!prefs.dayCloseEnabled||prefs.foldReviewDismissed||document.getElementById('pfFoldReview'))return;const day=activeDay(),now=new Date();if(now.getHours()*60+now.getMinutes()<minutes(day.end))return;const host=document.getElementById('setupDock')||document.getElementById('foldBody')||document.querySelector('main');if(!host)return;const card=create('section','pf-fold-review');card.id='pfFoldReview';card.setAttribute('aria-label','Fold review');card.append(create('strong','','Fold review'));const values=create('div','pf-fold-review-numbers');for(const [label,value] of [['Water',Number(prefs.waterSips||0)],['Meals',countToday(prefs.lunchSessions)],['Intervals',countToday(prefs.bodySessions)+countToday(prefs.awaySessions)+countToday(prefs.prayerSessions)]]){const item=create('span');item.append(create('b','',String(value)),create('small','',label));values.append(item)}const dismiss=create('button','','Dismiss');dismiss.type='button';dismiss.addEventListener('click',()=>{writePrefs({foldReviewDismissed:true});card.remove()});card.append(values,create('p','','Carry forward: Review unfinished notes.'),dismiss);host.append(card)}

  function closeMenu(){state.optionMenu?.remove();state.optionMenu=null}
  function ritualOptions(){for(const ritual of document.querySelectorAll('.ritual')){if(ritual.querySelector('.pf-ritual-options'))continue;const chevron=create('button','pf-ritual-options','⌄');chevron.type='button';chevron.setAttribute('aria-label','Options');chevron.addEventListener('click',event=>{event.stopPropagation();closeMenu();const id=ritual.id||ritual.querySelector('button')?.id||'',menu=create('div','pf-ritual-menu');menu.setAttribute('role','menu');const items=[];if(/lunch/i.test(id))items.push(['Desk lunch',()=>ritual.click()],['Away lunch',()=>ritual.dispatchEvent(new MouseEvent('click',{bubbles:true,shiftKey:true}))]);for(const duration of [5,8,10,15,20,30,45,60])items.push([`${duration} min`,()=>{writePrefs(/noodle/i.test(id)?{noodleMinutes:duration}:/lunch/i.test(id)?{deskLunchMinutes:duration}:{snoozeMinutes:duration});ritual.click()}]);items.push(['Snooze',()=>ritual.dispatchEvent(new MouseEvent('click',{bubbles:true,shiftKey:true}))],['Skip today',()=>{localStorage.setItem(`pacefold.ma.skip.${id}.${dayKey()}`,'1');status('Skipped today.')}]);for(const [label,action] of items){const button=create('button','',label);button.type='button';button.setAttribute('role','menuitem');button.addEventListener('click',()=>{closeMenu();action()});menu.append(button)}chevron.parentElement.append(menu);state.optionMenu=menu;menu.querySelector('button')?.focus()});ritual.append(chevron)}}

  function stripSecrets(value){if(Array.isArray(value))return value.map(stripSecrets);if(!value||typeof value!=='object')return value;const out={};for(const [key,item] of Object.entries(value)){if(!/token|secret|auth|credential|password/i.test(key))out[key]=stripSecrets(item)}return out}
  function backup(){const prefs=stripSecrets(readPrefs());return {format:BACKUP_FORMAT,schemaVersion:1,createdAt:new Date().toISOString(),prefs,notes:parse(localStorage.getItem('pacefold.notebook.entries.v2'),[]),categories:parse(localStorage.getItem('pacefold.notebook.categories.v1'),[]),playlists:parse(localStorage.getItem('pacefold.player.playlists.v1'),[]),streamingLinks:parse(localStorage.getItem('pacefold.player.streaming-links.v1'),[]),history:prefs.history||[]}}
  function downloadBackup(){const blob=new Blob([JSON.stringify(backup(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=create('a');anchor.href=url;anchor.download=`pacefold-${dayKey()}-backup.json`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function restoreDiff(incoming){const current=backup();return ['prefs','notes','categories','playlists','streamingLinks','history'].map(key=>{const oldValue=JSON.stringify(current[key]??null),newValue=JSON.stringify(incoming[key]??null);return {key,status:newValue==='null'?'Skip':oldValue===newValue?'Unchanged':oldValue==='null'||oldValue==='[]'?'Add':'Overwrite'}})}
  function applyRestore(incoming){if(incoming?.format!==BACKUP_FORMAT||Number(incoming.schemaVersion)!==1){status('Backup format not supported.');return}if(incoming.prefs)localStorage.setItem(PREFS_KEY,JSON.stringify(migrate({...readPrefs(),...incoming.prefs,schemaVersion:18})));for(const [key,storageKey] of [['notes','pacefold.notebook.entries.v2'],['categories','pacefold.notebook.categories.v1'],['playlists','pacefold.player.playlists.v1'],['streamingLinks','pacefold.player.streaming-links.v1']])if(incoming[key]!==undefined)localStorage.setItem(storageKey,JSON.stringify(incoming[key]));status('Restore applied.');location.reload()}
  function restoreDialog(incoming){document.getElementById('pfRestoreDialog')?.remove();const dialog=create('dialog','pf-restore-dialog');dialog.id='pfRestoreDialog';dialog.append(create('strong','','Restore preview'));const list=create('dl');for(const row of restoreDiff(incoming))list.append(create('dt','',row.key),create('dd','',row.status));const actions=create('div','pf-dialog-actions'),cancel=create('button','','Cancel'),apply=create('button','','Apply restore');cancel.type=apply.type='button';cancel.addEventListener('click',()=>dialog.close());apply.addEventListener('click',()=>{applyRestore(incoming);dialog.close()});actions.append(cancel,apply);dialog.append(list,actions);document.body.append(dialog);dialog.showModal()}
  function backupControls(){if(document.getElementById('pfBackupControls'))return;const host=document.getElementById('setupDock')||document.getElementById('foldBody');if(!host)return;const wrap=create('div','pf-backup-controls'),save=create('button','','Back up'),restore=create('label','','Restore'),input=create('input');wrap.id='pfBackupControls';save.type='button';save.addEventListener('click',downloadBackup);input.type='file';input.accept='application/json,.json';input.hidden=true;restore.append(input);input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;try{restoreDialog(JSON.parse(await file.text()))}catch{status('Backup file could not be read.')}input.value=''});wrap.append(save,restore);host.append(wrap)}

  async function estimate(){if(!navigator.storage?.estimate)return null;try{return await navigator.storage.estimate()}catch{return null}}
  async function storageLine(){const host=document.getElementById('setupDock')||document.getElementById('foldBody');if(!host)return;let line=document.getElementById('pfStorageLine');if(!line){line=create('p','pf-storage-line');line.id='pfStorageLine';host.append(line)}const data=await estimate();if(!data){line.textContent='Stored locally. Size unavailable.';return}const mb=value=>`${(Number(value||0)/1048576).toFixed(Number(value||0)>10485760?0:1)} MB`;line.textContent=`Stored locally: ${mb(data.usage)} of about ${mb(data.quota)} available.`}
  async function persist(){const prefs=readPrefs();if(prefs.storagePersistAsked)return;writePrefs({storagePersistAsked:true},{dispatch:false});try{await navigator.storage?.persist?.()}catch{}}
  async function fits(files){const data=await estimate();if(!data)return true;const bytes=[...files].reduce((sum,file)=>sum+Number(file.size||0),0);return Number(data.usage||0)+bytes<Number(data.quota||0)*.85}
  function audioGuard(){document.addEventListener('change',async event=>{const input=event.target;if(!(input instanceof HTMLInputElement)||input.type!=='file'||!input.files?.length||![...input.files].some(file=>file.type.startsWith('audio/')))return;if(!await fits(input.files)){input.value='';status('Audio import would use too much local storage. Remove files or choose fewer tracks.',7000)}},true);document.addEventListener('drop',async event=>{const files=event.dataTransfer?.files;if(!files?.length||![...files].some(file=>file.type.startsWith('audio/'))||await fits(files))return;event.preventDefault();event.stopImmediatePropagation();status('Audio import would use too much local storage. Remove files or choose fewer tracks.',7000)},true)}

  function waferSuggestion(){const small=innerWidth<=340&&innerHeight<=150,key='pacefold.ma.wafer.launches';let count=Number(localStorage.getItem(key)||0);count=small?count+1:0;localStorage.setItem(key,String(count));const prefs=readPrefs();if(count<2||prefs.waferSuggestion!=='pending')return;const host=document.getElementById('setupDock');if(!host||document.getElementById('pfWaferSuggestion'))return;const line=create('div','pf-wafer-suggestion'),use=create('button','','Use Wafer'),dismiss=create('button','','Dismiss');line.id='pfWaferSuggestion';line.append(create('span','','Use Wafer for this window.'));use.type=dismiss.type='button';use.addEventListener('click',()=>{writePrefs({clarity:'wafer',waferSuggestion:'accepted'});document.body.dataset.clarity='wafer';line.remove()});dismiss.addEventListener('click',()=>{writePrefs({waferSuggestion:'dismissed'});line.remove()});line.append(use,dismiss);host.append(line)}
  function waferEdge(){if(document.getElementById('pfWaferEdge'))return;const button=create('button','pf-wafer-edge','•••');button.id='pfWaferEdge';button.type='button';button.setAttribute('aria-expanded','false');button.addEventListener('click',()=>{const open=document.body.toggleAttribute('data-pf-wafer-open');button.setAttribute('aria-expanded',String(open))});document.body.append(button);document.addEventListener('focusin',event=>{if(!event.target.closest?.('#workline,#quietDock,#pfWaferEdge')){document.body.removeAttribute('data-pf-wafer-open');button.setAttribute('aria-expanded','false')}})}
  function wco(){const overlay=navigator.windowControlsOverlay,apply=()=>document.documentElement.toggleAttribute('data-pf-wco',Boolean(overlay?.visible));apply();try{overlay?.addEventListener('geometrychange',apply)}catch{}}

  function reconcile(){installDigitFold();buildRibbon();meters();quietButton();dayTypeButton();ritualOptions();backupControls();foldReview();applyQuiet()}
  function observers(){for(const type of ['pointerdown','keydown','touchstart'])document.addEventListener(type,()=>state.lastInteraction=Date.now(),{passive:true,capture:true});document.addEventListener('click',event=>{if(state.optionMenu&&!event.target.closest('.pf-ritual-menu,.pf-ritual-options'))closeMenu()},true);document.addEventListener('visibilitychange',()=>{if(document.hidden)state.hiddenAt=Date.now();else{reconcileDrift();state.hiddenAt=0;renderRibbon(true)}});window.addEventListener('focus',()=>{reconcileDrift();state.hiddenAt=0});window.addEventListener('storage',event=>{if(event.key===PREFS_KEY){readPrefs();applyQuiet();renderRibbon(true);meters()}});new MutationObserver(reconcile).observe(document.documentElement,{childList:true,subtree:true,characterData:true})}
  function init(){if(state.booted)return;state.booted=true;readPrefs();const prefs=readPrefs();if(document.body){document.body.dataset.theme=String(prefs.theme||document.documentElement.dataset.theme||'auto');document.body.dataset.clarity=String(prefs.clarity||document.documentElement.dataset.clarity||'discreet')}requestAnimationFrame(()=>requestAnimationFrame(()=>document.documentElement.classList.remove('pf-boot')));observers();clipboard();audioGuard();wco();persist();reconcile();light();waferSuggestion();waferEdge();storageLine();setInterval(tickRibbon,1000);setInterval(light,10*MINUTE);setInterval(meters,MINUTE);setInterval(foldReview,MINUTE);window.__PACEFOLD_MA__={release:RELEASE,readPrefs,writePrefs,ribbon:{render:()=>renderRibbon(true),tick:tickRibbon},scheduler:state.scheduler,reconcileDrift,quiet:{on:()=>{if(!quiet())toggleQuiet()},off:()=>{if(quiet())toggleQuiet()}},backup,rhythmSummary,activeDay}}
  state.scheduler=new CueScheduler();
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
