function renderBook(){const root=book();if(!root)return;const k=date||local(),m=metrics(k),ns=dayNotes(k),key=JSON.stringify([tab,k,search,m.events.map(e=>[e.id,e.end]),ns.map(n=>[n.id,n.updatedAt])]);if(key===bookKey)return;bookKey=key;for(const b of root.querySelectorAll('.pf21-daybook-tab')){b.dataset.active=String(b.dataset.tab===tab);b.setAttribute('aria-selected',String(b.dataset.tab===tab))}const nav=root.querySelector('.pf21-daybook-nav'),main=root.querySelector('.pf21-daybook-main'),side=root.querySelector('.pf21-daybook-side'),h=el('header'),today=btn('pf21-daybook-today','Return to today','Today');today.onclick=()=>{date=local();bookKey='';queue()};h.append(el('strong','',new Date(`${k}T12:00:00`).toLocaleDateString([],{month:'long',year:'numeric'})),today);nav.replaceChildren(h,calendar(k),el('div','pf21-daybook-activity',`${Object.keys(read().days||{}).length} active days`));const compose=el('section','pf21-daybook-compose'),ta=el('textarea','pf21-daybook-textarea'),saveBtn=btn('pf21-daybook-save','Save note','Save note');ta.id='pf21-daybook-compose';ta.placeholder='Capture a decision, follow-up, field observation or idea…';ta.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')saveNote()};saveBtn.onclick=saveNote;compose.append(el('header','',k===local()?"What’s on your mind?":`Add to ${label(k)}`),ta,saveBtn);if(tab==='day')main.replaceChildren(compose,el('header','pf21-daybook-section-head',label(k)),log(m));else if(tab==='notes'){const tools=el('div','pf21-daybook-tools'),input=el('input');input.type='search';input.placeholder='Search notes';input.value=search;input.oninput=()=>{search=input.value;bookKey='';queue()};tools.append(input,el('span','',`${ns.length} notes`));const cards=el('div','pf21-daybook-notes');for(const n of ns.filter(n=>!search||txt(`${n.body} ${n.category}`).toLowerCase().includes(search.toLowerCase()))){const c=el('article','pf21-daybook-note'),head=el('header'),x=btn('pf21-daybook-note-delete','Delete note','×');x.onclick=()=>removeNote(n);head.append(el('span','',n.category||'Note'),x);c.append(head,el('p','',n.body),el('small','',clock(n.updatedAt||n.createdAt)));cards.append(c)}main.replaceChildren(compose,tools,cards)}else if(tab==='calendar')main.replaceChildren(el('section','pf21-daybook-date-summary',label(k)),log(m));else main.replaceChildren(week(),el('section','pf21-daybook-long-insight',insight(m)));side.replaceChildren(analytics(m))}
function hideOld(){const ws=id('pf-local-workspace');if(ws)for(const n of [...ws.children])if(n.id!=='pf21-daybook')n.classList.add('pf21-legacy-hidden')}
function quiet(){return document.body?.dataset.quiet==='true'||Boolean(prefs().quietMode)}
function unmountQuiet(){id('pf21-dayflow')?.remove();id('pf21-daybook')?.remove();const ws=id('pf-local-workspace');if(ws){ws.classList.remove('pf21-daybook-mounted');for(const n of [...ws.children])n.classList.remove('pf21-legacy-hidden')}flowKey=bookKey=''}
function reconcile(){if(quiet()){unmountQuiet();return}patch();brand();settings();sync();renderFlow();renderBook();hideOld()}
function queue(){if(frame)return;frame=requestAnimationFrame(()=>{frame=0;try{reconcile()}catch(e){try{window.__PACEFOLD_RESILIENCE__?.recordError?.('v21-dayflow',e)}catch{}}})}
function init(){date=local();reconcile();observer=new MutationObserver(queue);observer.observe(document.documentElement,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['class','hidden','data-active','data-day-type','data-state','data-source','data-quiet','aria-selected','aria-expanded']});for(const e of ['pacefold:ma-prefs','pacefold:storage-changed','pacefold:dayflow','pacefold:quiet'])window.addEventListener(e,()=>{flowKey=bookKey='';queue()});window.addEventListener('storage',()=>{snapshot=null;flowKey=bookKey='';queue()});setInterval(queue,60000);[50,250,700,1600].forEach(setTimeout.bind(null,queue))}
window.__PACEFOLD_V21_PRECISION__={experience:EXPERIENCE,release:RELEASE,revision:REVISION,offlineCore:CORE,reconcile:queue};window.__PACEFOLD_DAYFLOW__={release:RELEASE,revision:REVISION,key:FLOW,read,events,metrics,add:moment,toggleFocus,exportDay,reconcile:queue};
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init,{once:true}):init();
})();
