'use strict';
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {chromium}=require('playwright');
const RELEASE='22.0.1';
const SPATIAL_RELEASE='22.0.0';
const REVISION='spatial-r1';
const site=path.resolve(process.argv[2]||'_site');
const artifacts=path.resolve(process.argv[3]||'/tmp/pacefold-v22-artifacts');
const app=path.join(site,'app');
const read=file=>fs.readFileSync(file,'utf8');
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
const dayKey=()=>{const d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
function staticAudit(){
  const js=read(path.join(app,'pacefold-v22-spatial.js')),hardening=read(path.join(app,'pacefold-v22-hardening.js')),css=read(path.join(app,'pacefold-v22-spatial.css')),hardeningCss=read(path.join(app,'pacefold-v22-hardening.css')),html=read(path.join(app,'index.html')),worker=read(path.join(site,'service-worker.js'));
  assert(read(path.join(site,'pacefold-experience.txt')).trim()===RELEASE,'Experience marker is stale');
  assert(js.includes(`const RELEASE='${SPATIAL_RELEASE}'`)&&js.includes(`const REVISION='${REVISION}'`),'Spatial runtime version is stale');
  for(const token of [`const RELEASE='${RELEASE}'`,'setNotifications','openSound','buildSettings','workReminders','gazeEnabled','bodyEnabled'])assert(hardening.includes(token),`Hardening runtime token missing: ${token}`);
  for(const token of ['pf22-spatial-root','buildNotes','buildWorklog','buildContext','buildSettings','pacefold:spatial-ready'])assert(js.includes(token),`Spatial runtime token missing: ${token}`);
  for(const token of ['data-pacefold-spatial="pending"','data-pacefold-v22-spatial','data-pacefold-v22-hardening','pacefold-v22-spatial.css','pacefold-v22-hardening.css','pacefold-v22-hardening.js'])assert(html.includes(token),`Spatial injection missing: ${token}`);
  for(const asset of ['pacefold-v22-spatial.css','pacefold-v22-spatial.js','pacefold-v22-hardening.css','pacefold-v22-hardening.js'])assert(worker.includes(asset),`Offline shell omits ${asset}`);
  assert(!/\.innerHTML\s*=|style\s*=\s*["']/.test(js+hardening),'Unsafe spatial DOM construction found');
  for(const token of ['.pf22-sound-overlay','.pf22-settings-panel','.pf22-control-toggle','.pf22-clock-hero::before'])assert(hardeningCss.includes(token),`Recovery visual token missing: ${token}`);
}
function serve(){return new Promise(resolve=>{const server=http.createServer((request,response)=>{let pathname='/';try{pathname=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname)}catch{}let file=path.join(site,pathname.replace(/^\/+/,''));if(pathname.endsWith('/'))file=path.join(file,'index.html');if(!file.startsWith(site)){response.writeHead(403);response.end();return}fs.readFile(file,(error,buffer)=>{if(error){response.writeHead(404);response.end();return}const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.woff2':'font/woff2','.png':'image/png','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream';response.writeHead(200,{'content-type':type,'cache-control':'no-store'});response.end(buffer)})});server.listen(0,'127.0.0.1',()=>resolve(server))})}
function prefs(){const week={};for(let day=0;day<7;day++)week[day]={start:'08:30',end:'16:30',type:day&&day<6?'desk':'off'};return{profile:'original',schemaVersion:18,theme:'paper',privacy:false,quietMode:false,timeFormat:'12',showSeconds:true,workHours:'08:30-16:30',workWeek:week,workdaysOnly:false,workReminders:true,gazeEnabled:true,bodyEnabled:true,notifications:true,browserNotif:true,notificationMode:'quiet',taskbarBadge:true,taskbarBadgeMode:'due',locationLabel:'Toronto',lat:43.6532,lng:-79.3832,waterTarget:24,sipCadence:30,waterSips:2,v21WeatherEnabled:true,waferPromptDismissed:true,activityDate:dayKey(),waterDate:dayKey()}}
function seed(){const now=new Date();return[{id:'seed-note',date:dayKey(),body:'Spatial seed note',category:'Moment',createdAt:now.toISOString(),updatedAt:now.toISOString()}]}
function weather(){const now=new Date().toISOString().slice(0,13)+':00';return{current:{temperature_2m:25,apparent_temperature:23,weather_code:0,is_day:1,precipitation:0,rain:0},hourly:{time:[now],temperature_2m:[25],precipitation_probability:[0],weather_code:[0]},daily:{time:[dayKey(),dayKey(),dayKey()],weather_code:[0,1,2],temperature_2m_max:[26,27,30],temperature_2m_min:[17,15,15],precipitation_probability_max:[0,0,3]}}}
async function contextFor(browser,viewport){const context=await browser.newContext({viewport,permissions:[]});await context.addInitScript(({settings,entries})=>{localStorage.setItem('pacefoldPrefsV15',JSON.stringify(settings));localStorage.setItem('pacefoldOnboardedV15','1');localStorage.setItem('pacefoldSetupDismissedV15','1');localStorage.setItem('pacefold.notebook.entries.v2',JSON.stringify(entries));sessionStorage.setItem('pacefoldV21AuditSeeded','1')},{settings:prefs(),entries:seed()});await context.route('**/api.open-meteo.com/**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(weather())}));return context}
async function inspectPage(page){return page.evaluate(()=>{const root=document.getElementById('pf22-spatial-root'),legacy=document.querySelector('body>main'),style=legacy&&getComputedStyle(legacy),rects=[...document.querySelectorAll('.pf22-face')].map(face=>{const r=face.getBoundingClientRect();return{name:face.dataset.face,left:r.left,top:r.top,right:r.right,bottom:r.bottom,width:r.width,height:r.height,visible:r.right>0&&r.bottom>0&&r.left<innerWidth&&r.top<innerHeight}});return{release:window.__PACEFOLD_SPATIAL__?.release,hardening:window.__PACEFOLD_HARDENING__?.release,revision:window.__PACEFOLD_SPATIAL__?.revision,mode:root?.dataset.mode,title:document.title,spatial:document.documentElement.dataset.pacefoldSpatial,legacy:style?.display,scroll:document.documentElement.scrollHeight<=innerHeight+1&&document.documentElement.scrollWidth<=innerWidth+1,faces:rects,visibleFaces:rects.filter(face=>face.visible).map(face=>face.name),edges:document.querySelectorAll('.pf22-edge').length}})}
async function controlState(page){return page.evaluate(()=>({prefs:window.__PACEFOLD_MA_CORE__?.getPrefs?.(),raw:JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}'),mode:document.getElementById('pf22-spatial-root')?.dataset.mode,controls:[...document.querySelectorAll('.pf22-control-toggle')].map(node=>({key:node.dataset.setting,text:node.textContent,active:node.dataset.active})),panels:document.querySelectorAll('.pf22-settings-panel').length,actions:document.querySelectorAll('.pf22-settings-action').length,secondsHidden:document.querySelector('.pf22-seconds')?.hidden,overlayHidden:document.getElementById('pf22-sound-overlay')?.hidden,workbenchParent:document.getElementById('pf-v19-workbench')?.parentElement?.id}))}
async function waitControl(page,label,predicate){try{await page.waitForFunction(predicate,null,{timeout:9000})}catch(error){throw new Error(`${label} did not settle: ${JSON.stringify(await controlState(page))}`)}}
async function exercise(page){
  await page.keyboard.press('ArrowUp');await page.waitForFunction(()=>document.getElementById('pf22-spatial-root')?.dataset.mode==='notes');
  const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('pacefold.notebook.entries.v2')||'[]').length);
  await page.locator('#pf22-note-input').fill('Spatial audit note');await page.locator('.pf22-capture .pf22-primary').click();
  await page.waitForFunction(value=>JSON.parse(localStorage.getItem('pacefold.notebook.entries.v2')||'[]').length===value+1,before);
  await page.keyboard.press('ArrowLeft');await page.waitForFunction(()=>document.getElementById('pf22-spatial-root')?.dataset.mode==='worklog');
  await page.locator('#pf22-worklog-focus').click();await page.waitForFunction(()=>window.__PACEFOLD_DAYFLOW__?.events?.().some(event=>event.type==='focus'&&!event.end));
  await page.locator('#pf22-worklog-focus').click();await page.waitForFunction(()=>window.__PACEFOLD_DAYFLOW__?.events?.().some(event=>event.type==='focus'&&event.end));
  await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>document.getElementById('pf22-spatial-root')?.dataset.mode==='context');
  await page.keyboard.press('ArrowDown');await page.waitForFunction(()=>document.getElementById('pf22-spatial-root')?.dataset.mode==='settings');
  await waitControl(page,'Settings rebuild',()=>document.querySelectorAll('.pf22-settings-panel').length===3&&document.querySelectorAll('.pf22-control-toggle').length===8&&document.querySelectorAll('.pf22-settings-action').length===3);
  await page.waitForTimeout(300);await page.screenshot({path:path.join(artifacts,'pacefold-v22-settings.png'),fullPage:false});
  await page.locator('.pf22-control-toggle[data-setting="weather"]').click();await waitControl(page,'Weather toggle',()=>window.__PACEFOLD_V21_PERSISTENCE__?.read?.().v21WeatherEnabled===false&&document.querySelector('.pf22-control-toggle[data-setting="weather"]')?.textContent==='Off');
  await page.locator('.pf22-control-toggle[data-setting="seconds"]').click();await waitControl(page,'Seconds toggle',()=>window.__PACEFOLD_MA_CORE__?.getPrefs?.().showSeconds===false&&document.querySelector('.pf22-seconds')?.hidden===true);
  await page.locator('.pf22-control-toggle[data-setting="notifications"]').click();await waitControl(page,'Notification shutdown',()=>{const p=window.__PACEFOLD_MA_CORE__?.getPrefs?.()||{};return p.notifications===false&&p.browserNotif===false&&p.notificationMode==='off'&&p.taskbarBadge===false&&p.taskbarBadgeMode==='off'&&document.querySelector('.pf22-control-toggle[data-setting="notifications"]')?.textContent==='Off'});
  await page.locator('.pf22-control-toggle[data-setting="notifications"]').click();await waitControl(page,'Notification restore',()=>{const p=window.__PACEFOLD_MA_CORE__?.getPrefs?.()||{};return p.notifications===true&&p.notificationMode!=='off'&&p.taskbarBadge===true&&document.querySelector('.pf22-control-toggle[data-setting="notifications"]')?.textContent==='On'});
  await page.locator('.pf22-control-toggle[data-setting="timeFormat"]').click();await waitControl(page,'Time-format toggle',()=>window.__PACEFOLD_MA_CORE__?.getPrefs?.().timeFormat==='24'&&document.querySelector('.pf22-control-toggle[data-setting="timeFormat"]')?.textContent==='24h');
  await page.locator('.pf22-settings-action[data-action="sound"]').click();await waitControl(page,'Sound ownership',()=>{const overlay=document.getElementById('pf22-sound-overlay'),workbench=document.getElementById('pf-v19-workbench'),player=document.getElementById('pf-local-player');return overlay&&!overlay.hidden&&workbench?.parentElement?.id==='pf22-sound-mount'&&getComputedStyle(player).display!=='none'});
  await page.waitForTimeout(250);await page.screenshot({path:path.join(artifacts,'pacefold-v22-sound-overlay.png'),fullPage:false});
  await page.locator('.pf22-sound-close').click();await waitControl(page,'Sound restore',()=>document.getElementById('pf22-sound-overlay')?.hidden===true&&document.getElementById('pf-v19-workbench')?.parentElement?.id!=='pf22-sound-mount');
  await page.keyboard.press('Escape');await page.waitForFunction(()=>document.getElementById('pf22-spatial-root')?.dataset.mode==='home');
}
async function browserAudit(){fs.mkdirSync(artifacts,{recursive:true});const server=await serve(),base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true}),errors=[];try{
  const context=await contextFor(browser,{width:1180,height:920}),page=await context.newPage();page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'&&!/ERR_INTERNET_DISCONNECTED/.test(message.text()))errors.push(message.text())});
  await page.goto(`${base}/app/`,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(4500);
  const startup=await page.evaluate(()=>({api:Boolean(window.__PACEFOLD_SPATIAL__),hardening:Boolean(window.__PACEFOLD_HARDENING__),spatial:document.documentElement.dataset.pacefoldSpatial,root:Boolean(document.getElementById('pf22-spatial-root')),boot:window.__PACEFOLD_V21_BOOT__,dayflow:Boolean(window.__PACEFOLD_DAYFLOW__),ready:document.readyState,title:document.title,scripts:[...document.scripts].map(script=>script.src.split('/').pop()).filter(Boolean)}));
  if(!startup.api||!startup.hardening||startup.spatial!=='ready')await page.screenshot({path:path.join(artifacts,'pacefold-v22-startup-failure.png'),fullPage:false});
  assert(startup.api&&startup.hardening&&startup.spatial==='ready',`Spatial startup did not complete: ${JSON.stringify(startup)}; browser errors: ${errors.join(' | ')}`);
  const initial=await inspectPage(page);assert(initial.release===RELEASE&&initial.hardening===RELEASE&&initial.revision===REVISION&&initial.mode==='home'&&initial.title==='Pacefold — Quiet Workday Rhythm',`Spatial startup failed: ${JSON.stringify(initial)}`);assert(initial.legacy==='none'&&initial.scroll&&initial.faces.length===5&&initial.edges===4&&initial.visibleFaces.length===1&&initial.visibleFaces[0]==='home',`Spatial geometry failed: ${JSON.stringify(initial)}`);
  await page.waitForTimeout(2200);assert((await page.title())==='Pacefold — Quiet Workday Rhythm','Window title changed after clock tick');
  const statusState=await page.evaluate(()=>{const root=document.getElementById('pf22-spatial-root'),source=document.getElementById('statusLine'),target=document.getElementById('pf22-status');return{text:target?.textContent||'',source:source?.textContent||'',sourceChildren:source?[...source.children].map(node=>({id:node.id,className:node.className,text:node.textContent})):[],sourceObserver:Boolean(root?.__pacefoldSpatialStatusObserver),timer:Boolean(root?.__pacefoldSpatialStatusTimer)}});console.log(`Spatial status contract: ${JSON.stringify(statusState)}`);assert(statusState.text.includes(' · '),`Spatial status is unreadable: ${JSON.stringify(statusState)}`);
  await exercise(page);await page.waitForTimeout(440);await page.screenshot({path:path.join(artifacts,'pacefold-v22-clock.png'),fullPage:false});
  await page.keyboard.press('ArrowUp');await page.waitForTimeout(440);await page.screenshot({path:path.join(artifacts,'pacefold-v22-notes.png'),fullPage:false});await context.close();
  const mobile=await contextFor(browser,{width:430,height:850}),small=await mobile.newPage();small.on('pageerror',error=>errors.push(error.message));await small.goto(`${base}/app/`,{waitUntil:'domcontentloaded',timeout:30000});await small.waitForFunction(()=>window.__PACEFOLD_HARDENING__&&document.getElementById('pf22-spatial-root'));await small.keyboard.press('ArrowLeft');await small.waitForFunction(()=>document.getElementById('pf22-spatial-root')?.dataset.mode==='worklog');await small.waitForTimeout(440);const geometry=await small.evaluate(()=>({scroll:document.documentElement.scrollHeight<=innerHeight+1&&document.documentElement.scrollWidth<=innerWidth+1,root:document.getElementById('pf22-spatial-root').getBoundingClientRect().toJSON(),mode:document.getElementById('pf22-spatial-root').dataset.mode,visible:[...document.querySelectorAll('.pf22-face')].filter(face=>{const r=face.getBoundingClientRect();return r.right>0&&r.bottom>0&&r.left<innerWidth&&r.top<innerHeight}).map(face=>face.dataset.face)}));assert(geometry.scroll&&geometry.mode==='worklog'&&geometry.root.width<=430&&geometry.root.height<=850&&geometry.visible.length===1&&geometry.visible[0]==='worklog',`Mobile spatial geometry failed: ${JSON.stringify(geometry)}`);await small.screenshot({path:path.join(artifacts,'pacefold-v22-mobile-worklog.png'),fullPage:false});await mobile.close();
  assert(!errors.length,`Browser errors: ${errors.join(' | ')}`);
}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}}
(async()=>{staticAudit();await browserAudit();console.log('Pacefold 22.0.1 Spatial Fold recovery audit passed.')})().catch(error=>{console.error(error);process.exitCode=1});