'use strict';
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {chromium}=require('playwright');
const RELEASE='23.0.0';
const site=path.resolve(process.argv[2]||'_site');
const artifacts=path.resolve(process.argv[3]||'/tmp/pacefold-v23-artifacts');
const app=path.join(site,'app');
const read=file=>fs.readFileSync(file,'utf8');
const assert=(ok,message)=>{if(!ok)throw new Error(message)};
const dayKey=()=>{const value=new Date();return new Date(value-value.getTimezoneOffset()*60000).toISOString().slice(0,10)};

function staticAudit(){
  const html=read(path.join(app,'index.html')),landing=read(path.join(site,'index.html')),css=read(path.join(app,'pacefold-v23.css')),runtime=read(path.join(app,'pacefold-v23.js')),worker=read(path.join(site,'service-worker.js'));
  assert(read(path.join(site,'pacefold-experience.txt')).trim()===RELEASE,'Experience marker is stale');
  assert(read(path.join(site,'pacefold-stability.txt')).trim()===`${RELEASE} ${RELEASE}`,'Stability marker is stale');
  for(const marker of ['data-pacefold-v23-boot','data-pacefold-v23-css','data-pacefold-v23-runtime'])assert((html.match(new RegExp(marker,'g'))||[]).length===1,`${marker} is not unique`);
  assert((html.match(/<link[^>]+rel="stylesheet"/g)||[]).length===13,'The active stylesheet request count regressed');
  assert((html.match(/<script[^>]+src=/g)||[]).length===13,'The active script request count regressed');
  assert(!/<link[^>]+data-pacefold-v2[12]-/i.test(html),'An individual V21/V22 stylesheet is still active');
  assert(!/<script[^>]+data-pacefold-v22-/i.test(html),'An individual V22 runtime is still active');
  assert(landing.includes('Pacefold 23 · one quiet spatial workday')&&landing.includes('Pacefold 23.0.0 · one quiet spatial workday'),'Landing release copy is stale');
  for(const token of ['@media(forced-colors:active)','@media(prefers-reduced-motion:reduce)','@media(max-width:420px) and (max-height:240px)','.pf23-seconds-dial','.pf22-settings-layout[data-hardened]','.pf22-note-calendar-controls'])assert(css.includes(token),`CSS contract missing: ${token}`);
  for(const token of [`const RELEASE='${RELEASE}'`,'__PACEFOLD_ACTIVE_RELEASE__','setNoteDate','pacefold.spatial.note.draft.v1','complete-stabilization-r4','observeReleaseTruth','window.__PACEFOLD_ACTIVE_RELEASE__||RELEASE','window.__PACEFOLD_ACTIVE_RELEASE__||EXPERIENCE'])assert(runtime.includes(token),`Runtime contract missing: ${token}`);
  for(const asset of ['pacefold-v23-boot.css','pacefold-v23.css','pacefold-v23.js'])assert(worker.includes(asset),`Offline shell omits ${asset}`);
  assert(worker.includes(`revision:${RELEASE}`),'Worker cache revision is stale');
  assert(!/\.innerHTML\s*=|style\s*=\s*["']/.test(read(path.join(app,'pacefold-v23-stability.js'))),'Unsafe V23 DOM construction found');
}
function serve(){return new Promise(resolve=>{const server=http.createServer((request,response)=>{let pathname='/';try{pathname=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname)}catch{}let file=path.join(site,pathname.replace(/^\/+/,''));if(pathname.endsWith('/'))file=path.join(file,'index.html');if(!file.startsWith(site)){response.writeHead(403);response.end();return}fs.readFile(file,(error,buffer)=>{if(error){response.writeHead(404);response.end();return}const type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json','.woff2':'font/woff2','.png':'image/png','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream';response.writeHead(200,{'content-type':type,'cache-control':'no-store'});response.end(buffer)})});server.listen(0,'127.0.0.1',()=>resolve(server))})}
function prefs(){const week={};for(let day=0;day<7;day++)week[day]={start:'08:30',end:'16:30',type:day>0&&day<6?'desk':'off'};return{profile:'original',schemaVersion:18,theme:'paper',privacy:false,quietMode:false,timeFormat:'12',showSeconds:true,workHours:'08:30-16:30',workWeek:week,workdaysOnly:false,workReminders:true,gazeEnabled:true,bodyEnabled:true,notifications:true,browserNotif:true,notificationMode:'quiet',taskbarBadge:true,taskbarBadgeMode:'due',locationLabel:'Toronto',lat:43.6532,lng:-79.3832,waterTarget:24,sipCadence:30,waterSips:2,prepPreset:'noodles',noodleMinutes:30,v21WeatherEnabled:true,waferPromptDismissed:true,activityDate:dayKey(),waterDate:dayKey()}}
async function returningContext(browser,viewport,extra={}){const context=await browser.newContext({viewport,...extra});await context.addInitScript(settings=>{localStorage.setItem('pacefoldPrefsV15',JSON.stringify(settings));localStorage.setItem('pacefoldOnboardedV15','1');localStorage.setItem('pacefoldSetupDismissedV15','1')},prefs());return context}
async function wait(page,label,predicate,arg=null,timeout=15000){try{await page.waitForFunction(predicate,arg,{timeout})}catch{throw new Error(`${label} did not settle`)}}
async function geometry(page){return page.evaluate(()=>{const root=document.getElementById('pf22-spatial-root'),clock=document.getElementById('pf22-time');return{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,viewport:[innerWidth,innerHeight],root:root?.getBoundingClientRect().toJSON(),clock:clock?.getBoundingClientRect().toJSON(),mode:root?.dataset.mode}})}

async function auditFreshSetup(browser,base,errors){
  const context=await browser.newContext({viewport:{width:1180,height:820}}),page=await context.newPage();page.on('pageerror',error=>errors.push(`fresh: ${error.message}`));
  await page.goto(`${base}/app/?setup=1`,{waitUntil:'domcontentloaded',timeout:30000});
  await wait(page,'Fresh onboarding',()=>{const node=document.getElementById('onboarding');return node&&!node.hidden&&document.body.classList.contains('onboarding-open')});
  const state=await page.evaluate(()=>({root:Boolean(document.getElementById('pf22-spatial-root')),onboarded:localStorage.getItem('pacefoldOnboardedV15'),dismissed:localStorage.getItem('pacefoldSetupDismissedV15'),title:document.getElementById('onboardingTitle')?.textContent}));
  assert(!state.root&&!state.onboarded&&!state.dismissed&&state.title==='Choose your rhythm',`Fresh setup was suppressed or pre-completed: ${JSON.stringify(state)}`);await page.screenshot({path:path.join(artifacts,'pacefold-v23-first-run.png')});await context.close();
}
async function auditDesktop(browser,base,errors){
  const context=await returningContext(browser,{width:1180,height:820}),page=await context.newPage();page.on('pageerror',error=>errors.push(`desktop: ${error.message}`));page.on('console',message=>{if(message.type()==='error'&&!/ERR_(?:INTERNET_DISCONNECTED|FAILED)/.test(message.text()))errors.push(`console: ${message.text()}`)});
  await page.goto(`${base}/app/`,{waitUntil:'domcontentloaded',timeout:30000});await wait(page,'V23 startup',()=>window.__PACEFOLD_V23__?.release==='23.0.0'&&document.getElementById('pf22-spatial-root')?.dataset.release==='23.0.0');
  await page.waitForTimeout(1200);await wait(page,'Stable V23 release truth',()=>document.documentElement.dataset.pacefoldExperience==='23.0.0'&&document.body.dataset.pacefoldExperience==='23.0.0'&&document.getElementById('pf22-spatial-root')?.dataset.release==='23.0.0');
  const initial=await page.evaluate(()=>({title:document.title,mode:document.getElementById('pf22-spatial-root')?.dataset.mode,rituals:[...document.querySelectorAll('.pf22-ritual')].map(node=>node.dataset.ritual),dial:Boolean(document.querySelector('.pf23-seconds-dial')),dayUnfold:Boolean(document.getElementById('pf22-day-unfold')),faces:[...document.querySelectorAll('.pf22-face')].filter(face=>{const rect=face.getBoundingClientRect();return rect.right>0&&rect.left<innerWidth&&rect.bottom>0&&rect.top<innerHeight}).map(face=>face.dataset.face),release:document.documentElement.dataset.pacefoldExperience}));
  assert(/^\d{1,2}:\d{2} (?:AM|PM)$|^\d{2}:\d{2}$|^Clock$/.test(initial.title)&&initial.mode==='home'&&initial.release===RELEASE&&initial.dial&&initial.dayUnfold&&initial.faces.length===1&&initial.faces[0]==='home',`Clock startup contract failed: ${JSON.stringify(initial)}`);
  assert(JSON.stringify(initial.rituals)===JSON.stringify(['water','timer','away','meal','eyes','move']),`Original rhythm controls are incomplete: ${JSON.stringify(initial.rituals)}`);
  let size=await geometry(page);assert(size.width<=size.viewport[0]&&size.height<=size.viewport[1],`Desktop overflows: ${JSON.stringify(size)}`);await page.screenshot({path:path.join(artifacts,'pacefold-v23-clock.png')});
  await page.evaluate(()=>{window.__PACEFOLD_CUES__.add('audit-water','water',60000);window.__PACEFOLD_CUES__.add('audit-prayer','prayer',60000)});await wait(page,'Source cue dots',()=>document.querySelectorAll('.pf22-cue-cluster .pf22-cue-dot').length===2);const cueColors=await page.evaluate(()=>[...document.querySelectorAll('.pf22-cue-cluster .pf22-cue-dot')].map(node=>({source:node.dataset.source,color:getComputedStyle(node).backgroundColor})));assert(cueColors.some(item=>item.source==='water')&&cueColors.some(item=>item.source==='prayer')&&new Set(cueColors.map(item=>item.color)).size===2,`Source cue colours collapsed: ${JSON.stringify(cueColors)}`);await page.evaluate(()=>window.__PACEFOLD_CUES__.clear());

  await page.keyboard.press('ArrowUp');await wait(page,'Notes',()=>document.getElementById('pf22-spatial-root')?.dataset.mode==='notes');await page.locator('#pf22-note-input').fill('Draft survives an accidental reload');await wait(page,'Draft write',()=>localStorage.getItem('pacefold.spatial.note.draft.v1')==='Draft survives an accidental reload');await page.reload({waitUntil:'domcontentloaded'});await wait(page,'Reloaded V23',()=>window.__PACEFOLD_V23__?.release==='23.0.0');await page.keyboard.press('ArrowUp');await wait(page,'Draft restore',()=>document.getElementById('pf22-note-input')?.value==='Draft survives an accidental reload');
  await page.locator('.pf22-capture .pf22-primary').click();await wait(page,'Save returns Clock',()=>document.getElementById('pf22-spatial-root')?.dataset.mode==='home'&&localStorage.getItem('pacefold.spatial.note.draft.v1')===null);assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('pacefold.notebook.entries.v2')||'[]').some(note=>note.body==='Draft survives an accidental reload')),'Saved note is missing');
  await page.keyboard.press('ArrowUp');await wait(page,'Calendar',()=>document.querySelectorAll('.pf22-note-calendar .pf22-note-day').length>=28&&document.querySelector('.pf22-note-day[data-count]:not([data-count="0"])[data-selected="true"]'));const notedDay=page.locator('.pf22-note-day[data-count]:not([data-count="0"])').first();await notedDay.click();await wait(page,'Calendar filter clear',()=>!document.querySelector('.pf22-note-day[data-selected="true"]'));await notedDay.click();await wait(page,'Calendar selection',()=>document.querySelector('.pf22-note-day[data-selected="true"]'));await page.screenshot({path:path.join(artifacts,'pacefold-v23-notes.png')});

  await page.keyboard.press('Escape');await page.keyboard.press('ArrowDown');await wait(page,'Settings',()=>document.getElementById('pf22-spatial-root')?.dataset.mode==='settings'&&document.querySelectorAll('.pf22-settings-panel').length===3&&document.querySelectorAll('.pf22-settings-action').length===4);const settings=await page.evaluate(()=>{const layout=document.querySelector('.pf22-settings-layout'),last=document.querySelector('.pf22-settings-tools'),lr=layout.getBoundingClientRect(),tr=last.getBoundingClientRect();return{columns:getComputedStyle(layout).gridTemplateColumns,client:layout.clientHeight,scroll:layout.scrollHeight,lastTop:tr.top,layoutBottom:lr.bottom,overflow:getComputedStyle(layout).overflowY}});assert(settings.columns.split(' ').length===3&&/auto|scroll/.test(settings.overflow)&&settings.client>0&&settings.scroll>=settings.client,`Settings layout is clipped: ${JSON.stringify(settings)}`);await page.screenshot({path:path.join(artifacts,'pacefold-v23-settings.png')});
  await page.locator('.pf22-control-toggle[data-setting="seconds"]').click();await wait(page,'Seconds hide',()=>document.querySelector('.pf23-seconds-dial')?.hidden===true&&document.querySelector('.pf22-seconds')?.hidden===true);
  await page.locator('.pf22-settings-action[data-action="sound"]').click();await wait(page,'Sound ownership',()=>document.getElementById('pf-local-player')?.parentElement?.id==='pf22-sound-mount'&&!document.getElementById('pf22-sound-overlay')?.hidden);const sound=await page.evaluate(()=>{const node=document.getElementById('pf-local-player'),rgb=getComputedStyle(node).backgroundColor.match(/[\d.]+/g)?.map(Number)||[];return{rgb,parent:node?.parentElement?.id,rect:node?.getBoundingClientRect().toJSON()}});assert(sound.parent==='pf22-sound-mount'&&sound.rgb.slice(0,3).reduce((a,b)=>a+b,0)>300&&sound.rect.height>300,`Sound escaped the paper visual system: ${JSON.stringify(sound)}`);await page.screenshot({path:path.join(artifacts,'pacefold-v23-sound.png')});await page.locator('.pf22-sound-close').click();await context.close();
}
async function auditViewport(browser,base,viewport,name,extra={}){const context=await returningContext(browser,viewport,extra),page=await context.newPage();await page.goto(`${base}/app/`,{waitUntil:'domcontentloaded',timeout:30000});await wait(page,name,()=>window.__PACEFOLD_V23__?.release==='23.0.0');const state=await geometry(page);assert(state.width<=viewport.width&&state.height<=viewport.height&&state.root.width<=viewport.width&&state.root.height<=viewport.height&&state.clock.width>0&&state.clock.height>0,`${name} geometry failed: ${JSON.stringify(state)}`);if(viewport.height>240)assert(await page.locator('.pf22-ritual').count()===6,`${name} lost rhythm controls`);await page.screenshot({path:path.join(artifacts,`pacefold-v23-${name}.png`)});await context.close()}
async function browserAudit(){fs.mkdirSync(artifacts,{recursive:true});const server=await serve(),base=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true}),errors=[];try{await auditFreshSetup(browser,base,errors);await auditDesktop(browser,base,errors);await auditViewport(browser,base,{width:390,height:844},'mobile');await auditViewport(browser,base,{width:340,height:150},'wafer');await auditViewport(browser,base,{width:760,height:620},'reduced-motion',{reducedMotion:'reduce'});await auditViewport(browser,base,{width:760,height:620},'forced-colors',{forcedColors:'active'});assert(!errors.length,`Browser errors: ${errors.join(' | ')}`)}finally{await browser.close();await new Promise(resolve=>server.close(resolve))}}

(async()=>{staticAudit();if(process.env.PACEFOLD_STATIC_ONLY!=='1')await browserAudit();console.log(`Pacefold 23.0.0 ${process.env.PACEFOLD_STATIC_ONLY==='1'?'static ':'complete '}stabilization audit passed.`)})().catch(error=>{console.error(error);process.exitCode=1});
