'use strict';
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {chromium}=require('playwright');
const site=path.resolve(process.argv[2]||'_site');
const artifacts=path.resolve(process.argv[3]||path.join(process.cwd(),'v24-audit-artifacts'));
const assert=(condition,message)=>{if(!condition)throw new Error(message)};
function serve(){return new Promise(resolve=>{const server=http.createServer((request,response)=>{let pathname;try{pathname=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname)}catch{pathname='/'}let file=path.join(site,pathname.replace(/^\/+/,''));if(pathname.endsWith('/'))file=path.join(file,'index.html');if(!file.startsWith(site)){response.writeHead(403);response.end();return}fs.readFile(file,(error,buffer)=>{if(error){response.writeHead(404);response.end('Not found');return}const type={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.webmanifest':'application/manifest+json','.woff2':'font/woff2','.png':'image/png','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream';response.writeHead(200,{'content-type':type,'cache-control':'no-store'});response.end(buffer)})});server.listen(0,'127.0.0.1',()=>resolve({server,origin:`http://127.0.0.1:${server.address().port}`}))})}
async function main(){
  fs.mkdirSync(artifacts,{recursive:true});
  const landing=fs.readFileSync(path.join(site,'index.html'),'utf8'),app=fs.readFileSync(path.join(site,'app','index.html'),'utf8'),worker=fs.readFileSync(path.join(site,'service-worker.js'),'utf8'),manifest=JSON.parse(fs.readFileSync(path.join(site,'manifest.webmanifest'),'utf8'));
  assert(landing.includes('Pacefold 24.0.0'),'Public website does not identify Pacefold 24');
  assert(!/\bMa\b|OneNote|verified offline core 15\.2\.2/i.test(landing),'Public website exposes an obsolete concept');
  assert(!/data-pacefold-ma|pacefold-ma\.(?:css|js)/i.test(app),'App still loads the former Ma layer');
  for(const token of ['pacefold-v24-kernel.js','pacefold-v24.css','pacefold-v24.js'])assert(app.includes(token),`App omits ${token}`);
  for(const token of ['pacefold-public-v24.css','pacefold-public-v24.js','pacefold-v24-kernel.js','pacefold-v24.css','pacefold-v24.js'])assert(worker.includes(token),`Offline worker omits ${token}`);
  assert(manifest.name==='Pacefold — Quiet Workday Rhythm','Manifest name is stale');
  const {server,origin}=await serve();const browser=await chromium.launch({headless:true});
  try{
    const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'America/Toronto'}),page=await context.newPage();
    await page.addInitScript(()=>{localStorage.setItem('pacefoldOnboardedV15','1');localStorage.setItem('pacefoldSetupDismissedV15','1');localStorage.setItem('pacefoldPrefsV15',JSON.stringify({profile:'original',lat:43.6205,lng:-79.5132,locationLabel:'Etobicoke, Toronto',timeZone:'America/Toronto',method:'15',asr:'hanafi',showSeconds:true,waterTarget:24,waterSips:2,waterDate:new Date().toISOString().slice(0,10),workHours:'08:30-16:30',noodleMinutes:30,lunchMode:'desk',notifications:false,quietMode:false}));});
    await page.goto(`${origin}/app/`,{waitUntil:'networkidle'});await page.waitForSelector('#pf22-spatial-root[data-experience="unified-r1"]',{timeout:15000});await page.waitForSelector('#pf24-instrument');
    const home=await page.evaluate(()=>({release:window.__PACEFOLD_UNIFIED__?.release,experience:document.getElementById('pf22-spatial-root')?.dataset.experience,dial:document.querySelectorAll('#pf24-dial .pf24-tick').length,actions:document.querySelectorAll('#pf23-action-dock .pf23-action').length,rhythm:document.querySelectorAll('#pf24-rhythm-strip .pf24-rhythm-item').length,fold:Boolean(document.getElementById('pf24-fold-tray')),ma:Boolean(document.querySelector('[data-pacefold-ma]')),overflow:document.documentElement.scrollWidth-innerWidth,title:document.title}));
    assert(home.release==='24.0.0','Unified runtime release is missing');assert(home.experience==='unified-r1','Unified experience did not own the root');assert(home.dial===60,'Analog clock is incomplete');assert(home.actions===6,'Six quick actions are not visible');assert(home.rhythm===5,'Main rhythm strip does not show five moments');assert(home.fold,'Visible Daybook fold is missing');assert(!home.ma,'Former Ma layer is still mounted');assert(home.overflow<=1,`Desktop overflows by ${home.overflow}px`);assert(home.title==='Pacefold — Quiet Workday Rhythm','Window title is stale');
    const schedule=await page.evaluate(()=>{const s=window.__PACEFOLD_UNIFIED__.schedule(true);return{zone:s.timeZone,muslim:s.muslim,times:s.today.map(item=>({id:item.id,stamp:item.date.getTime(),text:item.date.toISOString()}))}});
    assert(schedule.zone==='America/Toronto','Configured time zone was not respected');assert(schedule.muslim,'Original profile did not use the prayer rhythm');assert(schedule.times.length===6,'Sunrise-inclusive schedule is incomplete');assert(schedule.times.every((item,index,array)=>index===0||item.stamp>array[index-1].stamp),'Prayer schedule is not ordered');
    await page.click('#pf23-action-water');await page.waitForTimeout(250);const water=await page.evaluate(()=>window.__PACEFOLD_CORE__?.getPrefs?.()||JSON.parse(localStorage.getItem('pacefoldPrefsV15')));assert(Number(water.waterSips)>=3&&Number(water.waterLastAt)>0,'Water action did not write the current schema');
    await page.evaluate(()=>window.__PACEFOLD_SPATIAL__.go('notes'));await page.fill('#pf22-note-input','Pacefold 24 audit note');await page.click('.pf22-capture .pf22-primary');await page.waitForTimeout(900);assert(await page.locator('#pf24-fold-note-list').getByText('Pacefold 24 audit note').count()===1,'Saved note did not return to the visible fold');
    await page.evaluate(()=>window.__PACEFOLD_SPATIAL__.go('settings'));await page.waitForSelector('#pf24-settings-overview');const settings=await page.evaluate(()=>({controls:document.querySelectorAll('.pf24-setting').length,version:[...document.querySelectorAll('.pf22-version')].map(node=>node.textContent)}));assert(settings.controls===4,'Essential settings are incomplete');assert(settings.version.every(value=>value.includes('24.0.0')),'Settings expose a stale version');
    await page.evaluate(()=>window.__PACEFOLD_SPATIAL__.go('home'));await page.screenshot({path:path.join(artifacts,'pacefold-24-home.png'),fullPage:false});
    const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,timezoneId:'America/Toronto'}),m=await mobile.newPage();await m.addInitScript(()=>{localStorage.setItem('pacefoldOnboardedV15','1');localStorage.setItem('pacefoldSetupDismissedV15','1');localStorage.setItem('pacefoldPrefsV15',JSON.stringify({profile:'everyday',timeZone:'America/Toronto',showSeconds:true,workHours:'08:30-16:30',notifications:false}));});await m.goto(`${origin}/app/`,{waitUntil:'networkidle'});await m.waitForSelector('#pf22-spatial-root[data-experience="unified-r1"]',{timeout:15000});const mobileOverflow=await m.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert(mobileOverflow<=1,`Mobile overflows by ${mobileOverflow}px`);await m.screenshot({path:path.join(artifacts,'pacefold-24-mobile.png'),fullPage:false});await mobile.close();
    const publicPage=await context.newPage();await publicPage.goto(`${origin}/`,{waitUntil:'networkidle'});assert(await publicPage.locator('text=One product—not a stack of old versions.').count()===1,'Public consolidation message is missing');await publicPage.screenshot({path:path.join(artifacts,'pacefold-24-public.png'),fullPage:true});
    await context.close();console.log('Pacefold 24 unified audit passed: public site, current-only app shell, day instrument, rhythm, logging, notes, settings and responsive layout.');
  }finally{await browser.close();server.close()}
}
main().catch(error=>{console.error(error.stack||error);process.exitCode=1});
