'use strict';
const fs=require('node:fs');
const http=require('node:http');
const path=require('node:path');
const {chromium}=require('playwright');
const site=path.resolve(process.argv[2]||'_site');
const artifacts=path.resolve(process.argv[3]||path.join(process.cwd(),'v25-audit-artifacts'));
const assert=(condition,message)=>{if(!condition)throw new Error(message)};
function serve(){return new Promise(resolve=>{const server=http.createServer((request,response)=>{let pathname;try{pathname=decodeURIComponent(new URL(request.url,'http://127.0.0.1').pathname)}catch{pathname='/'}let file=path.join(site,pathname.replace(/^\/+/,''));if(pathname.endsWith('/'))file=path.join(file,'index.html');if(!file.startsWith(site)){response.writeHead(403);response.end();return}fs.readFile(file,(error,buffer)=>{if(error){response.writeHead(404);response.end('Not found');return}const type={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json','.webmanifest':'application/manifest+json','.woff2':'font/woff2','.png':'image/png','.svg':'image/svg+xml'}[path.extname(file)]||'application/octet-stream';response.writeHead(200,{'content-type':type,'cache-control':'no-store'});response.end(buffer)})});server.listen(0,'127.0.0.1',()=>resolve({server,origin:`http://127.0.0.1:${server.address().port}`}))})}
function seed(){
  const d=new Date(),today=new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10),week={};for(let day=0;day<7;day+=1)week[day]={start:'08:30',end:'16:30',type:day===0||day===6?'off':'desk'};
  localStorage.setItem('pacefoldOnboardedV15','1');localStorage.setItem('pacefoldSetupDismissedV15','1');localStorage.setItem('pacefoldPrefsV15',JSON.stringify({profile:'original',lat:43.6205,lng:-79.5132,locationLabel:'Etobicoke, Toronto',timeZone:'America/Toronto',method:'15',asr:'hanafi',showSeconds:true,waterTarget:24,waterSips:2,waterDate:today,workHours:'08:30-16:30',workWeek:week,todayOverride:{date:today,type:'half'},noodleMinutes:30,lunchMode:'desk',notifications:false,quietMode:false,taskbarBadge:true,taskbarBadgeMode:'due'}));
}
async function main(){
  fs.mkdirSync(artifacts,{recursive:true});
  const landing=fs.readFileSync(path.join(site,'index.html'),'utf8'),app=fs.readFileSync(path.join(site,'app','index.html'),'utf8'),worker=fs.readFileSync(path.join(site,'service-worker.js'),'utf8');
  assert(landing.includes('Pacefold 25.0.0'),'Public website does not identify Pacefold 25');assert(landing.includes('Recovery'),'Public website does not identify the recovery release');
  assert(!/\bMa\b|OneNote|verified offline core 15\.2\.2/i.test(landing),'Public website exposes an obsolete concept');
  for(const token of ['pacefold-v25-boot.js','pacefold-v25-recovery.css','pacefold-v25-recovery.js']){assert(app.includes(token),`App omits ${token}`);assert(worker.includes(token),`Offline worker omits ${token}`)}
  const {server,origin}=await serve();const browser=await chromium.launch({headless:true});
  try{
    const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'America/Toronto'}),page=await context.newPage();await page.addInitScript(seed);
    await page.goto(`${origin}/app/`,{waitUntil:'networkidle'});await page.waitForSelector('#pf22-spatial-root[data-recovery="recovery-r2"]',{timeout:15000});await page.waitForSelector('#pf25-dayline');await page.waitForSelector('#pf25-rhythm');
    const home=await page.evaluate(()=>({release:window.__PACEFOLD_RECOVERY__?.release,revision:window.__PACEFOLD_RECOVERY__?.revision,dial:document.querySelectorAll('#pf24-dial .pf24-tick').length,actions:document.querySelectorAll('#pf23-action-dock .pf23-action').length,rhythm:document.querySelectorAll('#pf25-rhythm .pf25-rhythm-item').length,sunrise:document.querySelectorAll('#pf25-rhythm [data-source="sunrise"]').length,daybook:document.getElementById('pf24-fold-tray')?.dataset.open,oldArc:getComputedStyle(document.getElementById('pf24-day-arc')).display,overflow:document.documentElement.scrollWidth-innerWidth,boot:document.documentElement.dataset.pacefoldV25,title:document.title}));
    assert(home.release==='25.0.0'&&home.revision==='recovery-r2','Recovery runtime release is missing');assert(home.dial===60,'Analog clock is incomplete');assert(home.actions===6,'Six quick actions are not available');assert(home.rhythm===6&&home.sunrise===1,'Prayer day must visibly include Fajr, Sunrise, Dhuhr, Asr, Maghrib and Isha');assert(home.daybook==='false','Daybook must start folded');assert(home.oldArc==='none','V24 duplicate day ribbon is still visible');assert(home.overflow<=1,`Desktop overflows by ${home.overflow}px`);assert(home.boot==='ready','Returning-user recovery boot did not settle');assert(home.title==='Pacefold — Quiet Workday Rhythm','Window title is stale');
    const day=await page.evaluate(()=>window.__PACEFOLD_RECOVERY__.resolvedDay());assert(day.type==='half','Today override did not win over the weekly schedule');assert(Math.abs(day.start-8.5)<.001&&Math.abs(day.end-12.5)<.001,'Half-day range was not resolved from the saved work week');
    const schedule=await page.evaluate(()=>{const s=window.__PACEFOLD_UNIFIED__.schedule(true);return{zone:s.timeZone,muslim:s.muslim,times:s.today.map(item=>({id:item.id,stamp:item.date.getTime()}))}});assert(schedule.zone==='America/Toronto'&&schedule.muslim,'Saved Toronto Muslim profile was not respected');assert(schedule.times.length===6&&schedule.times.every((item,index,array)=>index===0||item.stamp>array[index-1].stamp),'Prayer schedule is incomplete or unordered');
    await page.evaluate(()=>window.__PACEFOLD_CUES__.add('audit-water','water',600000));await page.waitForSelector('#pf25-cue-dots .pf25-cue-dot[data-source="water"]');await page.evaluate(()=>window.__PACEFOLD_RHYTHM__.quiet.set(true));await page.waitForTimeout(150);assert(await page.locator('#pf25-cue-dots .pf25-cue-dot[data-source="water"]').isVisible(),'Quiet mode incorrectly hid the coloured cue dot');await page.evaluate(()=>window.__PACEFOLD_RHYTHM__.quiet.set(false));
    await page.click('#pf25-cue-dots .pf25-cue-dot[data-source="water"]');await page.waitForTimeout(400);let activity=await page.evaluate(()=>window.__PACEFOLD_CORE__?.getPrefs?.()||JSON.parse(localStorage.getItem('pacefoldPrefsV15')));assert(Number(activity.waterSips)>=3&&Number(activity.waterLastAt)>0,'Water action did not preserve canonical water logging');
    await page.click('#pf23-action-eyes');await page.click('#pf23-action-body');await page.waitForTimeout(400);activity=await page.evaluate(()=>window.__PACEFOLD_CORE__?.getPrefs?.()||JSON.parse(localStorage.getItem('pacefoldPrefsV15')));assert(Number(activity.gazeLastAt)>0&&Number(activity.bodyLastAt)>0,'Eye or movement action did not preserve canonical activity keys');
    await page.click('#pf25-daybook-toggle');assert(await page.locator('#pf24-fold-tray').getAttribute('data-open')==='true','Daybook did not unfold');await page.click('#pf25-daybook-toggle');assert(await page.locator('#pf24-fold-tray').getAttribute('data-open')==='false','Daybook did not fold closed');
    await page.evaluate(()=>window.__PACEFOLD_SPATIAL__.go('notes'));await page.fill('#pf22-note-input','Pacefold 25 recovery audit note');await page.click('.pf22-capture .pf22-primary');await page.waitForTimeout(900);await page.click('#pf25-daybook-toggle');assert(await page.locator('#pf24-fold-note-list').getByText('Pacefold 25 recovery audit note').count()===1,'Saved note did not return to the folding Daybook');await page.click('#pf25-daybook-toggle');
    await page.evaluate(()=>{document.activeElement?.blur();window.__PACEFOLD_SPATIAL__.go('notes')});await page.keyboard.press('ArrowRight');await page.waitForTimeout(120);assert(await page.locator('#pf22-spatial-root').getAttribute('data-mode')==='home','Directional navigation skipped the clock instead of returning home first');
    await page.evaluate(()=>window.__PACEFOLD_SPATIAL__.go('settings'));await page.waitForSelector('#pf25-settings');const settings=await page.evaluate(()=>({recovery:Boolean(document.getElementById('pf25-settings')),essentials:document.querySelectorAll('.pf24-setting').length,version:[...document.querySelectorAll('.pf22-version')].map(node=>node.textContent)}));assert(settings.recovery&&settings.essentials===4,'Recovery settings or essential toggles are incomplete');assert(settings.version.every(value=>value.includes('25.0.0')),'Settings expose a stale version');
    await page.evaluate(()=>window.__PACEFOLD_RECOVERY__.home());await page.screenshot({path:path.join(artifacts,'pacefold-25-recovery-home.png'),fullPage:false});
    const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,timezoneId:'America/Toronto'}),m=await mobile.newPage();await m.addInitScript(seed);await m.goto(`${origin}/app/`,{waitUntil:'networkidle'});await m.waitForSelector('#pf22-spatial-root[data-recovery="recovery-r2"]',{timeout:15000});const mobileState=await m.evaluate(()=>({overflow:document.documentElement.scrollWidth-innerWidth,rhythm:document.querySelectorAll('#pf25-rhythm .pf25-rhythm-item').length,daybook:document.getElementById('pf24-fold-tray')?.dataset.open}));assert(mobileState.overflow<=1,`Mobile overflows by ${mobileState.overflow}px`);assert(mobileState.rhythm===6&&mobileState.daybook==='false','Mobile recovery surface lost prayer rhythm or folded Daybook');await m.screenshot({path:path.join(artifacts,'pacefold-25-recovery-mobile.png'),fullPage:false});await mobile.close();
    const publicPage=await context.newPage();await publicPage.goto(`${origin}/`,{waitUntil:'networkidle'});assert(await publicPage.locator('text=Recovered from the best of Pacefold').count()===1,'Public recovery message is missing');await publicPage.screenshot({path:path.join(artifacts,'pacefold-25-recovery-public.png'),fullPage:true});
    await context.close();console.log('Pacefold 25 Recovery audit passed: clean boot, saved day types, six-time prayer display, quiet cue dots, canonical logging, folding Daybook, clock-return navigation, settings, mobile and public launch.');
  }finally{await browser.close();server.close()}
}
main().catch(error=>{console.error(error.stack||error);process.exitCode=1});
