const {chromium}=require('playwright');
const fs=require('node:fs');
const path=require('node:path');
const http=require('node:http');

const current=path.resolve(process.argv[2]||'.');
const previous=process.argv[3]?path.resolve(process.argv[3]):'';
let activeRoot=current,workerGeneration=0,base='';
const results=[];
const assert=(condition,message)=>{if(!condition)throw new Error(message||'Assertion failed');};
async function check(name,fn){process.stdout.write(`RUN ${name}\n`);const detail=await fn();results.push(name);process.stdout.write(`PASS ${name}${detail?` · ${detail}`:''}\n`);}
function contentType(file){return{'.css':'text/css','.html':'text/html','.js':'text/javascript','.json':'application/json','.webmanifest':'application/manifest+json','.png':'image/png','.txt':'text/plain','.md':'text/markdown'}[path.extname(file)]||'application/octet-stream';}
function overflow(page){return page.evaluate(()=>({width:innerWidth,body:document.body.scrollWidth,html:document.documentElement.scrollWidth}));}
async function waitControlled(page){await page.waitForFunction(()=>navigator.serviceWorker?.controller,null,{timeout:12000});}
async function workerVersion(page){return page.evaluate(()=>new Promise(resolve=>{const timer=setTimeout(()=>resolve('timeout'),3000);const listener=event=>{if(event.data?.type==='PACEFOLD_VERSION'){clearTimeout(timer);navigator.serviceWorker.removeEventListener('message',listener);resolve(event.data.version);}};navigator.serviceWorker.addEventListener('message',listener);navigator.serviceWorker.controller?.postMessage({type:'PACEFOLD_VERSION'});}));}

async function main(){
  const server=http.createServer((request,response)=>{
    const pathname=decodeURIComponent(new URL(request.url,'http://localhost').pathname),relative=pathname==='/'?'index.html':pathname.endsWith('/')?`${pathname.slice(1)}index.html`:pathname.slice(1),target=path.resolve(activeRoot,relative);
    if(!target.startsWith(`${activeRoot}${path.sep}`)||!fs.existsSync(target)||!fs.statSync(target).isFile()){response.writeHead(404,{'content-type':'text/plain'});response.end('Not found');return;}
    let body=fs.readFileSync(target);if(relative==='service-worker.js'&&workerGeneration){body=Buffer.from(body.toString('utf8').replace(/const VERSION='[^']+';/,match=>match.replace("';",`-audit${workerGeneration}';`)));}
    response.writeHead(200,{'content-type':contentType(target),'service-worker-allowed':'/','cache-control':'no-store'});response.end(body);
  });
  await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});base=`http://127.0.0.1:${server.address().port}`;
  const launch={headless:true};if(process.env.PLAYWRIGHT_EXECUTABLE_PATH)launch.executablePath=process.env.PLAYWRIGHT_EXECUTABLE_PATH;
  const browser=await chromium.launch(launch);
  try{
    const desktop=await browser.newContext({viewport:{width:1440,height:1000}}),landing=await desktop.newPage();
    await check('landing identifies Pacefold 15.2.1 without overflow',async()=>{await landing.goto(`${base}/`,{waitUntil:'networkidle'});const footer=await landing.locator('footer').innerText(),size=await overflow(landing);assert(/Pacefold 15\.2\.1/.test(footer),footer);assert(Math.max(size.body,size.html)<=size.width+1,JSON.stringify(size));return footer.replace(/\s+/g,' ');});
    if(process.env.PACEFOLD_SCREENSHOTS)await landing.screenshot({path:'/tmp/pacefold15-landing-desktop.png',fullPage:true});
    await desktop.close();

    const fresh=await browser.newContext({viewport:{width:1280,height:900},permissions:['notifications']});await fresh.grantPermissions(['notifications'],{origin:base});const app=await fresh.newPage();
    const pageErrors=[];app.on('pageerror',error=>pageErrors.push(error.message));
    await check('fresh setup persists profile, routine and care',async()=>{await app.goto(`${base}/app/?setup=1`,{waitUntil:'networkidle'});await app.locator('#onboarding:not([hidden])').waitFor();assert(await app.locator('[data-onboard-profile]').count()===9,'profile count');await app.locator('[data-onboard-profile="secular"]').click();await app.locator('#onboardingNext').click();await app.locator('[data-onboard-prep="tea"]').click();await app.locator('#onboardingNext').click();await app.locator('[data-onboard-comfort="warm"]').click();const body=app.locator('[data-onboard-body]');if(!(await body.isChecked()))await body.check();await app.locator('#onboardingNext').click();await app.waitForFunction(()=>document.querySelector('#onboarding')?.hidden);const state=await app.evaluate(()=>({marker:localStorage.getItem('pacefoldOnboardedV15'),prefs:JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}')}));assert(state.marker==='1'&&state.prefs.profile==='secular'&&state.prefs.prepPreset==='tea'&&state.prefs.comfortMode==='warm'&&state.prefs.bodyEnabled,JSON.stringify(state));return 'Everyday · Tea · Warm · Care on';});
    await check('care and hydration begin with the live session',async()=>{const state=await app.evaluate(()=>JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}')),now=Date.now();for(const key of ['waterLastAt','gazeLastAt','bodyLastAt'])assert(state[key]>0&&state[key]<=now+1000&&now-state[key]<120000,`${key}: ${state[key]}`);assert(!/^Move now$/.test(await app.locator('#careBtn').innerText()),'movement debt appeared on fresh launch');return 'no inherited hydration, eye or movement debt';});
    await check('capture saves locally and unfinished text survives reload',async()=>{await app.locator('#captureBtn').click();await app.locator('#captureInput').fill('Review inspection wording with the team');await app.locator('[data-capture-kind="inspection"]').click();await app.locator('#captureForm').locator('[type="submit"]').click();let state=await app.evaluate(()=>JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}'));assert(state.captures.at(-1)?.kind==='inspection','saved capture missing');await app.locator('#captureInput').fill('Unfinished follow-up survives an update');await app.goto(`${base}/app/?capture=1`,{waitUntil:'networkidle'});await app.locator('#captureInput').waitFor();assert(await app.locator('#captureInput').inputValue()==='Unfinished follow-up survives an update','draft lost');await app.locator('#captureForm').locator('[type="submit"]').click();state=await app.evaluate(()=>JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}'));assert(state.captures.length===2,'capture count');return '2 local captures';});
    await check('notification is quiet, singular, durable and exactly-once',async()=>{await waitControlled(app);await app.evaluate(()=>{const state=JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}');state.browserNotif=true;state.notificationMode='all';localStorage.setItem('pacefoldPrefsV15',JSON.stringify(state));});await app.reload({waitUntil:'networkidle'});const outcome=await app.evaluate(async()=>{let detail=null;addEventListener('pacefold:notification',event=>{detail=event.detail;},{once:true});const permission=Notification.permission,specOnly=permission!=='granted',delivered=await window.pacefoldNotificationPreview('water',specOnly);return{detail,delivered,permission,specOnly};});assert(outcome.delivered&&outcome.detail,JSON.stringify(outcome));if(!outcome.specOnly)await app.waitForFunction(async()=>{const r=await navigator.serviceWorker.ready,n=await r.getNotifications();return n.some(item=>item.data?.source==='water');},null,{timeout:8000});const shown=outcome.detail.options;assert(shown.silent===true&&shown.requireInteraction===false,JSON.stringify(shown));assert(shown.actions?.length===1&&shown.actions[0].action==='ack',JSON.stringify(shown.actions));assert(/notification-water\.png$/.test(shown.icon),shown.icon);await app.evaluate(async()=>{const id='audit-notification-action';const cache=await caches.open('pacefold-notification-actions-v1');await cache.put(new Request(new URL(`../__pacefold-action__/${id}`,location.href)),new Response(JSON.stringify({id,action:'ack',at:Date.now(),data:{key:'audit-water',source:'water',version:'15.2.1'}}),{headers:{'content-type':'application/json'}}));});await app.reload({waitUntil:'networkidle'});await app.waitForFunction(()=>{const state=JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}');return state.waterSips===1&&state.notificationActionHistory?.filter(x=>x.id==='audit-notification-action').length===1;},null,{timeout:8000});await app.reload({waitUntil:'networkidle'});const state=await app.evaluate(()=>JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}'));assert(state.waterSips===1&&state.notificationActionHistory.filter(x=>x.id==='audit-notification-action').length===1&&Date.now()-state.waterLastAt<120000,JSON.stringify(state));return `silent · fades · one clear action · source icon · durable dedupe · ${outcome.specOnly?'headless spec':'browser delivery'}`;});
    await check('care reset records a real guided session',async()=>{await app.locator('#foldClose').click().catch(()=>{});await app.locator('#careBtn').click();await app.locator('[data-fold-action="startBody"]').click();await app.waitForTimeout(1100);await app.locator('[data-fold-action="finishBody"]').click();const sessions=await app.evaluate(()=>JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}').bodySessions||[]);assert(sessions.length===1&&sessions[0].seconds>=1,JSON.stringify(sessions));return `${sessions[0].seconds}s`;});
    await check('offline sound layer starts, ducks and stops',async()=>{await app.locator('#foldClose').click();await app.locator('#soundBtn').click();await app.locator('[data-sound-choice="brown"]').click();await app.locator('[data-fold-action="toggleSound"]').click();await app.waitForFunction(()=>document.querySelector('#soundBtn')?.classList.contains('playing'));await app.locator('[data-fold-action="toggleSound"]').click();assert(!(await app.locator('#soundBtn').getAttribute('class')).includes('playing'),'sound did not stop');return 'Brown hush';});
    await check('OneNote remains optional and local queue remains intact',async()=>{await app.locator('#foldClose').click();await app.locator('#syncBtn').click();assert(await app.locator('#oneNoteClientId').isVisible(),'client ID setup missing');const state=await app.evaluate(()=>JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}'));assert(state.captures.length===2&&state.captures.every(item=>!item.syncedAt),'local queue changed');return '2 local · no network identity configured';});
    await check('settings use four focused views instead of one long sheet',async()=>{await app.locator('#foldClose').click();await app.locator('#brandButton').click();const tabs=app.locator('[data-settings-view]');assert(await tabs.count()===4,'settings tab count');let visible=await app.locator('[data-settings-group]:visible').count();assert(visible===1,`visible groups: ${visible}`);await app.locator('[data-settings-view="app"]').click();visible=await app.locator('[data-settings-group]:visible').count();assert(visible===1&&await app.locator('[data-settings-group="app"]').isVisible(),'App settings did not become the sole view');const height=await app.locator('[data-settings-group="app"]').evaluate(node=>node.scrollHeight);assert(height<2500,`App settings too long: ${height}px`);return `Today · Rhythm · Tools · App · App view ${height}px`;});
    await check('expanded in-app self-check passes',async()=>{await app.locator('[data-settings-view="app"]').click();await app.locator('[data-action="selfCheck"]').click();await app.waitForFunction(()=>/core checks passed/.test(document.querySelector('#panel')?.textContent||''),null,{timeout:12000});const text=await app.locator('#panel').innerText();assert(!/found \d+ issue/.test(text),text);return text.match(/\d+\/\d+ core checks passed/)?.[0]||'passed';});
    if(process.env.PACEFOLD_SCREENSHOTS){await app.locator('[data-action="close"]').click();await app.locator('#captureBtn').click();await app.screenshot({path:'/tmp/pacefold15-capture-desktop.png',fullPage:true});}
    assert(!pageErrors.length,pageErrors.join('; '));await fresh.close();

    const migration=await browser.newContext({viewport:{width:1024,height:768}});await migration.addInitScript(()=>{localStorage.setItem('pacefoldOnboardedV14','1');localStorage.setItem('pacefoldPrefsV14',JSON.stringify({profile:'secular',prepPreset:'coffee',prepLabel:'Coffee',noodleMinutes:8,theme:'paper',waterSips:3,activityDate:new Date().toISOString().slice(0,10)}));});const migrated=await migration.newPage();
    await check('Pacefold 14 preferences migrate into 15',async()=>{await migrated.goto(`${base}/app/`,{waitUntil:'networkidle'});const state=await migrated.evaluate(()=>JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}'));assert(state.profile==='secular'&&state.prepPreset==='coffee'&&state.theme==='paper'&&state.waterSips===3,JSON.stringify(state));return 'profile · routine · theme · records';});await migration.close();

    const graph=await browser.newContext({viewport:{width:1180,height:860}});let graphPageContent='',graphPageTitle='',graphCreates=0,graphAppends=0;
    await graph.route('**/msal-browser-5.17.1.min.js',route=>route.fulfill({contentType:'text/javascript',body:`window.msal={PublicClientApplication:class{constructor(){this.account={username:'pacefold-audit@example.com'}}async initialize(){}async handleRedirectPromise(){return null}getActiveAccount(){return this.account}getAllAccounts(){return[this.account]}setActiveAccount(a){this.account=a}async acquireTokenSilent(){return{accessToken:'pacefold-audit-token'}}async loginPopup(){return{account:this.account,accessToken:'pacefold-audit-token'}}async acquireTokenPopup(){return{accessToken:'pacefold-audit-token'}}async clearCache(){}}};`}));
    await graph.route('https://graph.microsoft.com/**',async route=>{const request=route.request(),url=new URL(request.url()),method=request.method(),headers={'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'GET,POST,PATCH,OPTIONS','content-type':'application/json'};if(method==='OPTIONS'){await route.fulfill({status:204,headers});return;}if(url.pathname.endsWith('/notebooks')){await route.fulfill({headers,body:JSON.stringify({value:[{id:'nb1',displayName:'HSSys',isDefault:true}]})});return;}if(url.pathname.endsWith('/notebooks/nb1/sections')){await route.fulfill({headers,body:JSON.stringify({value:[{id:'sec1',displayName:'TODAY'}]})});return;}if(url.pathname.endsWith('/sections/sec1/pages')&&method==='GET'){await route.fulfill({headers,body:JSON.stringify({value:graphCreates?[{id:'page1',title:graphPageTitle}]:[]})});return;}if(url.pathname.endsWith('/sections/sec1/pages')&&method==='POST'){graphCreates++;graphPageContent=request.postData()||'';graphPageTitle=graphPageContent.match(/<title>([^<]+)<\/title>/)?.[1]||'';await route.fulfill({status:201,headers,body:JSON.stringify({id:'page1'})});return;}if(url.pathname.endsWith('/pages/page1/content')&&method==='GET'){await route.fulfill({headers:{...headers,'content-type':'text/html'},body:graphPageContent});return;}if(url.pathname.endsWith('/pages/page1/content')&&method==='PATCH'){graphAppends++;try{graphPageContent+=JSON.parse(request.postData()||'[]')[0]?.content||'';}catch(_){}await route.fulfill({status:204,headers});return;}await route.fulfill({status:404,headers,body:JSON.stringify({error:{message:'Unhandled mock Graph route'}})});});
    await graph.addInitScript(()=>{if(sessionStorage.getItem('pacefoldGraphAuditSeeded'))return;sessionStorage.setItem('pacefoldGraphAuditSeeded','1');const createdAt=Date.now(),day=`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,'0')}-${String(new Date().getDate()).padStart(2,'0')}`;localStorage.setItem('pacefoldOnboardedV15','1');localStorage.setItem('pacefoldPrefsV15',JSON.stringify({profile:'secular',captures:[{id:'audit-first',text:'First durable note',kind:'inbox',createdAt,day,syncedAt:0,syncError:''}],activityDate:day}));});const graphPage=await graph.newPage(),graphErrors=[];graphPage.on('pageerror',error=>graphErrors.push(error.message));
    async function waitGraphSynced(stage,count){try{await graphPage.waitForFunction(expected=>{const captures=JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}').captures||[];return captures.length===expected&&captures.every(item=>item.syncedAt);},count,{timeout:8000});}catch(error){const state=await graphPage.evaluate(()=>({prefs:JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}'),drawer:document.querySelector('#foldBody')?.innerText||''}));throw new Error(`${stage}: ${JSON.stringify({state,graphCreates,graphAppends,graphErrors})}`);}}
    await check('mocked OneNote flow creates, appends and deduplicates',async()=>{await graphPage.goto(`${base}/app/`,{waitUntil:'networkidle'});await graphPage.locator('#syncBtn').click();await graphPage.locator('#oneNoteClientId').fill('11111111-1111-1111-1111-111111111111');await graphPage.locator('[data-fold-action="saveOneNoteConfig"]').click();await graphPage.locator('[data-onenote-notebook="0"]').click();await graphPage.locator('[data-onenote-section="0"]').click();await waitGraphSynced('initial create',1);await graphPage.locator('#foldClose').click();await graphPage.locator('#captureBtn').click();await graphPage.locator('#captureInput').fill('Second durable follow-up');await graphPage.locator('[data-capture-kind="follow-up"]').click();await graphPage.locator('#captureForm [type="submit"]').click();await waitGraphSynced('second append',2);await graphPage.evaluate(()=>{const state=JSON.parse(localStorage.getItem('pacefoldPrefsV15'));state.captures[1].syncedAt=0;state.oneNotePages={};localStorage.setItem('pacefoldPrefsV15',JSON.stringify(state));});await graphPage.reload({waitUntil:'networkidle'});await waitGraphSynced('duplicate retry',2);assert(graphCreates===1&&graphAppends===1,JSON.stringify({graphCreates,graphAppends,graphPageContent}));return '1 page · 1 append · retry found existing capture';});await graph.close();

    const update=await browser.newContext({viewport:{width:1100,height:820}}),updatePage=await update.newPage();
    await check('worker update waits for open capture and draft survives reload',async()=>{await updatePage.goto(`${base}/app/`,{waitUntil:'networkidle'});await waitControlled(updatePage);await updatePage.reload({waitUntil:'networkidle'});await updatePage.evaluate(()=>{localStorage.setItem('pacefoldOnboardedV15','1');});await updatePage.locator('#onboardingClose').click().catch(()=>{});await updatePage.locator('#captureBtn').click();await updatePage.locator('#captureInput').fill('Do not lose this during a worker update');await updatePage.evaluate(()=>{window.__pacefoldAuditPage='original';});workerGeneration=1;await updatePage.evaluate(async()=>{const registration=await navigator.serviceWorker.getRegistration('/');await registration.update();});await updatePage.waitForFunction(async()=>{const result=await new Promise(resolve=>{const timer=setTimeout(()=>resolve(''),500);const fn=e=>{if(e.data?.type==='PACEFOLD_VERSION'){clearTimeout(timer);navigator.serviceWorker.removeEventListener('message',fn);resolve(e.data.version);}};navigator.serviceWorker.addEventListener('message',fn);navigator.serviceWorker.controller?.postMessage({type:'PACEFOLD_VERSION'});});return /audit1$/.test(result);},null,{timeout:12000});await updatePage.waitForTimeout(900);assert(await updatePage.evaluate(()=>window.__pacefoldAuditPage)==='original','page reloaded over open capture');assert(await updatePage.locator('#captureInput').inputValue()==='Do not lose this during a worker update','open draft changed');await updatePage.locator('#foldClose').click();await updatePage.waitForFunction(()=>window.__pacefoldAuditPage===undefined,null,{timeout:8000});await updatePage.locator('#captureBtn').click();assert(await updatePage.locator('#captureInput').inputValue()==='Do not lose this during a worker update','draft did not survive deferred reload');return await workerVersion(updatePage);});await update.close();workerGeneration=0;

    if(previous){
      activeRoot=previous;const upgrade=await browser.newContext({viewport:{width:1100,height:820}});await upgrade.addInitScript(()=>{localStorage.setItem('pacefoldOnboardedV14','1');localStorage.setItem('pacefoldPrefsV14',JSON.stringify({profile:'mindful',prepPreset:'tea',prepLabel:'Tea',noodleMinutes:5,theme:'dark',activityDate:new Date().toISOString().slice(0,10)}));});const upgradePage=await upgrade.newPage();
      await check('installed previous release upgrades to Pacefold 15.2.1',async()=>{await upgradePage.goto(`${base}/app/`,{waitUntil:'networkidle'});await waitControlled(upgradePage);await upgradePage.reload({waitUntil:'networkidle'});activeRoot=current;const registration=await upgradePage.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration('/');await r.update();return Boolean(r);});assert(registration,'registration missing');await upgradePage.waitForFunction(()=>{const state=JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}');return document.querySelector('#captureBtn')&&state.taskbarBadgeMode==='due'&&state.notificationMode==='quiet';},null,{timeout:15000});const state=await upgradePage.evaluate(()=>JSON.parse(localStorage.getItem('pacefoldPrefsV15')||'{}'));assert(state.profile==='mindful'&&state.prepPreset==='tea'&&state.theme==='dark'&&state.taskbarBadgeMode==='due'&&state.notificationMode==='quiet',JSON.stringify(state));return await workerVersion(upgradePage);});await upgrade.close();
    }

    activeRoot=current;const mobile=await browser.newContext({viewport:{width:390,height:844}}),mobilePage=await mobile.newPage();await check('mobile app and drawer do not overflow',async()=>{await mobilePage.goto(`${base}/app/`,{waitUntil:'networkidle'});await mobilePage.evaluate(()=>localStorage.setItem('pacefoldOnboardedV15','1'));await mobilePage.locator('#onboardingClose').click().catch(()=>{});await mobilePage.locator('#captureBtn').click();const size=await overflow(mobilePage);assert(Math.max(size.body,size.html)<=size.width+1,JSON.stringify(size));return JSON.stringify(size);});if(process.env.PACEFOLD_SCREENSHOTS)await mobilePage.screenshot({path:'/tmp/pacefold15-capture-mobile.png',fullPage:true});await mobile.close();
    const offline=await browser.newContext({viewport:{width:1024,height:768}});await offline.addInitScript(()=>localStorage.setItem('pacefoldOnboardedV15','1'));const offlinePage=await offline.newPage();await check('complete Pacefold 15.2.1 shell reloads offline',async()=>{await offlinePage.goto(`${base}/app/`,{waitUntil:'networkidle'});await waitControlled(offlinePage);await offlinePage.reload({waitUntil:'networkidle'});await offline.setOffline(true);await offlinePage.reload({waitUntil:'domcontentloaded'});assert(await offlinePage.locator('#captureBtn').isVisible(),'capture tool unavailable offline');assert(await offlinePage.evaluate(()=>Boolean(window.msal?.PublicClientApplication)),'pinned MSAL unavailable offline');await offlinePage.locator('#soundBtn').click();assert(await offlinePage.locator('[data-sound-choice="brown"]').isVisible(),'offline sound UI unavailable');return 'app · care · sound · capture · notification icons · Microsoft adapter cached';});await offline.close();
    process.stdout.write(`Pacefold browser audit: ${results.length}/${results.length} checks passed.\n`);
  }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
}
main().catch(error=>{console.error(error.stack||error);process.exitCode=1;});
